### ISSUE TITLE
Add culling of user sessions

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#100]

**Comment by betatim** [comment]
Is the way to do this to add the user culler as a systemd unit?

**Comment by betatim** [comment]
Do you think making a second systemd unit to run the culler is the way to go @yuvipanda? We could also create a cronjob but that means another kind of system service TLJH integrates with and the "run every N minutes" part of the culler seems to work well.

**Comment by yuvipanda** [comment]
apologies for coming back to issues so late! I think having it be a managed service of JupyterHub is good enough, since the culler doesn't need to run when the hub isn't running.

**Comment by yuvipanda** [comment]
@minrk Given that we already use traefik, once #313 lands, am I correct in understanding that we can just use the normal idle culler here?

**Comment by gsemet** [comment]
Yeah, culling (like in z2jh) could be very useful :) thanks for all the hard work, it makes it very easy to use jupyterhub everywhere !

**Comment by yuvipanda** [comment]
Closed by #366, thanks to @GeorgianaElena. Please test it out, @gsemet :)
