### ISSUE TITLE
Install on your own server install script doesn't work when copied

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#102]
I believe that the installation instructions won't work on the "custom server" page because if you copy/paste it into a terminal then the first line is treated as a comment and nothing is run.

I think instead, we should tell people something like:

1. Create a file called `install.sh`
   
   `nano install.sh`

2. Paste in the following lines

   ```
   #!/bin/bash
   curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin <admin-user-name>
   ```

3. Modify `<admin-user-name>` to be your user name
4. Exit and save: `ctrl+X`, "yes", `enter`
5. Run the install script:
    
    `sh install.sh`

what do you think @yuvipanda ?

**Comment by yuvipanda** [comment]
Nope, just get rid of the #!/bin/bash line. No text editors :)

**Comment by betatim** [comment]
One thing I noticed today is if you run it as is and get asked for your sudo password you end up with the prompt and curl output somehow on top of each other. Worth a call out to tell people "run curl first, then pipe it in?" Or does someone curl well enough to know of commandline options to turn of curl output?

**Comment by yuvipanda** [comment]
@betatim can you show me output / screenshot of what you are seeing? That doesn't happen for me.
