### ISSUE TITLE
Documentation on adding new normal users

### ISSUE THREAD

**Issue by betatim** [jupyterhub/the-littlest-jupyterhub#104]
After installing TLJH and successfully logging in as myself (the admin user), I thought other unix users would also be able to login. That is an incorrect assumption. After that it was a bit tricky to workout how to add new users. I found the docs on adding new admin users but not regular users. I know of the "Add Users" button in the admin panel but combined with my assumption that unix users should be able to login and seeing that FirstUseAuth is being used I ended up confused on what I should do.

Proposed fix: add a short section in "Tutorials" or "Howto Guides" on how to add a new user. (Semi related what is the difference between Tutorials and Howto Guides?)

**Comment by yuvipanda** [comment]
It's the second section of all the tutorials: https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/digitalocean.html#step-2-adding-more-users

**Comment by yuvipanda** [comment]
re: Tutorials / HowTo - great question! I had copy-pasted something from https://the-littlest-jupyterhub.readthedocs.io/en/latest/contributing/docs.html#how-the-documentation-is-organized, but it probably should be better delineated.

**Comment by GeorgianaElena** [comment]
Closing this as there are docs on how to add normal users. Thanks Tim and Yuvi :sunflower:
