### ISSUE TITLE
ReadTheDocs lags behind repo contents

### ISSUE THREAD

**Issue by betatim** [jupyterhub/the-littlest-jupyterhub#109]
http://the-littlest-jupyterhub.readthedocs.io/ seems to lag behind the [docs in this repository.

In particular I followed http://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/notebook-interfaces.html#changing-the-default-user-interface which didn't seem to do anything.

But trusting the docs I then started doubting if I had indeed restarted the hub (no visual feedback when you do it from the terminal inside your notebook server). I then became unsure about when precisely I'd see the change take effect (hub restart? hub and then single user server restart?).

After all this I tried to look at the code but it isn't super easy to find what the option should be. Though a quick grep confirmed that it probably wasn't what was written on RTD. In the end I found https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/docs/howto/notebook-interfaces.rst#changing-the-default-user-interface which works but is different from RTD. Which is the whole point of this issue.

Is this lag on purpose or accidental? I think until there is a release and some stability it would be good to keep the rendered HTML up-to-date. This lead me to make #107.

ps. should there be a new issue about increasing visual feedback about hub restarts/new config being taken into account?

**Comment by yuvipanda** [comment]
This looks accidental. I've added the other JupyterHub team members to RTD if they wanna take a look. I'm missing some users' RTD usernames tho - @jzf2101 and @consideRatio I think.

**Comment by yuvipanda** [comment]
@betatim yes, open another issue :)

**Comment by yuvipanda** [comment]
@betatim When I go to http://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/notebook-interfaces.html#changing-the-default-user-interface now I see the same thing I see in github.

**Comment by betatim** [comment]
Thank you, new issue is #112
