### ISSUE TITLE
Warn & abort if tljh-config is called as non-root user

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#120]
Is there a way to quickly double check that:

1. Sudo is invoked (e.g. by trying to do something that needs sudo)
2. -E was used (e.g. by trying to access a variable we know only exists in the user's environment)

and if one of these conditions isn't met, throw a helpful error telling them to use `sudo -E`?

**Comment by yuvipanda** [comment]
we can do (1) but not (2), since if you do 'sudo tljh-config' it will just not find the command (due to the missing path)

**Comment by choldgraf** [comment]
is there the bash equivalent of 

```
try:
    tljh-config ...
except PathErrorWhateverItsCalled: 
    raise("We couldn't find the `tljh-config` path, perhaps you didn't use `-E`?")
```
?

**Comment by choldgraf** [comment]
hey @anyushevai - I believe this is the function that's run when people run `tljh-config XXX` https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/config.py#L227

Perhaps you could run a check in there that'll only be true if the person is running as root!

**Comment by anyushevai** [comment]
@choldgraf thank you for the help!

I created a pull request https://github.com/jupyterhub/the-littlest-jupyterhub/pull/209 , please review
