### ISSUE TITLE
`tljh-config` overwriting bug

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#122]
I noticed a TLJH configuration bug in the latest TLJH. When you use `tljh-config` to add a new subsection to the YAML, it  will over-write the latest section that was written. This only happens if you try to overwrite the **same** subsection that you most-recently wrote. E.g.:

```bash
jupyter-choldgraf@tljh-demo:~/data$ sudo -E tljh-config set blah.doo hellothere

jupyter-choldgraf@tljh-demo:~/data$ tljh-config show
users:
  admin:
  - choldgraf
blah:
  doo: hellothere

jupyter-choldgraf@tljh-demo:~/data$ sudo -E tljh-config set blah.dootwo hellothere

jupyter-choldgraf@tljh-demo:~/data$ tljh-config show
users:
  admin:
  - choldgraf
blah:
  dootwo: hellothere

jupyter-choldgraf@tljh-demo:~/data$ sudo -E tljh-config set blahtwo.doo hellothere

jupyter-choldgraf@tljh-demo:~/data$ tljh-config show
users:
  admin:
  - choldgraf
blah:
  dootwo: hellothere
blahtwo:
  doo: hellothere
```

**Comment by choldgraf** [comment]
I'm gonna guess the problem is somewhere around here:

https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/config.py#L76

**Comment by yuvipanda** [comment]
I suspect this is what is causing the integration tests to fail. Would <3 if someone could take a look :)

**Comment by choldgraf** [comment]
I'll try to look into this later today if I can get other to-do items done first. I spent my morning TLJH time finishing up those doc PRs and adding these issues :-)
