### ISSUE TITLE
installer.log should not be world readable

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#142]
Since the the `/opt/tljh/` hosted configuration files (at least `/opt/tljh/` and `/opt/tljh/jupyterhub_config.d` can contain information on secret keys for authentication and other sensitive information, the file permissions for those configuration files should be tightened down so that non-admin users can't read those files if possible.  

My own testing shows there doesn't seem to be a problem with restricting reading to `root`.

**Comment by yuvipanda** [comment]
This looks mostly ok, with all config in `/opt/tljh/config` (not user readable), and state in `/opt/tljh/state` (not user readable). Only possible issue might be the installer log in `/opt/tljh/installer.log`, which is user readable. We should make it be root readable.
