### ISSUE TITLE
Better error message if git not installed.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/the-littlest-jupyterhub#150]
Currently the traceback shows :
```
Traceback (most recent call last):
  File "<stdin>", line 83, in <module>
  File "<stdin>", line 68, in main
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.
``` 

Or... rely on github tarball ?

**Comment by Carreau** [comment]
Also `systemctl` not found as well (`ubuntu:latest`, assuming that's what most people on custom servers will be running. )

**Comment by Carreau** [comment]
Might be due to the fact that I'm running in docker...Don't know if that affect systemd.

**Comment by Carreau** [comment]
> Might be due to the fact that I'm running in docker...Don't know if that affect systemd.

Yeah apparently that's the problem, Then warning in the docs that it needs to be an actual running server, and that you can't just try to install in a docker container to test that out.

**Comment by yuvipanda** [comment]
Good call! Yes, this won't work in a plain docker container because those don't ship with systemd. There's #16 for catching most of these...

**Comment by yuvipanda** [comment]
Going to close this in favor of #16
