### ISSUE TITLE
Question: Is it possible to give each user a separate pip/conda environment? (Not shared between all users)

### ISSUE THREAD

**Issue by eco32i** [jupyterhub/the-littlest-jupyterhub#154]

**Comment by minrk** [comment]
`pip install --user` certainly works if the users are in a shared conda env (it wouldn't work if we were using a shared virtualenv). There isn't a `conda install --user` for individual packages, though. Per-user conda installs can only be done by creating whole new envs:

    conda create -p $HOME/envs/my-env ipykernel pandas matplotlib

If the question is whether tljh can be configured to create per-user envs by default vs a shared env, I'm not sure if that should be an option that's in-scope for tljh or not.

**Comment by yuvipanda** [comment]
@minrk I'm convinced it is out of scope! We'll have to deal with per-user upgrades, which I've tried before and is not pretty. 

@eco32i so it looks like pip install --user is the only thing to do for now! Does that answer your question?

**Comment by eco32i** [comment]
Thanks for the clarification! I was indeed thinking about per user virtualenvs.
@yuvipanda @minrk  but in principle is this possible with jupyterhub? Through custom Spawner? What direction should I be looking?

**Comment by yuvipanda** [comment]
@eco32i yes, it's possible with general JupyterHub. See https://github.com/wikimedia/puppet/blob/production/modules/jupyterhub/templates/jupyterhub_config.py.erb#L96 for an example :)

Gonna close this one for now!

**Comment by minrk** [comment]
@eco32i yes, absolutely! You'll probably want to customize the spawner entrypoint to setup the env on launch. For example, creating this script in `/usr/local/bin/launch-singleuser`:

```bash
#!/bin/bash -l
set -eux

# if env doesn't exist, create it
ENV_DIR="$HOME/jupyterhub-env"
if [[ ! -d "$ENV_DIR" ]]; then
  # create the env
  python3 -m venv "$ENV_DIR"
  # populate it with initial packages
  # must include jupyterhub package
  "$ENV_DIR/bin/pip" install -r /usr/local/share/jupyterhub/singleuser-requirements.txt
fi
# or move pip install here to ensure correct packages on each launch

source "$ENV_DIR/bin/activate"
exec jupyterhub-singleuser "$@"
```

The `/usr/local/share/jupyterhub/singleuser-requirements.txt` should look something like:

```
# must have jupyterhub and notebook!
jupyterhub==0.9.*
notebook==5.6.*
numpy>=1.14
matplotlib>=2
```

And then you can tell jupyterhub to launch this command instead of the default:

```python
c.Spawner.cmd = '/usr/local/bin/launch-singleuser'
```

Here's a single script that will set it all up, which you can run after you have bootstrapped tljh:

```bash
#!/bin/bash

set -eu

# create requirements.txt for singleuser
echo "creating /usr/local/share/jupyterhub/singleuser-requirements.txt"
mkdir -p /usr/local/share/jupyterhub
cat <<EOF >/usr/local/share/jupyterhub/singleuser-requirements.txt
jupyterhub==0.9.2
notebook==5.6.*
numpy>=1.14
matplotlib>=2
EOF

# create entrypoint
echo "creating /usr/local/bin/launch-singleuser"
cat <<EOF >/usr/local/bin/launch-singleuser
#!/bin/bash -l
set -eux

# if env doesn't exist, create it
ENV_DIR="\$HOME/jupyterhub-env"
if [[ ! -d "\$ENV_DIR" ]]; then
  # create the env
  python3 -m venv "\$ENV_DIR"
  # populate it with initial packages
  # must include jupyterhub package
  "\$ENV_DIR/bin/pip" install -r /usr/local/share/jupyterhub/singleuser-requirements.txt
fi

# or move pip install here to ensure correct packages on each launch
"\$ENV_DIR/bin/pip" install -r /usr/local/share/jupyterhub/singleuser-requirements.txt

source "\$ENV_DIR/bin/activate"
echo "\$PATH"
exec jupyterhub-singleuser "\$@"
EOF
chmod a+rx /usr/local/bin/launch-singleuser

# tell jupyterhub to use this entrypoint
CONF_D="${TLJH_INSTALL_DIR:-/opt/tljh}/jupyterhub_config.d"
mkdir -p "$CONF_D"
echo "creating $CONF_D/custom_entrypoint.py"
cat <<EOF >"$CONF_D/custom_entrypoint.py"
c.Spawner.cmd = "/usr/local/bin/launch-singleuser"
EOF

# reload jupyterhub config
# only necessary if the jupyterhub_config.d has changed
# changes to launch-singleuser and requirements.txt
# do not need hub reloads
echo 'run `tljh-config reload hub` to reload hub config'
```

**Comment by eco32i** [comment]
@minrk  Thanks a lot! This is perfect.

**Comment by cdibble** [comment]
We ran into this problem but found `ipykernel` to be a simple method to allow users to define their own venv to use as a kernel.

So non-admin users can install ipykernel:

`pip install --user ipykernel`

Then they can create a virtual environment, activate it and pip install things there. To make it available as a jupyter kernel, they have to run (assuming their virtual environment is called `venv`):

`python -m ipykernel install --user --name=myenv`

After that, new notebooks should have the option to launch in any kernels installed as such. They can be removed with:

`jupyter kernelspec uninstall <unwanted_venv>`
