### ISSUE TITLE
JSON file viewer in JupyterLab not working

### ISSUE THREAD

**Issue by cjemmott** [jupyterhub/the-littlest-jupyterhub#155]
I am loving The Littlest JupyterHub, but ran into a problem when I try to view a JSON file with the JupyterLab UI.  It is a tiny file (<1KB), but I get an orange spinner that never resolves.  

Viewing the file in the "classic" notebook UI (/tree) works fine.  Any ideas?

**Comment by yuvipanda** [comment]
Thanks for opening this issue, @cjemmott!

@ian-r-rose any idea why this might be happening?

**Comment by ian-r-rose** [comment]
It is possible that there is a parsing error in the JSON file: might it be invalid JSON? You may be able to see errors output to the Javascript console if this is the case. You can also right-click on the JSON file in the filebrowser to open it with the text editor in order to manually inspect it.

One of my backburner fixes in Lab is to make the JSON viewer fail more gracefully, and output useful error messages when this happens.

**Comment by cjemmott** [comment]
Invalid JSON does seem to be the problem, but it seems like Python will[ happily make and read invalid JSON](https://coderwall.com/p/amb0va/python-s-json-module-does-not-always-produce-valid-json)!  

I made the file with:

```
with open("usersList.json","w") as outfile:
    json.dump(userCountList, outfile)
```

Running the file through https://jsonlint.com/ I get:

```
Error: Parse error on line 6:
..."deletedUsersDisc": NaN}, {	"tenant": 
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```
The javascript error is:

```
Uncaught (in promise) SyntaxError: Unexpected token N in JSON at position 104
    at JSON.parse (<anonymous>)
    at t.toJSON (default.js:138)
    at t._render (mimedocument.js:165)
    at mimedocument.js:82
```

I had no idea that NaN was invalid!  FYI - the legacy /tree interface also happily parses JSON with NaN values.

Thanks for the help.

**Comment by yuvipanda** [comment]
@ian-r-rose thanks for your help! Glad we could get it solved, @cjemmott!

**Comment by ian-r-rose** [comment]
x-ref for improving the error reporting for the JSON viewer: https://github.com/jupyterlab/jupyterlab/issues/4490
