### ISSUE TITLE
check/change default umask

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/the-littlest-jupyterhub#158]
While walking in central valley today I came across a wild jupyterhub running in a grass field. It was used to teach R. Admins were surprised that students could see each other files.

Would it make sens to me to change the umask to 025 (I believe), use the `-M 750` of `adduser` when possible (not available on Ubuntu AFAICT), or at least `subprocess.check_call(['chmod','0750', f'~{user}'])`.

It seem to be a reasonable default IMHO

**Comment by yuvipanda** [comment]
This was fixed in #169
