### ISSUE TITLE
500 error after installing tljh

### ISSUE THREAD

**Issue by simonlindgren** [jupyterhub/the-littlest-jupyterhub#164]
After a successful install of tljh, I now ran into a 500 error when logging in in my browser. Any ideas?

**Comment by yuvipanda** [comment]
@simonlindgren can you provide logs for JupyterHub using https://the-littlest-jupyterhub.readthedocs.io/en/latest/troubleshooting/logs.html#jupyterhub-logs? Thanks!

**Comment by yuvipanda** [comment]
The last line there seems to imply the notebook service couldn't start. Can you find the logs of the user `digsum` (with sudo journalctl -u jupyter -digsum --no-pager) and show that here?

Apologies for the late response, recovering from JupyterCon :)
