### ISSUE TITLE
Figure out process for translating guide to other languages

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#166]
We should translate TLJH into lots of languages. There are several challenges to be overcome here:

1. How will commit rights work? A lot of the current maintainers do not actually know non-english languages, so we should figure out a process for how this works.
2. How to make sure things are accurate? When we add new content or fix bugs in our current content, we need to make sure that either other languages are updated, or there's an easy way to flag that this has changed.

This is very important work, and we should spend time and effort on it!

https://docs.readthedocs.io/en/latest/localization.html is some info on how RTD does localization.

**Comment by henfee** [comment]
Yes, it's very important to help other users no speaking English. 
I  had tried to do this by translating jupyter notebook UI from English into Chinese a few months ago, as 
[nootbook_i18n_Chinese](https://github.com/henfee/jupyter_notebook_i18n)

**Comment by yuvipanda** [comment]
Many many other projects do this, so let's keep this open.
