### ISSUE TITLE
enable RStudio drop-down menu

### ISSUE THREAD

**Issue by aculich** [jupyterhub/the-littlest-jupyterhub#176]
A lot of people will want to be able to have R/RStudio enabled by default in a drop-down menu, so having those instructions available in TLJ would be helpful, but that's missing at the moment:

![image](https://user-images.githubusercontent.com/118965/45194632-ac008d80-b208-11e8-9464-4fbedf525fb7.png)

**Comment by yuvipanda** [comment]
See #18. There are unfortunately a number of problems with getting RStudio to work in this kinda non-containerized environment.

**Comment by yuvipanda** [comment]
Closing as dupe of #18
