### ISSUE TITLE
Using exising user accounts?

### ISSUE THREAD

**Issue by mangecoeur** [jupyterhub/the-littlest-jupyterhub#177]
I didn't actually try an installation yet, but reading the docs/code as i understand it, this config will always create new users with a `jupyter-` prefix. We use our server for a range of services so everyone has their own standard linux user account - is it supported to just use the existing user accounts?

**Comment by yuvipanda** [comment]
Unfortunately that's something we explicitly decided against. See https://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/security.html#system-user-accounts, especially:

> The unix user account created for a JupyterHub user named <username> is jupyter-<username>. This prefix helps prevent clashes with users that already exist - otherwise a user named root can trivially gain full root access to your server.

It's unclear how exactly to support existing user accounts without complicating the code base too much. Currently, if you wanna use existing user accounts you'll have to set up JupyterHub manually I'm afraid.

**Comment by mangecoeur** [comment]
Fair enough, thanks anyway!

**Comment by davide84** [comment]
Hi! I'm in the same situation of mangecoeur, I manage a server where home folders are centralized, customized and shared... and having a duplicate set of users and home folders is a no-go.
I know this is an old issue, but I guess there could be better solutions to the problem of hijiacking users. First of all, Ubuntu and other distros have no explicit root user :) but a more general solution could be to check if a /home folder already exists to validate a legitimate user. cups, www-data and other "system" users don't have a home folder, only real users do. Hope this can be of interest.

**Comment by PaleNeutron** [comment]
I think the problem should not be 

> a user named root can trivially gain full root access to your server

JupyterHub provide `sudo` for admin users without password, which is dangerous enough.

Developer could use some limit, for example put root in default blacklist or even hard-coded, to avoid most of risks.

Force every users of server need to maintain two environment is ridiculous and thus we have no way to move the existing users into Jupyterhub environment.

**Comment by mangecoeur** [comment]
@PaleNeutron I made a detailed guide for setting up jupyterhub manually:

https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html

Of course, not as easy as having an automated install script, but on the other hand if you are installing to an existing system you might want to anyway customize how it works (e.g. I have it set up so there is a mix of read-only python envs and user-installable ones, so there is always a working env to fall back on if the users bork theirs)

**Comment by davide84** [comment]
I ended up using JupyterHub with LDAP authentication. Actually, all the users on the server are LDAP accounts, except for the single user defined during OS installation. I don't use jupyter-xxx accounts at all. So far it's working as I wanted to...

I followed mangecoeur's guide for the most part, back in June.
