### ISSUE TITLE
Works with Amazon Web Services (AWS)

### ISSUE THREAD

**Issue by fomightez** [jupyterhub/the-littlest-jupyterhub#182]
Finally got time to try this. It works well! Super easy.

I want to share my notes from getting it working on AWS in case it helps anyone. I saved images to work up into a user-friendly tutorial. (SEE **UPDATE** at bottom.) In case it helps anyone in the interim...

I'll spill the three tricks for those who may be vaguely familiar with AWS already:
a) Currently the AMI I found that works is:

Under Quick-start, about 3/5 of the way down the page, select **.NET Core 2.1 with Ubuntu Server 18.04 - Version 1.0  (ami-e24b7d9d)**.

b) You can do a step where you run a startup script like step# 18 under the 'Installing on Google Cloud' instructions.

To do that in AWS, go to what is currently **Step 3: Configure Instance Details** while working through the 'Launch Instance Wizard' and then go to the bottom of the page and toggle the drop-down next to **Advanced Details**. The only advanced detail there is a box where you can add **User data**. Paste in the startup script there.

c) Open port 80 (HTTP) in security group settings.

Beyond that, be patient.  
I found it took 10 minutes or so on a large instance before it was able to be logged into. You can monitor it somewhat by viewing the **System Log** by going to the EC2 Management Console, highlight the instance, and right-click `Instance Settings` > `Get System Log`. I never saw anything that said `Done` but I did see `Started jupyterhub service`. When I did the script on the command line via SSH it would actually get hung up after `Starting TLJH installer...` but then work after some time when I tried connecting in the browser.

UPDATE: The installation guide for Amazon Web Services (AWS) is now incorporated in the latest version.

**Comment by mrice88** [comment]
This is awesome!
