### ISSUE TITLE
tljh-config not on the path after install

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#185]
Note that this is on Azure, so not sure if this is something Azure specific or not, but...

When I install TLJH using a VM on Azure, the hub install correctly w/ my username etc, however `tljh-config` is not accessible by the command line.

If I then re-run the "install" script with

`curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 - --admin <admin-user-name>`

then the upgrade works, and `tljh-config` is now accessible.

This seems like a bug somewhere, just putting this here to keep track of

**Comment by choldgraf** [comment]
I was thinking this might be an issue with not using `-E`, though I noticed that throughout the TLJH guide we use `tljh-config` without `-E`. e.g.: https://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/env/notebook-interfaces.html

**Comment by yuvipanda** [comment]
We put it in /usr/bin now, solving this problem.
