### ISSUE TITLE
SSH into JupyterHub user

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/the-littlest-jupyterhub#198]
If you want to scp content into a user's home directory how would one do that? I have a small TLJH on GCP and we haven't been able to figure out how to use SCP to move data.

**Comment by jzf2101** [comment]
@yuvipanda https://github.com/jupyterhub/the-littlest-jupyterhub/issues/12

**Comment by willingc** [comment]
@jzf2101 I think you need to use `gcloud compute scp` [ref](https://cloud.google.com/sdk/gcloud/reference/compute/scp)

**Comment by jzf2101** [comment]
What if you're not admin?

**Comment by willingc** [comment]
Can you not do user@...?

**Comment by willingc** [comment]
Also see: https://cloud.google.com/compute/docs/instances/transfer-files You will need an ssh-key for the user and can try running the command with `--dry-run`

**Comment by jzf2101** [comment]
I think we're gonna try just the upload button for now.

**Comment by cappellino** [comment]
Found a way to enable SSH in TLJH:
Using the command "sudo passwd -aS" it shows that jupyter-users are associated with the flag "L"="Locked-Password".
The admin should reset the jupyter-user password with the command "sudo passwd jupyter-user".
After this it is possible to login via SSH. Optionally change the shell with "chsh -s /bin/bash" .
Note that after this the jupyter-user will have 2 passwords, one for the OS and one for TLJH!
