### ISSUE TITLE
Delays and 500/503 errors

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/the-littlest-jupyterhub#199]
@koustuvsinha and I are looking into setting up a TLJH for his class and have gotten a few delays and 500/503 errors from a small GCP instance running CUDA with 1 GPU.  How does one get logs and figure out how to debug the instance when one can get to the jupyter server but there are issues getting to run the code you want to run?

**Comment by willingc** [comment]
I think you can view log in the `/var/log` directory.

**Comment by jzf2101** [comment]
Sounds good thanks. I'll keep track of that from now on.

**Comment by yuvipanda** [comment]
There's now docs on looking at logs, for hub as well as each individual user, in http://tljh.jupyter.org/en/latest/troubleshooting/logs.html.
