### ISSUE TITLE
Using Terraform to install TLJH on AWS

### ISSUE THREAD

**Issue by joshuakalla** [jupyterhub/the-littlest-jupyterhub#200]
I created a repository to install TLJH on an AWS instance using Terraform to simplify the set-up process. Check out https://github.com/joshuakalla/tf-jupyterhub-aws. You might want to update the Docs. I'm happy to help on this if you would be interested.

**Comment by choldgraf** [comment]
Hi @joshuakalla - thanks for the suggestion, your terraform implementation looks cool!

I'm a little hesitant to incorporate this into the TLJH docs, as we're scoping this documentation to be mostly GUI-based when it comes to creating the VM and installing JupyterHub. We probably can't assume that the target audience for TLJH knows what terraform is, unfortunately :-/  I'm open to hearing differing opinions on this if others think otherwise!

**Comment by willingc** [comment]
Hi @joshuakalla, 

Thanks for sharing the terraform install for AWS. Initially, these repo was created as a simpler implementation of JupyterHub for education where the person setting up JupyterHub may have no or limited devops and sysadmin experience.

There's definitely value to a Terraform implementation. I agree with @choldgraf that this may not be the best place to host given the original goal of who TLJH would serve. That said, I can see there be interest in more automated deployment using Terraform (as mentioned here) or an API approach like doctl for Digital Ocean. I'm honestly not sure where the best place to put these sorts of deployments. I could see there being a page that links out to community projects initially.

**Comment by choldgraf** [comment]
+1 to @willingc 's idea about community projects

**Comment by choldgraf** [comment]
@joshuakalla totally makes sense, and I agree that terraform can be quite useful! Your paragraph there sounds like a nice introduction to a short guide that we can link to :-)

**Comment by yuvipanda** [comment]
Writing this up as a topic in discourse.jupyter.org and adding the tag 'tip' might be the way to go? This puts it in a convenient simple place, and allows others to comment / modify it if needed.

**Comment by yuvipanda** [comment]
I have done this now! I hope I credited you properly in https://discourse.jupyter.org/t/tip-setting-up-the-littlest-jupyterhub-on-aws-with-terraform/168, @joshuakalla! Thank you very much!!!! <3

I'm going to close this for now, do re-open if we wanna expose these in different ways.
