### ISSUE TITLE
Unable to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by xtutran** [jupyterhub/the-littlest-jupyterhub#206]
Hi,

I am facing on this error on Ubuntu 14.04 

This is error when I was trying to use ``bootstrap.py``
```
Upgrading TLJH installer...
Traceback (most recent call last):
  File "bootstrap.py", line 83, in <module>
    main()
  File "bootstrap.py", line 68, in main
    ] + pip_flags + [tljh_repo_path], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1
```

This is something when I was trying to run ``setup.py``

``
sudo /opt/tljh/hub/bin/python3.4 setup.py install
``

Error message
``
error in the-littlest-jupyterhub setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
``

This is a little bit strange to me. Do you guys have any idea?

Thank you,
Tran

**Comment by minrk** [comment]
the-littlest-jupyterhub requires Ubuntu >= 18.04. My guess is the errors come from setuptools and/or Python being too old (Python 3.4 will not work).

**Comment by choldgraf** [comment]
@minrk perhaps we should add a short "requirements" section to the index page? https://the-littlest-jupyterhub.readthedocs.io/en/latest/

**Comment by betatim** [comment]
It is mentioned here https://the-littlest-jupyterhub.readthedocs.io/en/latest/#installation

**Comment by choldgraf** [comment]
yeah, just a subsection for "requirements" even if it's followed by just that sentence would make things more explicit IMO

**Comment by willingc** [comment]
Why not put it in an important directive?

**Comment by xtutran** [comment]
> the-littlest-jupyterhub requires Ubuntu >= 18.04. My guess is the errors come from setuptools and/or Python being too old (Python 3.4 will not work).

Hi,

Thanks for the info! I just realised that there might more issues with Ubuntu 14.04. So I think I will give another try in Ubuntu 18.04

Thanks

**Comment by choldgraf** [comment]
hey @xtutran - does this seem to have worked for you? :-)

**Comment by yuvipanda** [comment]
Fixed in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/221 tos how better error messages.
