### ISSUE TITLE
Is TLJH scoped for local installs as well?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#210]
Right now all of our instructions etc assume that people are working from cloud VMs. What if they had Ubuntu 16+ running on their own laptop? Is that out of scope for TLJH? If not, I think that it would be useful to provide instructions for how people can do this!

**Comment by betatim** [comment]
I've setup TLJH on a machine "not in the cloud" but in a room I can walk to. Not quite sure I understand the direction you are going in. Should it be more explicit that "any machine that can run a new enough version of Ubuntu will do, you don't have to pay a cloud hoster" is a legit option?

**Comment by choldgraf** [comment]
Yeah basically that's what I'm interested in :-)

E.g. with a cloud VM you say things like "expose these connections (HTTP, SSH, etc) to the outside world" and it gives you a public IP address. What would that look like if you had your own local machine? That kinda thing

**Comment by choldgraf** [comment]
I think just saying something like this:

> if we assume:

> you have root on a recent-enough ubuntu
the machine is already accessible on the Internet via ip and/or DNS
then everything is the same other than looking up the public ip (curl http://ifconfig.co works for simple cases).

would be helpful for people with questions. Even better if we can give some links or short steps to exposing the IP of the machine to the internet

**Comment by yuvipanda** [comment]
This is the intent behind https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/custom-server.html. Maybe that is unclear in the intro to it in the index page?

We should explicitly tell people to *not* install it on their laptops. It opens up massive security holes, and can also do lasting damage to your data if we end up with a bug someplace.
