### ISSUE TITLE
Allow running TLJH under a URL prefix

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#216]
Currently TLJH runs in the root of the domain (example.com), and can not easily work under a URL prefix (example.com/hub). Would be nice to support this.

Requested by @mdogy

**Comment by minrk** [comment]
Setting `c.JupyterHub.base_url = '/jupyterhub/'` should be everything that's needed for this, so I think this should just be a docs update.

**Comment by tkang007** [comment]
Hello,

Thanks. It worked correctly by setting c.JupyterHub.base_url.

How about traefik.toml for sharing with other services, such as nbviewer.

I tried as below and it worked.
pip install nbviewer  at TLJH user(conda) env.
python3 -m nbviewer --localfiles=/public --port=5000

For setting based on traefik service. 
It looks like possible by updating traefik.toml.tpl at soruce.  

Do you have any guide for sharing traefik service ?  

Thanks in advance.

**Comment by tkang007** [comment]
Hi,

Below is my  updating traefik.toml to share treafik service between jupyterhub and nbviewer.
nbviewer is an public web service based on docker container, just sharing public folders with jupyterhub by mounting the folders at the container. 

## Default of TLJH
#[frontends]
#  [frontends.jupyterhub]
#  backend = "jupyterhub"
#  passHostHeader = true
#
#[backends]
#  [backends.jupyterhub]
#    [backends.jupyterhub.servers.chp]
#    url = "http://127.0.0.1:15003"
#

## ========================================
## Customizing to share traefik service between multiple web services with url prefix
## Priority: Routes will be sorted (in descending order) using rules length (to avoid path overlap) by default.
##            The priority value override the rule length during sorting.
## ========================================
[frontends]
  [frontends.default]
    backend = "jupyterhub"
    passHostHeader = true    
    priority = 100    
    [frontends.default.routes.rule1]
      rule = "Path:/;AddPrefix:/jupyterhub"

  [frontends.jupyterhub]
    backend = "jupyterhub"
    passHostHeader = true
    priority = 90    
    [frontends.jupyterhub.routes.rule1]
      rule = "PathPrefix:/jupyterhub"

  [frontends.nbviewer]
    backend = "nbviewer"
    passHostHeader = true
    priority = 80    
    [frontends.nbviewer.routes.rule1]
      rule = "PathPrefix:/nbviewer"

[backends]
  [backends.jupyterhub]
    [backends.jupyterhub.servers.chp]
      url = "http://127.0.0.1:15003"

  [backends.nbviewer]
    [backends.nbviewer.servers.nbv]
      url = "http://127.0.0.1:25000"    


Welcome any better approaches.

**Comment by ikhoury** [comment]
Hello,

I added an `extra_config.py` file under `/opt/tljh/config/jupyterhub_config.d/` with `c.JupyterHub.base_url = '/jupyter/'`. However, when I run `tljh-config reload hub` it does not exit and remains stuck in a loop with the following continuous output:

```
/opt/tljh/hub/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1' etc...
```
