### ISSUE TITLE
Allow disabling traefik?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/the-littlest-jupyterhub#218]
Right now, we have traefik in the front as the SSL termination service. When not using letsencrypt, traefik isn't really doing anything other than routing public `http.port` to CHP.

For folks who would like to have other SSL termination/site setups, e.g. with nginx, simply disabling traefik and taking responsibility for SSL termination, etc. could be as simple as:

```yaml
traefik:
  enabled: false
```

then tljh assumes that something else is responsible for routing. I specifically want to exclude modifying the CHP service to be the public face in this case. I think if something like this is in-scope, the *only* result of this configuration should be that the traefik service is not running, no other changes.

From conversation with @mdogy on Gitter

**Comment by yuvipanda** [comment]
Is there a reason to make this be user tweakable other than for efficiency purposes? If efficiency is the only reason, IMO we should not make it user configurable, since it adds a bunch of extra conditionals everywhere. Longer term, we can hopefully replace CHP with just Traefik.

**Comment by yuvipanda** [comment]
We no longer run CHP, and traefik is our proxy so we're good here :D
