### ISSUE TITLE
Make bootstrap.py work better with intercepting proxies

### ISSUE THREAD

**Issue by fm75** [jupyterhub/the-littlest-jupyterhub#219]
Issue #11 Addresses the need to document getting the environment to be used by `sudo -E`. I managed to install `TLJH` successfully this morning on an `ubuntu 18.04` instance running in an OpenStack private cloud. Things that I encountered that required it.

- http(s)_proxy settings to get through our firewalls
- SSL error from requests installing `Miniconda3`
- SSL error from `npm`

I believe that these can all be addressed by updating [Installing on your own server](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/custom-server.html)

Before the `sudo apt-get install python3 git curl`

    export http_proxy=<your_proxy>
    export https_proxy=<your_proxy>
    export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates
    sudo npm config set strict-ssl false

and then insert " -E " in the pipe to python3:
```bash
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin <admin-user-name>
```

**Comment by fm75** [comment]
I have a [documentation only change for this](https://github.com/fm75/the-littlest-jupyterhub/blob/documentation-behind-proxy/docs/install/custom-server.rst). Please let me know if you would like a PR for it.

**Comment by choldgraf** [comment]
hey @fm75 - thanks for catching this! Documentation improvements are *always* welcome! Do you see any downsides to including these changes as part of the default "on your own server" TLJH install? 

One thing I wonder is whether there should be another section to the custom server install page, called something like "common gotchas" where we can list things like configuring SSL properly etc. What do you think?

**Comment by fm75** [comment]
@choldgraf - Thanks. I wouldn't know about 'common gotchas'. I think the "custom server install" opens up a range of things that the cloud solutions don't have because they have made choices on a number of configuration options. 

### Troubleshooting
There is a "chapter" in the docs for Troubleshooting. Currently it only has:
- Looking at logs. 
  - (Perhaps this might be improved. I felt that I need to understand more about how the logging was working to investigate some stuff. That said, I think the stuff that I had the biggest problem with was because I tried to delete a user, then tried to add him back - long story)
- Google Cloud
- Amazon Web Services.

I suppose adding a section for Custom Server would be useful.

### With a firewall
- Need proxy settings to get out for the installation.
- Might need to be able to modify them on demand, to stay local, 
  - To use the URL of the requirements.txt option.
  - To reach other URLs behind the firewall - lessons, data, etc.
- I have not been able to configure SSL properly so far. 
  - I am terrible at managing SSL 
- I think having only local DNS for my server breaks the Let's Encrypt instructions.

### PR?
- How/should I proceed for documentation only?
- In Contributing - Getting the raw documentation "...get the development version of TLJH...". I don't see a `development branch`, just master and a couple of patches. Is development version simply master, here?
- If I submitted a PR, would I see whether or not it passed CI and what was wrong if it failed?
- Happy to help.
- Won't be disappointed if you just want issues for someone else to fix.

**Comment by choldgraf** [comment]
Hey @fm75 - thanks for these helpful points. I think you've started chipping away at these in some other PRs etc so we can spot-check some stuff there.

Re: your broader point about providing lots of new information about running this on a custom server, I wonder what @yuvipanda think about this. I wanna make sure that we keep TLJH in-scope, but I'm not sure exactly what the scope is meant to be. I guess my main question here is: at what point of customization do we start telling people "don't use TLJH, instead just install JupyterHub from scratch on your own (the old-fashioned way!)", and then improve the documentation for that. Would love to hear people's thoughts

**Comment by fm75** [comment]
Most of the differences that I have found, I believe, are related to running a server on a private ip network, so a proxy setup was needed to get out. I don't know if this is common for `.edu`, but I used this setup today, successfully for in-house training. My instance is on an `OpenStack VM`, so the certificate management may not have been set up sufficiently for this to work, where it might have been on `.edu` servers, or somebody took care of it. 

But I really liked this simple installation. Even if I pursued this further and set up a more conventional kubernetes/docker JH, I still think that the simple install is great because it could be spun up on demand for classes, then torn down when done.

I might actually fork this and modify the install to run from the fork - where it could contain the few extra features to make it just work without manually tweaking them.

If mine is not "in-scope", ok.  But, it was close enough for me to make it work quite quickly. It provided a good learning experience - so maybe a gateway to full JH - and I hope, even, an internal binder installation.(?)

**Comment by yuvipanda** [comment]
Heya! I think providing information on running behind firewalls (esp. ones with unrestricted HTTPS proxies, as yours seems to be) is in scope. I left comments in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/230 on how I think this could be structured.

**Comment by yuvipanda** [comment]
@fm75 and for setting up a version that would 'just work', we could possibly investigate creating a plugin (http://tljh.jupyter.org/en/latest/contributing/plugins.html). This might not be possible if the changes need to be in the bootstrap process though.

**Comment by fm75** [comment]
Add to troubleshooting - what happens if you misconfigure HTTPS.
- If key/certs are misconfigured Traefik won't start on reload
- Its failure to restart is not obvious
- HTTP access continues to work
- add journalctl command that can be used to investigate, perhaps with example output.

**Comment by fm75** [comment]
This issue grew into a number of separate items, some of which have been addressed. 

The cert problem mentioned directly above can be added to troubleshooting. I can do that.

The LetsEncrypt mechanism for setting up HTTPS won't work behind a proxy. 

As to getting bootstrap.py to figure it out, I suppose it could do something like testing for being able to access example.com or even some jupyter.org resource. If it failed, then it could log an error suggesting that one possible problem could be that if there is a proxy needed that it needs to be set up in the environment.

Should this issue be closed and new ones opened for the remainder of unaddressed issues?

**Comment by yuvipanda** [comment]
Apologies for the (very) late response. I think we can move this into two separate actionable issues:

1. Document that Let's Encrypt won't work in a private network
2. Have bootstrap.py print better error messages when it can't reach the public internet.

I've opened a new issue (#330) for (1) and updated (#16) to account for 2. I'm going to close this now, but feel free to re-open / open new issues.

Again, I apologize for letting this be unanswered for so long, @fm75
