### ISSUE TITLE
Write installation / bootstrap logs to somewhere persistent 

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#22]
It'd be helpful if we had language specifically about how to debug the installation process. The biggest "black box" moment of this is the `curl` script, and in this case users don't know if anything works until *everything* works (more or less).

The `logs` section describes how to debug a functioning JupyterHub, but what happens if something goes wrong with the install process? It looks like the python script is printing things to stdout, but that isn't being written to a place that users can access via SSH in case the JupyterHub doesn't pop up as expected. Is that right?

**Comment by yuvipanda** [comment]
This is right! The install process itself is a bit opaque now, and I'm not entirely sure how to make that better. Obvious clear ways are:

1. Make sure the install process is writing logs to somewhere useful on disk that is going to persist
2. Find some way of showing progress without requiring SSH

(1) is easier than (2)...

**Comment by choldgraf** [comment]
I'm +1 on 1 for now, it'd be pretty straightforward and I think that most VM providers provide a "relatively" easy way to SSH into the VM instance.
