### ISSUE TITLE
Q: Poring to CentOS and some questions

### ISSUE THREAD

**Issue by tkang007** [jupyterhub/the-littlest-jupyterhub#222]
Hello Heroes,

I have tried TLJH at Ubuntu 18.04, everything worked well.

Please let me ask these questions? 

Do you have any plan to port at CentOS 7  (it almost compatible with RedHat) ?
I think there might not big porting issue, and I can try to porting.
Could you give me any comments ?

At the first try, I met an timeout error as below:
With setting for http_proxy, https_proxy and no_proxy, it was failed urlopen()  at installer.py.
This failure was same with wget command, and succeed when I use localhost instead of 127.0.0.1.
I am not sure,  but it might not on the installer.py.

def ensure_jupyterhub_running(times=4):
   ...
    for i in range(times):
        try:
            logger.info('Waiting for JupyterHub to come up ({}/{} tries)'.format(i + 1, times))
            urlopen('http://127.0.0.1')
      ....
    raise Exception("Installation failed: JupyterHub did not start in {}s".format(times))

Thanks in advance.

**Comment by tkang007** [comment]
I have tested with CentOS 7 after just small code changing for using yum instead of apt. 
use 'yum install -y python36' and 'ln -s /bin/python36 /bin/python3',
no need to install python3-venv as venv was included std lib.
Thanks.

**Comment by tkang007** [comment]
During testing,  I found systemd need to be upgrade for systemd sandbox features:

On the CentOS 7.5 version, I have succeed by two things:
- update code to use yum instead of apt
- upgrade systemd version to 234 from 219.  

System preparations:  
## required packages install

yum install -y git curl

## Python 3 install

sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
sudo yum update
sudo yum install -y python36u-pip

sudo rm -f /bin/python3
sudo ln -s /bin/python3.6 /bin/python3
sudo ln -s /bin/pip3.6 /bin/pip3

## systemd version upgrade for systemd sandboxing features (ProtectSystem-strict,PrivateTmp=...)
System default installed version:
systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

note : Ubuntu 18.04 include systemd version 237.  Latest version at Nov.2,2018 was 239 at https://github.com/systemd/systemd

CentOS 7 backported  systemd 234:  
reference: https://maciej.lasyk.info/2016/Dec/16/systemd-231-latest-in-centos-7-thx-to-facebook/

wget https://copr.fedorainfracloud.org/coprs/jsynacek/systemd-backports-for-centos-7/repo/epel-7/jsynacek-systemd-backports-for-centos-7-epel-7.repo -O /etc/yum.repos.d/jsynacek-systemd-centos-7.repo
yum update systemd

systemctl --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

journalctl -u traefik
systemd[1]: /etc/systemd/system/traefik.service:11: Failed to parse protect home value, ignoring: tmpfs

Update option value (ProtectHome=read-only) at file traefik.service, configrable-http-proxy.service, jupyterhub.service at /etc/systemd/system  
systemctl daemon-reload
systemctl restart traefik configurable-http-proxy jupyterhub

browser access: http://localhost:80  was okay without any warning,   journalctl -xlf 


Hope to be helpful to others who want to try at CentOS or similar rpm based system.

**Comment by choldgraf** [comment]
thanks @tkang007 for updating the issue with your solution!!!

**Comment by willirath** [comment]
Thanks a lot for this guide!  Especially the backported systemd-version helped a lot in getting this to work on a centos7 box.

Is there any interest in officially supporting CentOS7 @yuvipanda, @choldgraf ? I'd be happy to put together a PR with a yum-submodule, integration tests for centos etc.
