### ISSUE TITLE
Q: Any idea for multiple node deployment?

### ISSUE THREAD

**Issue by tkang007** [jupyterhub/the-littlest-jupyterhub#233]
If we have any options for deploying TLJH on multi nodes, it will be very useful.

Do we have any guide or tips?

**Comment by choldgraf** [comment]
Hey @tkang007 - I'm a bit unclear what exactly you're hoping to do. Could you explain in a bit more detail? TLJH is designed for use with a single-VM deployment, so isn't meant to be split across machines. If you're looking for something more scalable, I think that using kubernetes w/ the [Zero to JupyterHub guide](z2jh.jupyter.org) would be better...

**Comment by tkang007** [comment]
Thanks. When not consider docker and kubernates, tljh could be better approach.

I think that userdb and auto user creation at os level could be issue.

**Comment by tkang007** [comment]
Thanks. When not consider docker and kubernates, tljh could be better approach.

I think that userdb, and auto user creation at os level and some NFS could be issue.
