### ISSUE TITLE
How to set LatexConfig.latex_command?

### ISSUE THREAD

**Issue by annefou** [jupyterhub/the-littlest-jupyterhub#251]
I installed texlive 2018 in /usr/local/texlive/2018/bin and would like "Show Latex Preview" in jupyterlab to run /usr/local/texlive/2018/bin/x86_64-linux/pdflatex but I do not understand where to set:

c.LatexConfig.latex_command = '/usr/local/texlive/2018/bin/x86_64-linux/pdflatex'

It keeps trying to run xelatex and cannot find it. Can you help?

{"message": "Unhandled error", "reason": null, "traceback": "Traceback (most recent call last):\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/web.py\", line 1592, in _execute\n    result = yield result\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 1133, in run\n    value = future.result()\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 1141, in run\n    yielded = self.gen.throw(*exc_info)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/jupyterlab_latex/build.py\", line 194, in get\n    out = yield self.run_latex(cmd_sequence)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 1133, in run\n    value = future.result()\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 1141, in run\n    yielded = self.gen.throw(*exc_info)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/jupyterlab_latex/build.py\", line 158, in run_latex\n    code, output = yield run_command(cmd)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 1133, in run\n    value = future.result()\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n    yielded = next(result)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/jupyterlab_latex/util.py\", line 48, in run_command_async\n    stderr=Subprocess.STREAM)\n  File \"/opt/tljh/user/lib/python3.6/site-packages/tornado/process.py\", line 240, in __init__\n    self.proc = subprocess.Popen(*args, **kwargs)\n  File \"/opt/tljh/user/lib/python3.6/subprocess.py\", line 709, in __init__\n    restore_signals, start_new_session)\n  File \"/opt/tljh/user/lib/python3.6/subprocess.py\", line 1344, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: 'xelatex': 'xelatex'\n"}

**Comment by yuvipanda** [comment]
I'd recommend putting that in `/etc/jupyter/latex_config.py`. You might have to restart your notebook from the control panel afterwards to have it take effect. Try that out and let us know if it works?

**Comment by annefou** [comment]
Ok. I created a new file `/opt/tljh/user/etc/jupyter/latex_config.py` with
c.LatexConfig.latex_command = '/usr/local/texlive/2018/bin/x86_64-linux/pdflatex'

and restarted my notebook from the control panel but I still have the same error.

**Comment by annefou** [comment]
It is not very elegant but I created symbolic link in /opt/tljh/user/bin

cd /opt/tljh/user/bin
for file in /usr/local/texlive/2018/bin/x86_64-linux/* ; do sudo ln -s $file ; done

and now it works...

**Comment by GeorgianaElena** [comment]
Closing this, as the issue seems to be solved. Thanks :sunflower:
