### ISSUE TITLE
Connexion http failed

### ISSUE THREAD

**Issue by BTamby** [jupyterhub/the-littlest-jupyterhub#255]
Hi all,
I installed LTJH on my personal server unbuntu 18.04 without worries, 
but I can not connect to http: // ip_local on jupyterhub. 
When I run jupyterhub with the / opt / tljh / hub / bin ./jupyterhub command, I get the http: // local_ip: 8000 connection on jupyterhub but the admin user is denied for the connection. Can you help me solve this problem? Thank you

**Comment by yuvipanda** [comment]
Apologies for the much delayed response. You shouldn't be running the JupyterHub command manually. Can you explain what you mean by 'but I can not connect to http: // ip_local on jupyterhub.'? Where were you trying to connect from?

**Comment by GeorgianaElena** [comment]
Closing this as the issue is quite old and still needs more user info. Please post on the [Jupyter Discourse forum](https://discourse.jupyter.org/) if there are any other questions. Thanks :sunflower:
