### ISSUE TITLE
Where can I put a startup script in the-littlest-jupyterhub

### ISSUE THREAD

**Issue by DSqiansun** [jupyterhub/the-littlest-jupyterhub#256]
Hello,

I wonld like to know Where can I put a startup script in the-littlest-jupyterhub?
I would like run a python script when i start a python kernel.

Thank you !

**Comment by yuvipanda** [comment]
Heya! I'm going to close this one, but do ask in github.com/ipython/ipython or discourse.jupyter.org if this is something you are still interested in.
