### ISSUE TITLE
Install does NOT create YAML config file

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#26]
The installation instructions (specifically the "Administrative Access" page) states:

> Admin users are specified in the YAML config file at /opt/tljh/config.yaml. This file is created upon installing tljh.

This is not true for me, at least on the installations I have done.  It is easy enough to manually create the file from scratch, but it should be clearly stated.

**Comment by yuvipanda** [comment]
Yep, the administrative access page needs a redo! If you follow one of the tutorials now, it will be created. Can you tell me which tutorial you followed?

**Comment by JuanCab** [comment]
I was following the one at http://the-littlest-jupyterhub.readthedocs.io/en/latest/

**Comment by yuvipanda** [comment]
@JuanCab I removed the direct instructions from there a few days ago for this reason! http://the-littlest-jupyterhub.readthedocs.io/en/latest/tutorials/custom.html is the tutorial for installing on your own server, and that has clearer instructions.

**Comment by yuvipanda** [comment]
Closing this now, since we don't reference a config.yaml file anywhere anymore. #77 adds a `tljh-config` command for configuration needs instead.
