### ISSUE TITLE
Admin can not log in when use GitHub Authenticator

### ISSUE THREAD

**Issue by ypff** [jupyterhub/the-littlest-jupyterhub#270]
Hello 

When I use GitHub account login, I can not log in as an admin. How can I solve this issue?

**Comment by leportella** [comment]
I think this issue is duplicated with the #269 . I encourage you to publish this issue either on [Jupyter Discourse](https://discourse.jupyter.org/) or [the authenticator repository](https://github.com/jupyterhub/oauthenticator/issues)
