### ISSUE TITLE
WebSocket connection failed behind apache proxy subpath

### ISSUE THREAD

**Issue by HoudayerPierre** [jupyterhub/the-littlest-jupyterhub#273]
Hello,

I have some web servers in my local network so to make them accessible outside I used an apache reverse proxy to just expose it on the internet. 

JupyterHub works fine, but when I run a notebook the connexion failed for the WebSocket. I tried a lot of things and configurations and I'm out of ideas.

I'm with the same error like here : https://github.com/jupyterhub/jupyterhub/issues/219#issuecomment-168892029

(My config is like in this issue, so the WebSocket works in my local network)
Thanks

**Comment by nathansegers** [comment]
Have you found a solution yet @HoudayerPierre ?

**Comment by HoudayerPierre** [comment]
Hi, @nathansegers, so no I'have not some new ideas to solve this ...

**Comment by HoudayerPierre** [comment]
I'm using this config in my Apache main web server (as proxy domain.com/jupyterlab) : 
```
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule ^/jupyterlab/(.*) ws://172.16.0.180/jupyterlab/$1 [P,L]
<Location /jupyterlab>
        ProxyPass http://172.16.0.180/jupyterlab
        ProxyPassReverse http://172.16.0.180/jupyterlab
        ProxyPassReverseCookiePath / /jupyterlab/
</Location>
```
