### ISSUE TITLE
Failed to install on 18.04 within LXC container - fix included

### ISSUE THREAD

**Issue by mkempenaar** [jupyterhub/the-littlest-jupyterhub#274]
Hi all,

I had trouble installing `tljh` on a clean Ubuntu 18.04 installation running within an LXC container. I have not yet tested if this error occurs when installing on the host system (Debian, so that results in other 'hackable' problems).

The problem is that the `configurable-http-proxy` is unable to start due to a permission error. The service file created contains the lines:

`[Service]`
` User=nobody`

but the node binary file that this service is trying to execute is owned by the `root` user so this results in the following error that results in the `jupyterhub` service to fail because of failing dependencies:

`configurable-http-proxy.service: Failed to execute command: Permission denied`

To fix this problem, I added a system user called `jupyter`, without a home directory, and granted this user execute rights to all executables in the `node-modules` folder. Then, changing the line in `/etc/systemd/system/configurable-http-proxy.service` to `User=jupyter` fixed the startup issues.

I couldn't find anyone else with this issue so it might be LXC specific. Otherwise it seems to be running fine, so this is still a nice solution compared to the Docker version when requiring < 100 clients. It takes about half an hour to set up an LXC container and this adds a layer of security. 

Thanks again for this great project!

**Comment by yuvipanda** [comment]
Thanks for reporting that here, @mkempenaar! I'm sure it will help someone :)

**Comment by JayBeRayBearGun** [comment]
Hey @mkempenaar I'd like to now your experience with TLJH and LXC. Is it worth investigating to deploy for a small group of say 7 to 10  users?

**Comment by GuanglinDu** [comment]
Since an LXC instance is a system container, which is identical to a complete OS, I thought it would be easy to install TLJH on it. The case is really as I expected on a Ubuntu 20.04 server. LXD and LXC are just a fabulous container implementaiton, unbelievably blazingly fast, extremely resource-saving and schocklingly outstanding. @mkempenaar  @yuvipanda @JayBeRayBearGun
