### ISSUE TITLE
nbgrader : Can't use formgrader for release and collect assignment.

### ISSUE THREAD

**Issue by DSqiansun** [jupyterhub/the-littlest-jupyterhub#280]
Hello,

I followed the tuto https://tljh.jupyter.org/en/latest/install/amazon.html, and installed  the-littlest-jupyterhub in AWS EC2. Then I installed nbgrader in jupyterhub terminal. But the courses can't be released

### Operating system
Ubuntu 18.4
### `nbgrader --version`
nbgrader version 0.5.5
### `jupyterhub --version` (the littlest JupyterHub)
0.9.4
### `jupyter notebook --version`
5.7.0
### Expected behavior

Formgrader should be able to release and collect assignment
### Actual behavior

I already set the course id in nbgrader_config.py but formgrader have an error message "The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions." and it cannot release and collect assignment

![image](https://user-images.githubusercontent.com/22519564/52891739-391f1980-318d-11e9-8e87-948a6a7327b6.png)

![image](https://user-images.githubusercontent.com/22519564/52891750-4d631680-318d-11e9-924e-6d0bf163ad49.png)

**Comment by yuvipanda** [comment]
Heya! Thank you for opening this issue. I'm going to transfer this to github.com/jupyterhub/nbgrader, where others with more nbgrader experience might chime in.

Can you describe in more detail how you set up nbgrader? Did you make it into a JupyterHub service?

**Comment by yuvipanda** [comment]
Apparently transferring issues only works in the same org :( Can you open this issue in https://github.com/jupyter/nbgrader instead? Thanks

**Comment by DSqiansun** [comment]
Hello, i put the issue [here](https://github.com/jupyter/nbgrader/issues/1067#issue-411035866). Thank you for your response.
