### ISSUE TITLE
TLJH not installing on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by cultureclap** [jupyterhub/the-littlest-jupyterhub#281]
Fails to install on an Ubuntu 18.04.1 LTS ?

Seems to be a requirements error in npm?

`
Checking if TLJH is already installed...
TLJH already installed, upgrading...
Upgrading TLJH installer...
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.8
  latest version: 4.6.4

Please update conda by running

    $ conda update -n base conda

Setting up JupyterHub...
Node v10.15.1

> /usr/bin/npm pack @jupyterlab/hub-extension
Node v10.15.1

> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
Incompatible extension:

"@jupyter-widgets/jupyterlab-manager@0.39.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/application
>=0.19.2 <0.20.0        >=1.0.0-alpha.4 <2.0.0@jupyterlab/notebook
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/rendermime

Found compatible version: 0.38.1
> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager@0.38.1
Node v10.15.1

> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
> node /opt/tljh/user/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
Waiting for JupyterHub to come up (1/4 tries)
Waiting for JupyterHub to come up (2/4 tries)
Waiting for JupyterHub to come up (3/4 tries)
Waiting for JupyterHub to come up (4/4 tries)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 448, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 438, in main
    ensure_jupyterhub_running()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 305, in ensure_jupyterhub_running
    raise Exception("Installation failed: JupyterHub did not start in {}s".format(times))
Exception: Installation failed: JupyterHub did not start in 4s
`

**Comment by alexespencer** [comment]
I'm getting the same error:
`> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
Incompatible extension:

"@jupyter-widgets/jupyterlab-manager@0.39.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/application
>=0.19.2 <0.20.0        >=1.0.0-alpha.4 <2.0.0@jupyterlab/notebook
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/rendermime

Found compatible version: 0.38.1`

**Comment by ker2x** [comment]
i have a similar problem, but i didn't update conda, and tljh is working just fine.

**Comment by xmnlab** [comment]
any update about this issue?

**Comment by yuvipanda** [comment]
@xmnlab I just tried it and it works. The difference seems to be that we now try for 20s rather than 4 - mine took 3s to start. Do you still have this problem?

**Comment by mpound** [comment]
I have the same problem as @cultureclap with 20 tries.   I updated conda with
_/opt/tljh/user/bin/conda  update -n base conda_
but it made no difference.   I followed the instructions on http://tljh.jupyter.org/en/latest/contributing/dev-setup.html?highlight=docker

Base OS is RHEL 7.3 & docker CE

Waiting for JupyterHub to come up (20/20 tries)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/src/tljh/installer.py", line 455, in <module>
    main()
  File "/srv/src/tljh/installer.py", line 445, in main
    ensure_jupyterhub_running()
  File "/srv/src/tljh/installer.py", line 313, in ensure_jupyterhub_running
    raise Exception("Installation failed: JupyterHub did not start in {}s".format(times))
Exception: Installation failed: JupyterHub did not start in 20s

**Comment by yuvipanda** [comment]
@mpound thanks for filing the issue! Can you see if you can get logs from JupyterHub (http://tljh.jupyter.org/en/latest/troubleshooting/logs.html)? That should help us see what's up.

**Comment by mpound** [comment]
@yuvipanda thanks for the quick reply!   There seems to be an issue writing to /opt/tljh/state/rules.toml  (owned by root with owner rw access): 

% ls -ls /opt/tljh/state/rules.toml 
0 -rw------- 1 root root 0 Apr 26 13:12 /opt/tljh/state/rules.toml

Attached is a section of the log, which is repeated 6 times during a trial.
[tljh.log](https://github.com/jupyterhub/the-littlest-jupyterhub/files/3121476/tljh.log)

**Comment by yuvipanda** [comment]
@mpound ah, I see it's running inside Docker! TLJH doesn't run *inside* a docker container without a lot of extra hacks. The resource busy error you see is one part of the problem. In general, systemd will also not be available inside a docker container, causing even more issues. I'll open a new issue making this clearer in the docs, and maybe in bootstrap.py too

**Comment by yuvipanda** [comment]
@alexespencer the message you quoted is not actually an error, even though it looks like one. I opened https://github.com/jupyterlab/jupyterlab/issues/5986 to make JupyterLab success messages look less like errors.

**Comment by yuvipanda** [comment]
@mpound I opened #333 to make it clearer that we don't support running inside a container.

I'm going to close this issue now. @xmnlab, @cultureclap @alexespencer if you are still having problems, please comment here - or even better, open a post in discourse.jupyter.org. A lot more people use that, so your chances of getting a quicker response is much higher.

I apologize to everyone here for how late my responses here have been :(
