### ISSUE TITLE
How to add custom settings to jupyter_notebook_config.py?

### ISSUE THREAD

**Issue by Thimm** [jupyterhub/the-littlest-jupyterhub#288]
I would like to add custom settings to every users jupyter_notebook_config.py. Particularly, for the jupyterlab extension  [jupyterlab templates](https://github.com/timkpaine/jupyterlab_templates). However, I am not able to find the configuration file. If I generate the config file it will only get generated for the current user.

**Comment by yuvipanda** [comment]
Heya! You can put the file in any of the paths under 'config' when you run 'jupyter --paths'. For systemwide use, I think /usr/local/etc/jupyter/jupyter_notebook_config.py might be a good place.

**Comment by yuvipanda** [comment]
We should document this, since it's probably a common question. Thank you for asking it!

**Comment by yuvipanda** [comment]
Closing this as a duplicate of #234
