### ISSUE TITLE
Support HTTPS with let's encrypt

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#29]
HTTPS is important, and we should do it right!

We could start by putting https://traefik.io/ in front of CHP for HTTPS termination. Eventually, we could either just use Traefik for the proxy, or add Let's Encrypt functionality to CHP.

**Comment by minrk** [comment]
I'd use certbot for this. It's standalone and available as a package, and has `certbot-autorenew`. Then CHP should just be looking in /etc/letsencrypt/...

**Comment by minrk** [comment]
The only missing feature there is CHP supporting SIGHUP or something to re-load SSL certs. I'll look into that.

Alternately, nginx in front could be responsible for SSL termination, since certbot has support for automatically refreshing nginx, etc.

**Comment by yuvipanda** [comment]
@minrk Traefik has built in support for Let's Encrypt (https://docs.traefik.io/configuration/acme/) so I'd prefer that over nginx. But certbot + CHP also lgtm.

**Comment by yuvipanda** [comment]
@kastork yeah, that should work too! However, we want to keep this as simple as possible and accessible to the most number of people - so we'll probably just implement traefik based Let's encrypt ourselves rather than ask users to learn to use a Load Balancer.

**Comment by yuvipanda** [comment]
Done with https://github.com/jupyterhub/the-littlest-jupyterhub/pull/67 <3 @minrk
