### ISSUE TITLE
Little Documentation error

### ISSUE THREAD

**Issue by helge42** [jupyterhub/the-littlest-jupyterhub#291]
In chapter "Configuring JupyterHub authenticators" (https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/docs/topic/authenticator-configuration.rst) is a misplaced equal sign:

sudo tljh-config set auth.LDAPAuthenticator.server_address = 'my-ldap-server'

must be

sudo tljh-config set auth.LDAPAuthenticator.server_address  'my-ldap-server'

BTW, thanks for your great work 

Edit: another one:
In https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/docs/howto/content/share-data.rst
the line
sudo ln -s /src/data/my_shared_data_folder my_shared_data_folder
must be
sudo ln -s /srv/data/my_shared_data_folder my_shared_data_folder

**Comment by leportella** [comment]
Hi @helge42 ! Would you be insterested in submitting a pull request with these fixes?

**Comment by yuvipanda** [comment]
Thanks for opening this issue, @helge42. I've opened #331 to fix the first issue. I can't see what the second suggestion is - both those lines look the same to me. Could you clarify?

**Comment by shareandenjoy** [comment]
src and srv in the path

**Comment by yuvipanda** [comment]
Ah, totally missed that. Thank you, @shareandenjoy. I've added it to #331

**Comment by yuvipanda** [comment]
I think all these are fixed. Please re-open if not.

Thanks for reporting this, @shareandenjoy
