### ISSUE TITLE
Safe to ugrade to newer jupyterlab version?

### ISSUE THREAD

**Issue by joshy** [jupyterhub/the-littlest-jupyterhub#293]
Maybe it is a stupid question, but is it safe to upgrade jupyterlab version? I want to run 
`sudo -E conda install -c conda-forge jupyterlab`

Thanks!

**Comment by yuvipanda** [comment]
@joshy it should be ok! It's installed with pip, so you might wanna use pip install -U jupyterlab instead.

**Comment by joshy** [comment]
@yuvipanda Cool, thanks for the answer. Will try out and report the result here and after that close the issue. Thanks!

**Comment by joshy** [comment]
Upgrade went flawless from jupyter lab version 0.32.1 to 0.35.4. The running servers needs to be restarted otherwise users will see a empty notebook.
