### ISSUE TITLE
Can't get to first time log in

### ISSUE THREAD

**Issue by chesterlbtan** [jupyterhub/the-littlest-jupyterhub#298]
I'm manage to install the-littlest-jupyterhub in my Linux Mint 19 desktop, after a minor tinkering with the installer.py and some manual installation of few packages.

Then I'm also able to open the jupyter website from a client PC, which contains the Sign In page.
However, I cannot login using the admin account or any other account.

I followed this [tutorial](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/custom-server.html) but stuck at step 1.6
I only get Invalid username or password

I'm new to this, so I'm don't know where to look at next.

**Comment by chesterlbtan** [comment]
Fixed already after manually adding a username to config.yaml

**Comment by nuistzhou** [comment]
> Fixed already after manually adding a username to config.yaml

Hi, where is the config.yaml? I cannot find it. Thank you!

**Comment by chesterlbtan** [comment]
> 
> 
> > Fixed already after manually adding a username to config.yaml
> 
> Hi, where is the config.yaml? I cannot find it. Thank you!

I found mine in /opt/tljh/config/config.yaml
I open it by text editor.
`sudo xed /opt/tljh/config/config.yaml`
