### ISSUE TITLE
JSON file in JupyterLab not working

### ISSUE THREAD

**Issue by jaewl** [jupyterhub/the-littlest-jupyterhub#300]
When I try to open json files from JupyterLab UI, all of them fail to open with the yellow spinner circling infinitely.

I checked at https://jsonlint.com/ that those all are valid json files.

I also get JSONDecodeError: Expecting value: line 7 column 1 (char 6) when I try to load it with json.load command.

Any idea how to resolve this issue? Looks like the problem is not the files but something within JupyterLab configuration.

**Comment by yuvipanda** [comment]
Heya! 

Unfortunately, this question is probably best answered by the JupyterLab folks. Can you make a post in discourse.jupyter.org, or open an issue in https://github.com/jupyterlab/jupyterlab? That's likely to get attention of people with more knowledge of JupyterLab issues.

Thank you!
