### ISSUE TITLE
Cells won't run, which ports should i leave open?

### ISSUE THREAD

**Issue by chamatt** [jupyterhub/the-littlest-jupyterhub#301]
I am part of a volunteer project to teach programming to high school kids. Our team has decided to use Jupyter Notebooks in class. Since we do our classes on university campus, we are allowed to use our university server to host it. We asked for a server, and got it, installed TLJH, and all was working perfectly, on the internal network.

But since we want the kids to use the platform at home, we needed to make it open to external access. For this purpose, i had to tell the IT Manager to open some external ports, i figured i only needed port 80 for web access. But since it was opened to external access, the notebook cells won't run anymore, it just shows a [*] next to it.

What should i do? Do i need to open any specific port? Or is there some other problem?

**Comment by frier-sam** [comment]
jupyter notebook used websocket to keep the connection open, if you are opening to internet then there might be some proxy inbetween, this should be configure to route the socket too,

**Comment by yuvipanda** [comment]
Thank you for opening the issue, @chamatt. Sorry for the delayed response. 

You need port 80, and possibly port 443 (if you have HTTPS, which I highly recommend). @frier-sam is right - this sounds like the method being used to open the ports externally is blocking websocket requests. Talking to the network folks to see if that's the case would help clarify things.

I hope you had some success and were able to use this for your class!

**Comment by chamatt** [comment]
frier-sam had it right. The problem was that the reverse-proxy was blocking web-sockets. I sent the tutorial available on TLJH website about this to the guys on IT and they were able to solve it. Thank you.

**Comment by yuvipanda** [comment]
Awesome, @chamatt! Glad to hear it worked for you :) 

Thanks for solving this, @frier-sam
