### ISSUE TITLE
installation failure on personal server -  ubuntu 18.04

### ISSUE THREAD

**Issue by frier-sam** [jupyterhub/the-littlest-jupyterhub#302]
installation fails with following error

```
`Checking

 if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Setup tljh package
Starting TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Downloading & setting up user environment...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 455, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 438, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/installer.py", line 257, in ensure_user_environment
    'tornado<6.0'
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/conda.py", line 133, in ensure_pip_packages
    ] + packages, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/user/bin/python', '-m', 'pip', 'install', '--no-cache-dir', 'jupyterhub==0.9.5', 'notebook==5.7.7', 'jupyterlab==0.35.4', 'nteract-on-jupyter==2.0.7', 'nbgitpuller==0.6.1', 'nbresuse==0.3.0', 'ipywidgets==7.4.2', 'tornado<6.0']' returned non-zero exit status 1.`
```

i am installing on ubuntu 18.04 server on ec2 instance

**Comment by frier-sam** [comment]
ok, i am able to find the culprit, notebook==5.7.7 is removed from pip due to some security issue, change it to 5.7.8 and it's working fine

**Comment by frier-sam** [comment]
if someone wants to install it, you can fork the repo and change the notebook version in installer.y and change the git repo in bootstrap.py , or you can use my repo until this is fixed as follows

curl https://raw.githubusercontent.com/frier-sam/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin sam

**Comment by fermasia** [comment]
It took me hours to figure it out.... but yes it works correcting notebook's package version. Is there a reason not to leave package versions undefinedad, or at least ask for a version or previous one?

**Comment by frier-sam** [comment]
if a package is updated, there will be change in how it works, functions may change, so if you create a repo using one version package then there is no guarantee that it gonna work with next or previous versions of same package. That's the reason package version will be fixed
Removing old packages from pypi(pip) repository is rare when compared to volumes. this can be considered as exception 
Regarding updates, i don't know about it. If someone has any idea how we can change our master repo in server please guide us

**Comment by willirath** [comment]
Fixed with #303.

**Comment by fermasia** [comment]
> if a package is updated, there will be a change in how it works, functions may change, so if you create a repo using one version of package then there is no guarantee that it's gonna work with next or previous versions of same package. That's the reason package versions will be fixed during installation.
> Removing old packages from pypi(pip) repository is rare when compared to volumes. this can be considered as exception
> Regarding updates, i don't know about it. If someone has any idea how we can change our master repo in server please guide us

I understand what a package's version change could brake, but asking for a version or anything previous (such as how tornado is defined in the script with the < operator) could prevent this kind of problems, provided you can ensure backwards compatibility. Even if that arises any problems, it seems like a better solution (to me) than pointing to an specific version number and if that's missing braking the installation script with no explicit error message.

Just trying to help, maybe I'm missing something thought.

**Comment by willirath** [comment]
Removing a version from a package repository as obviously happened with the notebook package is a very rare event. Usually, pinning everything is the way to go if you want stability and reliability. We should continue to do so here.
