### ISSUE TITLE
Document renewal process for HTTPS certificates

### ISSUE THREAD

**Issue by hoeller** [jupyterhub/the-littlest-jupyterhub#305]
How do the certificates for HTTPS get renewed?

**Comment by yuvipanda** [comment]
Heya! We use Traefik's let's encrypt support (documented in https://docs.traefik.io/configuration/acme/). It automatically renews it when the time comes.

**Comment by hoeller** [comment]
Hi! In my case, the certificate expired and nothing happened. I cannot say for sure but it is possible that there was a closed firewall at this moment. Tried restarting the hub with open firewall but that did not help. Eventually got myself a cert via Certbot and switched to the manual settings... Since I did not know that the renewal should be done by Traefik, I did not look further into this problem.

**Comment by yuvipanda** [comment]
That makes sense, @hoeller. I amended #328 to include a small troubleshooting section, and some info on how to get traefik logs. Hope that would have helped!
