### ISSUE TITLE
First paragraph of README.rst is repeated

### ISSUE THREAD

**Issue by nscozzaro** [jupyterhub/the-littlest-jupyterhub#307]
"All users get the same environment, and administrators can install libraries into this environment without any specialized knowledge. It provides all users with the same environment, and administrators can install libraries into this environment easily without any specialized knowledge."

![image](https://user-images.githubusercontent.com/15185105/56400089-e363fd80-621f-11e9-98fb-51119e9605dd.png)

**Comment by yuvipanda** [comment]
Thank you for reporting this. It's been fixed now :)
