### ISSUE TITLE
How to deal with port collision

### ISSUE THREAD

**Issue by lvertighel** [jupyterhub/the-littlest-jupyterhub#315]
I tried to set up The Littlest Jupyterhub on a machine on which the standard HTTP(S) ports are already in use by other applications. I am not able to access the Jupyterhub web interface, and I can find no indication how to change the port on which Jupyterhub listens. How should one proceed in this case? Thanks.

**Comment by yuvipanda** [comment]
You can set http port with the `http.port` setting and https port with `https.port` setting from tljh-config. However, I'll note that TLJH does a lot of other things to the system (with user accounts and sudo rules primarily) that might break security assumptions your other applications have, so use with extreme caution.

**Comment by gabefair** [comment]
Thank you for asking this and the response is great. Maybe this could be added to the documentation? I don't know if it would be appropriate to add.

**Comment by EvilMav** [comment]
```
~# tljh-config show
users:
  admin:
  - xxxx
http:
  port: 8080
limits:
  memory: 32G
```
Jupyterhub is still served under port 80 even after rebooting the server :-/

**Comment by GeorgianaElena** [comment]
Fixed by https://github.com/jupyterhub/the-littlest-jupyterhub/pull/362
