### ISSUE TITLE
Add documentation on how to use this with GPUs

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#318]
Since TLJH doesn't use containers, using this with GPUs should be easy. We should add documentation on how to do it. If necessary, we can make changes here - or create a [tljh plugin](http://tljh.jupyter.org/en/latest/contributing/plugins.html)

**Comment by mrocklin** [comment]
Does one need to do anything?  The nice thing about TLJH is that it's just a normal system.

I guess some people might want to be given a GPU that no one else is using?  If so, the standard practice seems to be to specify the `CUDA_VISIBLE_DEVICES` environment variable to restrict and order the priority that any particular process uses to choose GPUs.  

If I have four GPU devices on my machine then default is

```
CUDA_VISIBLE_DEVICES=0,1,2,3
```

Which says "use gpu 0.  If you need another then use gpu 1 and so on".  

So maybe we round robin these, or limit people after all GPUs are taken?

**Comment by yuvipanda** [comment]
Dupe of #197 

@mrocklin mostly along the lines of #197. I think a page where we link people to installation instructions would be good enough.
