### ISSUE TITLE
'405 method not allowed' with tljh on vm

### ISSUE THREAD

**Issue by lux12337** [jupyterhub/the-littlest-jupyterhub#323]
Hi, I had the pleasure to meet @yuvipanda a couple of weeks ago and he was able to help me setup tljh on a vm. However, as I tried to reinstall tljh from scratch, i run into problems similar to what i had but i don't remember what yuvi did to debug them. I have installed tljh on vm with a clean install of Ubuntu 18.04. After the installation, when I try to run the command `curl -I http://localhost` i get this: 
<img width="629" alt="Screen Shot 2019-05-12 at 11 44 09 PM" src="https://user-images.githubusercontent.com/19236515/57601400-43914b00-7511-11e9-838f-362d4577a9c7.png">

I remember that traefik might have been the problem but i'm not sure, these are the logs i get. Thanks for the help in advance!

> May 12 23:44:24 ubuntu sudo[1126]: pam_unix(sudo:session): session opened for user root by luigi(uid=0)
May 12 23:44:24 ubuntu sudo[1126]:    luigi : TTY=pts/0 ; PWD=/home/luigi ; USER=root ; COMMAND=/bin/journalctl -r
May 12 23:43:56 ubuntu python3[720]: [W 2019-05-12 23:43:56.960 JupyterHub log:158] 405 HEAD /hub (@::1) 1.19ms
May 12 23:43:53 ubuntu python3[720]: [W 2019-05-12 23:43:53.785 JupyterHub log:158] 405 HEAD / (@::1) 1.98ms
May 12 23:43:44 ubuntu python3[720]: [W 2019-05-12 23:43:44.589 JupyterHub log:158] 405 HEAD / (@::1) 46.95ms
May 12 23:43:39 ubuntu systemd-timesyncd[479]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
May 12 23:43:36 ubuntu systemd-logind[708]: New session 3 of user luigi.
May 12 23:43:36 ubuntu systemd[1]: Started Session 3 of user luigi.
May 12 23:43:36 ubuntu sshd[1032]: pam_unix(sshd:session): session opened for user luigi by (uid=0)
May 12 23:43:36 ubuntu sshd[1032]: Accepted password for luigi from 10.0.2.2 port 52123 ssh2
May 12 23:43:19 ubuntu systemd[999]: Startup finished in 95ms.
-- Logs begin at Fri 2019-03-22 15:38:40 PDT, end at Sun 2019-05-12 23:44:24 PDT. --
May 12 23:44:24 ubuntu sudo[1126]: pam_unix(sudo:session): session opened for user root by luigi(uid=0)
May 12 23:44:24 ubuntu sudo[1126]:    luigi : TTY=pts/0 ; PWD=/home/luigi ; USER=root ; COMMAND=/bin/journalctl -r
-- Logs begin at Fri 2019-03-22 15:38:40 PDT, end at Sun 2019-05-12 23:44:24 PDT. --
May 12 23:44:24 ubuntu sudo[1126]: pam_unix(sudo:session): session opened for user root by luigi(uid=0)
-- Logs begin at Fri 2019-03-22 15:38:40 PDT, end at Sun 2019-05-12 23:44:24 PDT. --
May 12 23:44:24 ubuntu sudo[1126]: pam_unix(sudo:session): session opened for user root by luigi(uid=0)
May 12 23:44:24 ubuntu sudo[1126]:    luigi : TTY=pts/0 ; PWD=/home/luigi ; USER=root ; COMMAND=/bin/journalctl -r
May 12 23:43:56 ubuntu python3[720]: [W 2019-05-12 23:43:56.960 JupyterHub log:158] 405 HEAD /hub (@::1) 1.19ms
May 12 23:43:53 ubuntu python3[720]: [W 2019-05-12 23:43:53.785 JupyterHub log:158] 405 HEAD / (@::1) 1.98ms
May 12 23:43:44 ubuntu python3[720]: [W 2019-05-12 23:43:44.589 JupyterHub log:158] 405 HEAD / (@::1) 46.95ms
May 12 23:43:39 ubuntu systemd-timesyncd[479]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
May 12 23:43:36 ubuntu systemd-logind[708]: New session 3 of user luigi.
May 12 23:43:36 ubuntu systemd[1]: Started Session 3 of user luigi.
May 12 23:43:36 ubuntu sshd[1032]: pam_unix(sshd:session): session opened for user luigi by (uid=0)
May 12 23:43:36 ubuntu sshd[1032]: Accepted password for luigi from 10.0.2.2 port 52123 ssh2
May 12 23:43:19 ubuntu systemd[999]: Startup finished in 95ms.
May 12 23:43:19 ubuntu systemd[999]: Reached target Default.
May 12 23:43:19 ubuntu systemd[1]: Started User Manager for UID 1000.
May 12 23:43:19 ubuntu systemd[999]: Reached target Basic System.
May 12 23:43:19 ubuntu systemd[999]: Reached target Paths.
May 12 23:43:19 ubuntu systemd[999]: Reached target Sockets.
May 12 23:43:19 ubuntu systemd[999]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
May 12 23:43:19 ubuntu systemd[999]: Listening on GnuPG cryptographic agent and passphrase cache.
May 12 23:43:19 ubuntu systemd[999]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
May 12 23:43:19 ubuntu systemd[999]: Reached target Timers.
May 12 23:43:19 ubuntu systemd[999]: Listening on GnuPG network certificate management daemon.
May 12 23:43:19 ubuntu systemd[999]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
May 12 23:43:19 ubuntu systemd[999]: Failed to open directory /home/luigi/.config/systemd/user, ignoring: Permission denied
May 12 23:43:19 ubuntu systemd-logind[708]: New session 1 of user luigi.
May 12 23:43:19 ubuntu systemd[1]: Started Session 1 of user luigi.
May 12 23:43:18 ubuntu systemd[999]: pam_unix(systemd-user:session): session opened for user luigi by (uid=0)
May 12 23:43:18 ubuntu systemd[1]: Starting User Manager for UID 1000...
May 12 23:43:18 ubuntu systemd[1]: Created slice User Slice of luigi.
May 12 23:43:18 ubuntu login[834]: pam_unix(login:session): session opened for user luigi by LOGIN(uid=0)
May 12 23:43:14 ubuntu snapd[735]: daemon stop requested to wait for socket activation
May 12 23:43:14 ubuntu snapd[735]: daemon.go:613: done waiting for running hooks
May 12 23:43:14 ubuntu snapd[735]: daemon.go:611: gracefully waiting for running hooks
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.154 JupyterHub app:1912] JupyterHub is now running at http://:8000
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.154 JupyterHub proxy:301] Checking routes
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.153 JupyterHub app:1870] Not starting proxy
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.153 JupyterHub app:1855] Hub API listening on http://127.0.0.1:15001/hub/
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.135 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.056 JupyterHub app:1016] Loading cookie_secret from /opt/tljh/state/jupyterhub_cookie_secret
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.053 JupyterHub app:1673] Using Spawner: builtins.UserCreatingSpawner
May 12 23:43:12 ubuntu python3[720]: [I 2019-05-12 23:43:12.053 JupyterHub app:1673] Using Authenticator: firstuseauthenticator.firstuseauthenticator.FirstUseAuthenticator
May 12 23:43:10 ubuntu systemd[1]: Startup finished in 3.812s (kernel) + 3.172s (userspace) = 6.984s.
May 12 23:43:10 ubuntu systemd[1]: Started Update UTMP about System Runlevel Changes.
May 12 23:43:10 ubuntu systemd[1]: Starting Update UTMP about System Runlevel Changes...
May 12 23:43:10 ubuntu systemd[1]: Reached target Graphical Interface.
May 12 23:43:10 ubuntu systemd[1]: Reached target Multi-User System.
May 12 23:43:10 ubuntu systemd[1]: Started Dispatcher daemon for systemd-networkd.
May 12 23:43:10 ubuntu networkd-dispatcher[718]: No valid path found for iwconfig
May 12 23:43:10 ubuntu systemd[1]: Started LSB: automatic crash report generation.
May 12 23:43:10 ubuntu apport[817]:    ...done.
May 12 23:43:10 ubuntu systemd[1]: Started OpenBSD Secure Shell server.
May 12 23:43:10 ubuntu sshd[838]: Server listening on :: port 22.
May 12 23:43:10 ubuntu sshd[838]: Server listening on 0.0.0.0 port 22.
May 12 23:43:10 ubuntu apport[817]:  * Starting automatic crash report generation: apport
May 12 23:43:10 ubuntu systemd[1]: Reached target Login Prompts.
May 12 23:43:10 ubuntu systemd[1]: Started Getty on tty1.
May 12 23:43:10 ubuntu systemd[1]: Created slice system-getty.slice.
May 12 23:43:10 ubuntu systemd[1]: Started Set console scheme.
May 12 23:43:10 ubuntu systemd[1]: Started Terminate Plymouth Boot Screen.
May 12 23:43:10 ubuntu systemd[1]: Starting Set console scheme...
May 12 23:43:10 ubuntu systemd[1]: Started Hold until boot process finishes up.
May 12 23:43:10 ubuntu systemd[1]: Starting Hold until boot process finishes up...
May 12 23:43:10 ubuntu systemd[1]: Starting Terminate Plymouth Boot Screen...
May 12 23:43:10 ubuntu systemd[1]: Started Permit User Sessions.
May 12 23:43:10 ubuntu systemd[1]: Started Availability of block devices.
May 12 23:43:10 ubuntu systemd[1]: Starting Availability of block devices...
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Server configuration reloaded on :80"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Server configuration reloaded on 127.0.0.1:8099"
May 12 23:43:10 ubuntu systemd[1]: Starting Permit User Sessions...
May 12 23:43:10 ubuntu systemd[1]: Starting LSB: automatic crash report generation...
May 12 23:43:10 ubuntu systemd[1]: Reached target Remote File Systems.
May 12 23:43:10 ubuntu systemd[1]: Reached target Remote File Systems (Pre).
May 12 23:43:10 ubuntu systemd[1]: Starting OpenBSD Secure Shell server...
May 12 23:43:10 ubuntu systemd[1]: Reached target Network is Online.
May 12 23:43:10 ubuntu systemd[1]: Started Wait for Network to be Configured.
May 12 23:43:10 ubuntu systemd-networkd-wait-online[517]: ignoring: lo
May 12 23:43:10 ubuntu systemd-networkd-wait-online[517]: managing: enp0s3
May 12 23:43:10 ubuntu systemd-timesyncd[479]: Network configuration changed, trying to establish connection.
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Configured
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Gained IPv6LL
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"rules.toml\",\"Constraints\":null,\"Trace\":false,\"Te
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on :80"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on 127.0.0.1:8099"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider configuration.ProviderAggregator {}"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compre
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server auth_api &{Address:127.0.0.1:8099 TLS:<nil> Redirect:<nil> Auth:0xc00037fe00 WhitelistSourceRange:[] 
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.
May 12 23:43:10 ubuntu systemd[1]: Started LXD - container startup/shutdown.
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Traefik version v1.7.5 built on 2018-12-03_11:01:00AM"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Using TOML configuration file /opt/tljh/state/traefik.toml"
May 12 23:43:09 ubuntu systemd[1]: Started Accounts Service.
May 12 23:43:09 ubuntu accounts-daemon[711]: started daemon version 0.6.45
May 12 23:43:10 ubuntu systemd-timesyncd[479]: Network configuration changed, trying to establish connection.
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Configured
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Gained IPv6LL
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"rules.toml\",\"Constraints\":null,\"Trace\":false,\"Te
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on :80"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on 127.0.0.1:8099"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider configuration.ProviderAggregator {}"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compre
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server auth_api &{Address:127.0.0.1:8099 TLS:<nil> Redirect:<nil> Auth:0xc00037fe00 WhitelistSourceRange:[] 
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.
May 12 23:43:10 ubuntu systemd[1]: Started LXD - container startup/shutdown.
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Traefik version v1.7.5 built on 2018-12-03_11:01:00AM"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Using TOML configuration file /opt/tljh/state/traefik.toml"
May 12 23:43:09 ubuntu systemd[1]: Started Accounts Service.
May 12 23:43:09 ubuntu accounts-daemon[711]: started daemon version 0.6.45
May 12 23:43:09 ubuntu systemd[1]: Started Authorization Manager.
May 12 23:43:09 ubuntu dbus-daemon[736]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
May 12 23:43:09 ubuntu polkitd[765]: started daemon version 0.105 using authority implementation `local' version `0.105'
May 12 23:43:09 ubuntu systemd[1]: Started LSB: Record successful boot for GRUB.
May 12 23:43:09 ubuntu grub-common[716]:    ...done.
May 12 23:43:09 ubuntu systemd[1]: Started Wait until snapd is fully seeded.
May 12 23:43:09 ubuntu systemd[1]: Starting Wait until snapd is fully seeded...
May 12 23:43:09 ubuntu systemd[1]: Started Snappy daemon.
May 12 23:43:09 ubuntu systemd[1]: Starting Authorization Manager...
May 12 23:43:09 ubuntu dbus-daemon[736]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service' requested by ':1.4' (uid=0 pid=711 comm="/usr/lib/accountsservice/
May 12 23:43:09 ubuntu snapd[735]: daemon.go:379: started snapd/2.38+18.04 (series 16; classic) ubuntu/18.04 (amd64) linux/4.15.0-48-generic.
May 12 23:43:09 ubuntu grub-common[716]:  * Recording successful boot for GRUB
May 12 23:43:09 ubuntu systemd[1]: Reached target Sound Card.
May 12 23:43:09 ubuntu systemd[1]: Started Unattended Upgrades Shutdown.
May 12 23:43:09 ubuntu systemd[1]: Started Login Service.
May 12 23:43:09 ubuntu /usr/sbin/irqbalance[754]: Balancing is ineffective on systems with a single cpu.  Shutting down
May 12 23:43:09 ubuntu systemd[1]: Started System Logging Service.
May 12 23:43:09 ubuntu systemd[1]: Starting LXD - container startup/shutdown...
May 12 23:43:09 ubuntu systemd[1]: Started irqbalance daemon.
May 12 23:43:09 ubuntu dbus-daemon[736]: [system] AppArmor D-Bus mediation is enabled
May 12 23:43:09 ubuntu snapd[735]: AppArmor status: apparmor is enabled and all features are available
May 12 23:43:09 ubuntu cron[715]: (CRON) INFO (Running @reboot jobs)
May 12 23:43:09 ubuntu systemd-logind[708]: Watching system buttons on /dev/input/event2 (AT Translated Set 2 keyboard)
May 12 23:43:09 ubuntu systemd-logind[708]: Watching system buttons on /dev/input/event1 (Sleep Button)
May 12 23:43:09 ubuntu lxcfs[717]:  12: fd:  18: unified
May 12 23:43:09 ubuntu lxcfs[717]:  11: fd:  17: name=systemd
May 12 23:43:09 ubuntu lxcfs[717]:  10: fd:  16: memory
May 12 23:43:09 ubuntu lxcfs[717]:   9: fd:  15: cpuset
May 12 23:43:09 ubuntu lxcfs[717]:   8: fd:  14: devices
May 12 23:43:09 ubuntu lxcfs[717]:   7: fd:  13: net_cls,net_prio
May 12 23:43:09 ubuntu lxcfs[717]:   6: fd:  12: rdma
May 12 23:43:09 ubuntu lxcfs[717]:   5: fd:  11: freezer
May 12 23:43:09 ubuntu lxcfs[717]:   4: fd:  10: hugetlb
May 12 23:43:09 ubuntu lxcfs[717]:   3: fd:   9: pids
May 12 23:43:09 ubuntu lxcfs[717]:   2: fd:   8: blkio
May 12 23:43:09 ubuntu lxcfs[717]:   1: fd:   7: perf_event
May 12 23:43:09 ubuntu lxcfs[717]:   0: fd:   6: cpu,cpuacct
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Server configuration reloaded on :80"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Server configuration reloaded on 127.0.0.1:8099"
May 12 23:43:10 ubuntu systemd[1]: Starting Permit User Sessions...
May 12 23:43:10 ubuntu systemd[1]: Starting LSB: automatic crash report generation...
May 12 23:43:10 ubuntu systemd[1]: Reached target Remote File Systems.
May 12 23:43:10 ubuntu systemd[1]: Reached target Remote File Systems (Pre).
May 12 23:43:10 ubuntu systemd[1]: Starting OpenBSD Secure Shell server...
May 12 23:43:10 ubuntu systemd[1]: Reached target Network is Online.
May 12 23:43:10 ubuntu systemd[1]: Started Wait for Network to be Configured.
May 12 23:43:10 ubuntu systemd-networkd-wait-online[517]: ignoring: lo
May 12 23:43:10 ubuntu systemd-networkd-wait-online[517]: managing: enp0s3
May 12 23:43:10 ubuntu systemd-timesyncd[479]: Network configuration changed, trying to establish connection.
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Configured
May 12 23:43:10 ubuntu systemd-networkd[485]: enp0s3: Gained IPv6LL
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider *file.Provider {\"Watch\":true,\"Filename\":\"rules.toml\",\"Constraints\":null,\"Trace\":false,\"Te
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on :80"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting server on 127.0.0.1:8099"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Starting provider configuration.ProviderAggregator {}"
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compre
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="Preparing server auth_api &{Address:127.0.0.1:8099 TLS:<nil> Redirect:<nil> Auth:0xc00037fe00 WhitelistSourceRange:[] 
May 12 23:43:10 ubuntu traefik[719]: time="2019-05-12T23:43:10-07:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.

**Comment by yuvipanda** [comment]
@lux12337 nice to meet you here :) 

`curl -I` sends a `HEAD` request, which isn't allowed by the hub in many places. If you leave the `-I` out it should work. You should add `-L` so it follows redirects. So try `curl -L http://localhost` instead. Browsers should be able to do this automatically...

**Comment by GeorgianaElena** [comment]
Closing this, as the issue seems to be solved. For any questions, please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks :sunflower:
