### ISSUE TITLE
Make it clearer we don't support running TLJH *inside* a docker container

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#333]
TLJH depends on Systemd, and hence can't run inside a Docker container without a bunch of extra hacks. It'll fail in mysterious ways if you try. We should make it clearer in the docs, and maybe add a flag to bootstrap.py as well.

**Comment by GeorgianaElena** [comment]
Fixed by https://github.com/jupyterhub/the-littlest-jupyterhub/pull/327
