### ISSUE TITLE
Copy files after user was created

### ISSUE THREAD

**Issue by D4rkM4atter** [jupyterhub/the-littlest-jupyterhub#341]
Hi,
I have activated the FirstUseAuthenticator which works fine. But i want that some notebooks will copied automatically after a new user was created.
Any solutions for this?

**Comment by yuvipanda** [comment]
Heya! thank you for opening this. We're trying to move user support questions like this to discourse.jupyter.org, where a wider audience will be able to look at this. Can you create a post there? Thank you!
