### ISSUE TITLE
Support way to generate and pre-assign random passwords to users

### ISSUE THREAD

**Issue by azaryc2s** [jupyterhub/the-littlest-jupyterhub#344]
Hi!
So i'm trying to use your script to setup a system, where i can create **n** accounts with random passwords that i can then distribute to the students. This could be easily done by a script that creates unix accounts on the machine with random passwords and drops the data into a file, which i can then - let's say print out. This seems impossible though, because the PAMAuthenticator (which is basically the standard one for a "normal" Jupyterhub-installation) is not supported. Is there any reason to why it's not supported or is it just "not implemented yet"?

Ps. Please keep in mind, that setting random passwords for each user myself (and by that i mean somehow automatically) is a mandatory requirement -> i cannot let the students set their passwords by themselves or use any existing accounts (ldap, openid etc.).

**Comment by yuvipanda** [comment]
Thanks for opening this issue, @azaryc2s. 

Unfortunately, PAM Authenticator is unlikely to be supported, since we do a bunch of things around creating and managing user accounts ourselves. If you'd like to use PAMAuthenticator right now, I'd recommend setting up a JupyterHub without using TLJH.

However, if the idea is to generate and set random passwords for users, there's a few ways you can accomplish that:

1. Use FirstUseAuthenticator, login yourself with the student username + generated password for each student.
2. Add a feature / script to FirstUseAuthenticator that lets you set passwords / usernames from the commandline. It uses bcrypt and gdb (see https://github.com/jupyterhub/firstuseauthenticator/blob/db02d3e5813755eb506ef7a069c7370ee3015c3c/firstuseauthenticator/firstuseauthenticator.py#L117) so should hopefully not be super difficult.

I think (2) would be most welcome if you have the time, since I believe this is a common use case.

**Comment by azaryc2s** [comment]
Thanks for the quick reply!

As silly as it sounds i'm not really fond of python and implementing this would take me much longer than probably needed ^^ Also i'm not really sure where to start (the code of the authenticator doesn't look like a CLI and i wouldn't know where and how to integrate this exactly. But i'll ask around - there are more people interested in this project here :)

About PAM - so simply checking if the username matches "jupyterhub-*" and the password is correct is out of the picture? This would practically disable the user management on the Web-UI, but you wouldn't need it and could still use it as an overview. And if you need additional functionalities, you could still manage a DB with all the data needed, but simply delegate the authentication to the underlying system.
But if you're absolutely sure this is not possible/would be a huge pain, then i'll deal with it :)

For now i'll probably make the effort and create the users myself or write a script that simply follows the login-API for the first-time login.

**Comment by yuvipanda** [comment]
Glad to hear that you have found a working solution!

We try to keep TLJH compact and easy to maintain - unfortunately this means not supporting some use cases. We let users write their own config - see https://tljh.jupyter.org/en/latest/topic/escape-hatch.html. You might be able to turn on PAM authenticator here, although it might break other assumptions throughout the system. I think your current workaround is probably less likely to break.

If you end up writing a script, please do post it here for the benefit of the next person trying to do the same thing.

**Comment by azaryc2s** [comment]
Will do, thanks for the support!

**Comment by yuvipanda** [comment]
Yw! I'll close this issue now, but do still post the script!

**Comment by azaryc2s** [comment]
Okay, so the script i wrote is fairly simple. You need to have installed:
`openssl`, `tr`, `cut` and `curl`
then just put this code in a file:
`#!/bin/bash
#The file to read the usernames from - separated by lines
FILE=$1
#The url of the server - containing the protocol, ip/dn and optionally the port number if custom
#https://example.com | http://192.168.0.105:8888
URL=$2
while read p; do
  PW=$(openssl rand -base64 29 | tr -d "=+/" | cut -c1-8)
  curl -d "username=$p&password=$PW" -X POST $URL/hub/login
  echo "$p,$PW"
done < $FILE`

let's say we name it "tljh_rng_users.sh" , on any machine that can connect to the TLJH-Installation. We create our file "students.txt", which contains only the usernames separated by lines and place it somewhere (let's say the same directory as the script). And our server is accessible at "https://tljh-example.com". We login as admins there and add all the users we have stored in our file, by just copying the whole file content and putting it into the "add user" form (just copy paste since we use the same format) and add them all.
Now we can just call the script "./tljh_rng_users.sh students.txt https://tljh-example.com > students_output.txt" and wait for it to end (this can take few seconds depending on how many users we need to add).
And voilà - all the users have random generated passwords, which we stored in a file that we can now process as we need.
I hope this helps some1 :)
