### ISSUE TITLE
How to reuse an existing Anaconda environment?

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/the-littlest-jupyterhub#348]
Hi.

I was (painfully) installing jupyterhub manually on a standalone server for some data science team when I came accross this project...

The installation went right away, so first congratulation !

Just wondering, if I have an existing Anaconda (full) environment already set up on my machine, with shared environment I was preparing for my users, can I reuse it or I'll have to refresh the environments (no big deal) with minicona?

**Comment by yuvipanda** [comment]
Heya!

Unfortunately this is not a use case TLJH supports. We generally assume you are starting from scratch. This let's us keep the TLJH codebase small, stable not and well rested.

Hope TLJH works out for you!

**Comment by gsemet** [comment]
As long as it works the same, and it looks like it is, that could be of for me. I'll ask you another question in another ticket, about profile.d files :)
