### ISSUE TITLE
add jupyter-* to some group

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/the-littlest-jupyterhub#349]
Can tljh support automatically add its `jupyer-*` users to some groups (like "video" or "cuda", for instance)?

**Comment by yuvipanda** [comment]
@gsemet this is probably something we can do. Can you explain your use case a little more?

**Comment by gsemet** [comment]
My users need to belong at least to the video group to be able to start tensorflow-gpu. I think this is pretty legit use case, but this would involve setting a configuration such as:
```yaml
user_groups:
   - video
   - cuda
```
and upon user creation, it would `useradd -g video jupyter-myusername`

**Comment by mylyu** [comment]
I just read the doc (https://tljh.jupyter.org/en/latest/topic/tljh-config.html#extra-user-groups), so currently we still need to add users to groups one by one, instead of automatically assigning them to groups on creation?
