### ISSUE TITLE
Document/move configuration

### ISSUE THREAD

**Issue by minrk** [jupyterhub/the-littlest-jupyterhub#35]
Currently config is located in $PREFIX/config.yaml, which is where admin users are set, and presumably authenticator will be chosen when that's exposed, etc. This file doesn't seem to appear in the docs yet.

It would probably be good to put all user-editable files (config.yml, mainly) to a different prefix (e.g. /etc/tljh) so that users upgrading/reinstalling can easily trash the whole tljh directory and start over without losing their admin list, etc.

**Comment by JuanCab** [comment]
I concur.  I've been a little nervous about updating TLJH from the version I currently have running for precisely this reason.

**Comment by yuvipanda** [comment]
I'm torn between keeping *everything* under /opt vs splitting things out. Splitting just the config out is a good idea, but maybe one way to do it is to keep it under /opt/tljh/config.yaml but then keep everything else there right now under a subdir? 

We already put systemd unit files in /etc though, so maybe that ship has sailed.

Generally, we don't really have a good story around uninstallation.

**Comment by yuvipanda** [comment]
@JuanCab good call! We don't really test upgrades or have a story around that yet.

**Comment by minrk** [comment]
Yeah, I'd be fine with siblings in one directory vs /etc/tljh or /etc/jupyterhub. It doesn't make much difference to me, and I recognize the attraction of "it's all in here." As long as the main goal of easily trashing the install without losing my config files is achievable, I'm happy.

Related to my comment in #36, it could be that the user-editable file starts as empty and is *merged* with the config.yaml in /opt/tljh rather than installing a filled-out config.yaml that users can edit.

**Comment by yuvipanda** [comment]
siblings in /opt/tljh it is!

I also have opened #38 with what I think we should do for making users configure this. Since we're focused specifically on folks who don't have that much sysadmin experience, not requiring them to edit YAML through a web terminal seems... ideal.

I also know from @choldgraf and @willingc (and watching people give talks) that editing on the terminal is a big hurdle for a lot of people, and this will help fix it.

**Comment by yuvipanda** [comment]
See #77

**Comment by yuvipanda** [comment]
I think ``tljh-config`` has solved this.
