### ISSUE TITLE
Documentation update needed for config.yaml location

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#354]
Everywhere that `config.yaml` is listed as being in `/opt/tljh` it needs to be updated to `/opt/tljh/config` as that is the new resting place for the configuration files.

**Comment by yuvipanda** [comment]
Great catch, @JuanCab. Do you think you'll have time to make a PR?

**Comment by JuanCab** [comment]
OK, I'll see if I can get on this in the next day or two.

**Comment by yuvipanda** [comment]
Fixed in #355
