### ISSUE TITLE
How to disable terminals in TLJH

### ISSUE THREAD

**Issue by woschmid** [jupyterhub/the-littlest-jupyterhub#373]
Hi,

I was trying to disable the terminals as described in [Custom jupyterhub_config.py snippets](https://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/escape-hatch.html) but for some reason it did not work for me.

I created a python file  named `jupyterhub_noterminals_config.py` in `/opt/tljh/config/jupyterhub_config.d` with file permissions `-rw-r--r--` (owner is root) and containing the single line:   `c.NotebookApp.terminals_enabled = False`

When I reload the configuration with `sudo tljh-config reload` the terminals are still visible for existing and new users. The terminals are also enabled for all users when I reboot. I found no obvious error message in the JupyterHub logs.

The only way I managed to disable terminals was to change both boolean parameters in line 1282 in `/opt/tljh/user/lib/python3.6/site-packages/notebook/notebookapp.py` from `True` to `False` and then reboot.

What did I miss? 

Thank you in advance.

ps1: installed TLJH with bootstrap.py  (commit  8ec3fab)
ps2# Related [issue in jupyterhub](https://github.com/jupyterhub/jupyterhub/issues/1195)

**Comment by yuvipanda** [comment]
Heya! Thanks for opening the issue!

Config in `jupyterhub_config.d` is only for JupyterHub, not for the Notebook application itself. https://github.com/jupyterhub/the-littlest-jupyterhub/issues/234 has some info on how to set this. Would be great to add to the docs, though.
 
Let us know if that works for you!

**Comment by woschmid** [comment]
Hi,

Thanks to your hint I found a solution:

1. I enabled the terminals again in order to execute the following commands in the terminal of the administrator user in TLJH
2. I searched for the config paths using the command `jupyter --paths` (mentioned in [this issue](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/288))
3. I generated a config file _jupyter_notebook_config.py_ using the command `jupyter notebook --generate-config` (described [here](https://jupyter-notebook.readthedocs.io/en/stable/config.html)). This file is generated into the admin's _.jupyter_ directory (listed first in the config paths)
4. I enabled the line `c.NotebookApp.terminals_enabled = True` in the generated _jupyter_notebook_config.py_
5. I copied this file using `sudo` to `/opt/tljh/user/etc/jupyter` (listed second in the config paths) and changed it's entry from `True` to `False`
6. Reboot the server (is there a better way?)
7. Now the TLJH administrator user has access to a terminal and all normal users have no terminal

**Comment by yuvipanda** [comment]
@woschmid awesome! Glad you have that working :) 

Starting and stopping a user's server should work instead of having to reboot the machine, since notebook server reads the config on each start. 

I'm going to close this now since we've figured out what works for you. Thank you for posting a detailed solution for the next person who finds this issue! <3

**Comment by HankZMH** [comment]
I solve the problem by uninstall terminado package, and it work for me.Just run```pip uninstll -y terminado ```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/disable-terminals-and-shell-script-in-tljh/5977/3
