### ISSUE TITLE
Change password doesn't work

### ISSUE THREAD

**Issue by efedorov-dart** [jupyterhub/the-littlest-jupyterhub#375]
I'm trying to change admin password. And It seems impossible to do!
1.
When access: /hub/auth/change-password from logged in user it produces:

Jun 13 15:41:38 paytonstudio python3[20278]: [I 2019-06-13 15:41:38.474 JupyterHub log:174] 200 GET /hub/auth/change-password (admin@192.168.11.155) 47.65ms
Jun 13 15:41:45 paytonstudio python3[20278]: [E 2019-06-13 15:41:45.047 JupyterHub web:1788] Uncaught exception POST /hub/auth/change-password (192.168.11.155)
Jun 13 15:41:45 paytonstudio python3[20278]:     HTTPServerRequest(protocol='https', host='st....xyz', method='POST', uri='/hub/auth/change-password', version='HTTP/1.1', remote_ip='192.168.11.155')
Jun 13 15:41:45 paytonstudio python3[20278]:     Traceback (most recent call last):
Jun 13 15:41:45 paytonstudio python3[20278]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
Jun 13 15:41:45 paytonstudio python3[20278]:         result = await result
Jun 13 15:41:45 paytonstudio python3[20278]:       File "/opt/tljh/hub/lib/python3.6/site-packages/firstuseauthenticator/firstuseauthenticator.py", line 53, in post
Jun 13 15:41:45 paytonstudio python3[20278]:         self.authenticator.reset_password(user.name, new_password)
Jun 13 15:41:45 paytonstudio python3[20278]:     AttributeError: 'coroutine' object has no attribute 'name'
Jun 13 15:41:45 paytonstudio python3[20278]:

2. I changed is using system passwd:
sudo passwd jupyter-admin
Enter new password: ....

But the password for admin remains the same. I can login with initial default insecure password.

**Comment by efedorov-dart** [comment]
It seems you forgot to add await on  self.get_current_user() in firstuseauthenticator.py

**Comment by efedorov-dart** [comment]
yep. That fixes. 
And also there are no link to change password page.

**Comment by GeorgianaElena** [comment]
This should now be fixed by https://github.com/jupyterhub/firstuseauthenticator/pull/23, (originally started in  https://github.com/jupyterhub/firstuseauthenticator/pull/20).
Thanks a lot @efedorov-dart and @ABVitali  for woking on this :confetti_ball:
