### ISSUE TITLE
admin-user-name can not be capitalized

### ISSUE THREAD

**Issue by burkett123** [jupyterhub/the-littlest-jupyterhub#378]
python3 - \
--admin <admin-user-name>

I tried an <admin-user-name> of "Librarian" and it appears a user name with a capital letter does not function.

**Comment by GeorgianaElena** [comment]
Hi @burkett123! Thanks for opening this issue.
Can you please describe the config you're using (especially what authenticator) and  the JupyterHub logs (https://the-littlest-jupyterhub.readthedocs.io/en/latest/troubleshooting/logs.html#jupyterhub-logs)?

**Comment by consideRatio** [comment]
This may be a real issue to be addressed, but it may depend on the authenticator if so as well. I'll go for a close in this repo that supports arbitrary authenticators.
