### ISSUE TITLE
Installation on Digital Ocean stalls waiting for user input

### ISSUE THREAD

**Issue by biogeo** [jupyterhub/the-littlest-jupyterhub#379]
I installed TLJH on a Digital Ocean droplet following the instructions included. (Overall very helpful, by the way.) After waiting some time for the JupyterHub server to come online as written in the guide, there was no sign of success. I ended up SSHing to the droplet to check the status of the running processes. `ps aux` revealed that `apt-get` was hung up waiting for some installation scripts that were stuck on `whiptail` waiting for user input. After realizing there was no way for me to provide that input I just ran `killall whiptail`. This was apparently just as good as giving direct confirmation and the installation of TLJH proceeded normally from there.

On a quick glance it looked like `apt` was run with the `-y` flag so I don't know what the source of the problem was. At any rate, if anyone else experiences this, connecting to the droplet via SSH and running `killall whiptail` should be a workaround.

**Comment by yuvipanda** [comment]
Thanks for opening this, @biogeo! I *think* #380 should fix this. I'm trying to figure out how to test it...
