### ISSUE TITLE
Compatibility with other compilers

### ISSUE THREAD

**Issue by kandulaziot** [jupyterhub/the-littlest-jupyterhub#394]
How can we enable other compilers/notebooks for example Python2, R, etc.

I this compatible with them

**Comment by GeorgianaElena** [comment]
Hi @kandulaziot. Maybe [this response](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/279#issuecomment-472805633) and [docs section](http://tljh.jupyter.org/en/latest/howto/env/user-environment.html#installing-conda-packages) the will help.
Currently we don't have a complete tutorial guide on how to add new notebooks to TLJH but it's something we're planning to add (as discussed [here](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/279))

**Comment by consideRatio** [comment]
Closed in favor of #728 that outlines the need for documentation examplifying how to add a kernel.
