### ISSUE TITLE
Trying jupyter hub for the first time

### ISSUE THREAD

**Issue by Chekos** [jupyterhub/the-littlest-jupyterhub#4]
This is not a real issue I just want to express my gratitude for this project. 

I had **never** even ssh'd into a server before today but within 20 minutes I had a jupyter hub instance on the cloud and I could even do this:
[image_of_my_phone](https://github.com/Chekos/pics_for_github/blob/master/IMG_8572.JPG)
I have no practical use to code on my phone but I think it really illustrates how powerful this could be specially in the hands of beginners. 
The original Jupyter Hub seemed doable but a little daunting to me. This 'littlest' jupyter hub I spun up in like 3 commands. I am amazed and truly grateful. I think great things will come from this. 

I used to work at a middle school where most kids have access to a chromebook which they **cannot** use to code (at least not easily) but this is incredibly easy to set up. Imagine how many schools could use a tool like this, not only here in the US but around the world. 
It cost me nothing to put this together because of how much credit these could services give you when you sign up but even when that runs out it is incredibly cheap to keep the service going. 
I grew up in Mexico where most schools don't have the resources to provide each student with access to a computer much less having an IT person around. With this, it feels like any teacher who really wants to could set up a jupyter hub and all their students need is internet. 

I am excited to see what comes out of this.

Thank you so much, 👍

**Comment by yuvipanda** [comment]
<3 thank you for trying it out, and the early encouragement! \o/ It's gotten more easier since, so do try it out again and let us know what you think!
