### ISSUE TITLE
Systemd config does not validate under Ubuntu Bionic

### ISSUE THREAD

**Issue by stormerider** [jupyterhub/the-littlest-jupyterhub#408]
```
Jul 30 20:56:50 dev-ml systemd[1]: /etc/systemd/system/jupyterhub.service:12: Failed to parse protect home value, ignoring: tmpfs
```
This is from the jupyterhub service file:
```
root@dev-ml:/opt/tljh/config# cat /etc/systemd/system/jupyterhub.service 
# Template file for JupyterHub systemd service
# Uses simple string.format() for 'templating'
[Unit]
# Traefik must have successfully started *before* we launch JupyterHub
Requires=traefik.service
After=traefik.service

[Service]
User=root
Restart=always
# jupyterhub process should have no access to home directories
ProtectHome=tmpfs
WorkingDirectory=/opt/tljh/state
# Protect bits that are normally shared across the system
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
Environment=TLJH_INSTALL_PREFIX=/opt/tljh
# Run upgrade-db before starting, in case Hub version has changed
# This is a no-op when no db exists or no upgrades are needed
ExecStart=/opt/tljh/hub/bin/python3 -m jupyterhub.app -f /opt/tljh/hub/lib/python3.6/site-packages/tljh/jupyterhub_config.py --upgrade-db

[Install]
# Start service when system boots
WantedBy=multi-user.target
root@dev-ml:/opt/tljh/config# 
```
From my research, ProtectHome=tmpfs was introduced in [version 238](https://www.phoronix.com/scan.php?page=news_item&px=Systemd-238-Released) of systemd. Ubuntu Bionic is still on version 237.

**Comment by feria35** [comment]
Hello @stormerider or anyone who has that issue.
My VPS is on Ubuntu 18.04 Server (by OVH) Bionic.
I had exactly the problem you described and I noticed it only happened when NginX was already installed, I mean before TLJH install. Stopping the service NginX is not enough to get rid of that error at TLJH's install.
So, from nowadays, I install **TLJH before NginX**, Let's Encrypt, PHP etc ..  and it's OK now.
I can't give you any explaination, but it might help you.

**Comment by stormerider** [comment]
That's interesting. I do have nginx installed. and it probably was before TLJH. I still think it is a bug; it's trying to use a feature that Bionic doesn't support.
