### ISSUE TITLE
Make spawner start voila?

### ISSUE THREAD

**Issue by DentonGentry** [jupyterhub/the-littlest-jupyterhub#425]
I have a TLJH instance which I am trying to make spawn Voila with a specific notebook for each user, by adding /opt/tljh/config/jupyterhub_config.d/spawner.py

```
c.Spawner.args = ['--NotebookApp.default_url=/voila/tree/drawdown/VoilaDrawdown.ipynb']
```

However, it starts a regular notebook instead. The Notebook has a Voila button which does work, Voila starts and renders the ipynb file. I just can't see what I need to do to make it start automatically.

![Screen Shot 2019-08-28 at 6 38 20 PM](https://user-images.githubusercontent.com/1140756/63903651-0d45e180-c9c3-11e9-8081-5dba37fd8af9.png)

**Comment by jtpio** [comment]
@DentonGentry and with the render endpoint? `/voila/render/drawdown/VoilaDrawdown.ipynb`

**Comment by DentonGentry** [comment]
/voila/render/drawdown/VoilaDrawdown.ipynb does start Voila, yay! Thank you!

**Comment by jtpio** [comment]
Great!

**Comment by DentonGentry** [comment]
I need to ask another question if I may: I'm trying to set --enable_nbextension=True. Adding it to c.Spawner.args didn't work, I think because those are the arguments passed to jupyterhub-singleuser not to a voila process.

Changing the default to True in python3.7/site-packages/voila/configuration.py didn't work either. I don't really understand why.

Is there a way to get the equivalent effect with JupyterHub of having passed --enable_nbextension=True to a standalone voila process?

**Comment by jtpio** [comment]
Have you tried passing `--VoilaConfiguration.enable_nbextensions=True`? It should be picked up by the server extension.

**Comment by DentonGentry** [comment]
--VoilaConfiguration.enable_nbextensions=True worked, and also led me to find Voila 0.1.10 and --VoilaConfiguration.file_whitelist which solved another problem I was running into with 404s for static files. Yay again!

For anyone perusing this issue in the future, my current jupyterhub config includes:

```
c.Spawner.args = ['--NotebookApp.default_url=/voila/render/drawdown/VoilaDrawdown.ipynb',
    '--VoilaConfiguration.enable_nbextensions=True',
    "--VoilaConfiguration.file_whitelist=['.*']"]
```

**Comment by jtpio** [comment]
Glad you got it working @DentonGentry !

Don't hesitate to open issues on the [voila repo](https://github.com/QuantStack/voila) directly if you have more questions.
