### ISSUE TITLE
Is possible to make the-littlest-jupyterhub run in other port/url ?

### ISSUE THREAD

**Issue by viniciusmaran** [jupyterhub/the-littlest-jupyterhub#426]
Hi,
I've tried to find the answer in the docs, but with no success.
Is possible to configure the installer to make Jupyter host run in other port (except the 80) or url (i.e. /jupyter) ?

**Comment by GeorgianaElena** [comment]
Hi @viniciusmaran! You can change the port using ``tljh-config``:
```
sudo tljh-config set http.port 15000
sudo tljh-config reload proxy
```

**Comment by viniciusmaran** [comment]
Hi @GeorgianaElena , thanks!

Is there any possibility to change the local of the installation (i.e. make it run @ IP:80/jupyter, where I have /var/www/html/jupyter in my server) ?

**Comment by GeorgianaElena** [comment]
@viniciusmaran, sorry for the extremely late reply. Setting ``c.JupyterHub.base_url = '/jupyter/'`` (as mentioned [here](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/216)) should be enough.
