### ISSUE TITLE
typo in AWS doc

### ISSUE THREAD

**Issue by ppliu** [jupyterhub/the-littlest-jupyterhub#430]
In step 12 of Installing on Amazon Web Services, the documentation reads 

> Choosing to Proceed with a key pair is not recommended as you’ll have no way to access your server via SSH if anything goes wrong with the Jupyterhub and have no way to recover files via download.

Should that be 

> Choosing to Proceed without a key pair

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/jupyterhub/the-littlest-jupyterhub/pull/421
