### ISSUE TITLE
Systemd issue

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/the-littlest-jupyterhub#431]
As pointed out in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/408 and https://github.com/jupyterhub/the-littlest-jupyterhub/issues/237, having ``ProtectHome=tmpfs`` raises some issues:
-  systemd version in Ubuntu Bionic is 237 and ``ProtectHome=tmpfs`` isn't recognized as a valid option, which causes *ProtectHome* to default to *no*.
  (check this with ``systemctl show jupyterhub.service -p ProtectHome`` shows: *ProtectHome=no*)
  Changing ``ProtectHome=yes``(jupyterhub process should have no access to home directories) results in failing spawns because the users home directories don't get created.
- systemd version in [Ubuntu 18.10 is 239](https://packages.ubuntu.com/cosmic/systemd), which supports ``ProtectHome=tmpfs``, but as pointed out in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/237, this doesn't work as expected and users home directories don't get created.

Reading through [systemd's man](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome=), it is my understanding that:
1. having ``ProtectHome=yes``(Ubuntu 18.04) in *jupyterhub.service* makes */home* inaccessible and empty for processes invoked by the jupyterhub unit. This means that when the [spawner is trying to add the user and create its home directory](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/jupyterhub_config.py#L35), because it's being invoked by the jupyterhub unit (thus, */home* is not accessible), it fails with:  
```
Previous spawn for abcd failed: Command '['useradd', '--create-home', 'jupyter-abcd']' returned non-zero exit status 12.
```
2. having ``ProtectHome=tmpfs`` (Ubuntu 18.10)  in *jupyterhub.service*  a temporary file system is mounted on */home* in read-only mode. Being read-only, when the spawner is trying to create the user's home directory */home/jupyter-user* will result in a failure (though I don't understand why an error isn't shown).

I *think* that:
- on Ubuntu 18.04 everything works because ``ProtectHome=tmpfs`` is not recognized and it becomes ``ProtectHome=no`` giving to the jupyterhub unit access to the home directory and thus it's able to create sub-directories in */home* for the users)
- on Ubuntu distributions with a version of *systemd* that recognizes ``ProtectHome=tmpfs``, it fails to create sub-directories in */home* because is read-only for the process that should create them (because it's invoked by the jupyterhub unit).

I don't know what should be done here in order to support both older and newer systemd versions and prevent jupyterhub process from accessing user's home directories but at the same time allowing it to create them. :(

**Comment by yuvipanda** [comment]
Thanks for looking into this deeply!

I think we should just turn it off for now, since 'prevent jupyterhub process from accessing user's home directories but at the same time allowing it to create them' is hard.
