### ISSUE TITLE
503 Server Connection Error (Servers shut down every 10 minutes of user inactivity)

### ISSUE THREAD

**Issue by ypff** [jupyterhub/the-littlest-jupyterhub#432]
Users will receive Server Connection Error after 10 minutes inactivity and need Launch Server. 

<img width="305" alt="Screen Shot 2019-09-04 at 4 35 49 PM" src="https://user-images.githubusercontent.com/42979997/65074460-df6d1080-d962-11e9-96ca-12aed22836bb.png">

<img width="1528" alt="Screen Shot 2019-09-04 at 8 18 30 PM" src="https://user-images.githubusercontent.com/42979997/65074413-c6fcf600-d962-11e9-8933-a0656d8a16f4.png">

How to cancel to the time restriction or make it longer?

**Comment by yuvipanda** [comment]
Heya!

This is because of the idle culler. Here are some docs on how to configure it: http://tljh.jupyter.org/en/latest/topic/idle-culler.html

Hope that helps!
