### ISSUE TITLE
Add new-user-hook

### ISSUE THREAD

**Issue by jkfm** [jupyterhub/the-littlest-jupyterhub#451]
Hi,

I would like a hook, which runs code after a new user was created. In my case I would use it to configure a specific database access with the user's credentials after the first login. 

What are your thoughts on this? Any counter arguments?

edit: just saw that the plugin-manager is specific to installer.py. Do you think it would be easy to adapt for the new-user-creation method?

**Comment by yuvipanda** [comment]
I think this is a good idea! I'll look at the PR shortly.

Thanks for making it!
