### ISSUE TITLE
I can not remove the user from the admin panel

### ISSUE THREAD

**Issue by aikula** [jupyterhub/the-littlest-jupyterhub#456]
When I try to delete a user (there was a password before), it gives an error.
**API request failed (500): Internal Server Error**

Or how to change a user's password without deleting it.

The server is installed out of the box, standard configuration.

**Comment by GeorgianaElena** [comment]
Hi @aikula! The latest revision in master should have fixed the problem. Changing a user's password using the  [`/hub/auth/change-password`](https://github.com/jupyterhub/firstuseauthenticator#how-can-i-change-my-password) endpoint should now work again.

I'm closing the issue, but please feel free to reopen if you still have issues :sun_with_face:
