### ISSUE TITLE
Multiple users on one account simultaneously?

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#46]
Our use case is for introductory astronomy students to run notebooks.  I would prefer execution be automatic (via the JupyterHub extension appmode), but will accept it might not be.  I currently have created a TLJH user who can log in without a password.  In that account, I have made all the notebook files read-only and owned by another user, so that students can’t change the files.  This allows me to pass the students a link that automatically executes the notebooks in ‘appmode’ and thus requires rather minimal preparation for the students.  I am not considering this ‘security’, just a means of avoiding students accidentally changing the files and causing problems for other students in the shared account.  

In this scenario, can more than one person be signed in on the same account simultaneously without ill consequences?  NOTE: None of the notebooks interact with the server to create files (other than pycache files and the like that are automatically created).

**Comment by yuvipanda** [comment]
Heya! This isn't supported by notebooks or JupyterHub, so going to close this. Let's continue the discussion on solving your underlying problem in #47
