### ISSUE TITLE
Custom umaks

### ISSUE THREAD

**Issue by pulponair** [jupyterhub/the-littlest-jupyterhub#463]
How to set a custom umask for creating notebooks?
Background: i a have a public shared folder where i want notebooks to be created with g+w (umask 002).
I am pretty sure i could hack it into the jupyterhup-singleuser but maybe there is a more elegant way.

Cheers,
Nikolas

**Comment by yuvipanda** [comment]
I just did this the other day.

In `/opt/tljh/config/jupyterhub_config.d/01-umask.py`, add:

```
c.SystemdSpawner.unit_extra_properties = {
        'UMask': '0002'
}
```

This sets up the umask you need.

You can see other systemd properties you can set in https://www.freedesktop.org/software/systemd/man/systemd.exec.html

**Comment by pulponair** [comment]
@yuvipanda ahh lovely, thank you.
I knew that was possible is just did know were :)
Cheers,
Nikolas
