### ISSUE TITLE
Spawn failed...

### ISSUE THREAD

**Issue by rtadewald** [jupyterhub/the-littlest-jupyterhub#465]
I've followed the installation for my own server (Ubuntu 18.04), but I'm getting this error:
![Captura de Tela 2019-11-14 às 16 35 59](https://user-images.githubusercontent.com/22618324/68890149-16f6ff80-06fd-11ea-902e-c86d84938ce7.png)

My logs:
``$ sudo journalctl -u jupyter-rtadewald
-- Logs begin at Mon 2019-07-29 18:08:43 UTC, end at Fri 2019-11-15 01:58:55 UTC. --
Nov 15 01:58:39 asimov_base systemd[1]: Started /bin/bash -c cd /home/jupyter-rtadewald && exec jupyterhub-singleuser --port=33393 --NotebookApp.default_url=/lab.
Nov 15 01:58:39 asimov_base bash[3493]: Traceback (most recent call last):
Nov 15 01:58:39 asimov_base bash[3493]:   File "/opt/tljh/user/bin/jupyterhub-singleuser", line 5, in <module>
Nov 15 01:58:39 asimov_base bash[3493]:     from jupyterhub.singleuser import main
Nov 15 01:58:39 asimov_base bash[3493]:   File "/opt/tljh/user/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 14, in <module>
Nov 15 01:58:39 asimov_base bash[3493]:     from jinja2 import ChoiceLoader
Nov 15 01:58:39 asimov_base bash[3493]: ModuleNotFoundError: No module named 'jinja2'
Nov 15 01:58:39 asimov_base systemd[1]: jupyter-rtadewald.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 01:58:39 asimov_base systemd[1]: jupyter-rtadewald.service: Failed with result 'exit-code'.`

I've already tried without sucess:
```
sudo -H /opt/tljh/hub/bin/pip install jinja2
Requirement already satisfied: jinja2 in ./tljh/hub/lib/python3.6/site-packages
Requirement already satisfied: MarkupSafe>=0.23 in ./tljh/hub/lib/python3.6/site-packages (from jinja2)
```

Does anyone know what could it be?

**Comment by rtadewald** [comment]
Solved by using this:
```
sudo su -
source /opt/tljh/user/bin/activate
pip install jinja2
source /opt/tljh/user/bin/deactivate
exit
```

**Comment by GeorgianaElena** [comment]
Happy you manage to get it work and thanks for posting your solution here @rtadewald :sun_with_face:

**Comment by mukhendra** [comment]
Hi @rtadewald  and @GeorgianaElena 
I'm also getting the same error in jupyter hub while accessing in web browser my spwan failed .
Server at https://10.250.69.3:8000/hub/spawn-pending/mukhendra/ can you guys please help me.
