### ISSUE TITLE
Adding capabilities to TLJH to set up authenticated, automatically set up, accounts

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/the-littlest-jupyterhub#47]
As an alternative to the approach I outlined in Issue #46 (multiple users sharing one account), which frankly, seems dodgy, I am looking at getting TLJH running with HTTPS, LDAP Authentication, and automatic Git retrieval of the code for new users.  So, a few questions I have:

1. Would you recommend creating a new Ubuntu 18.04 VM as a starting point for performing an upgrade to newer versions of TLJH?  Not a big deal, but it seems with the many structural changes I am seeing to how the configuration files will be set up in the near future this makes sense.

2. I assume TLJH replaces Apache as a server, so taking the Apache approach to creating security certificates will not work for HTTPS.  We don't want to run HTTPS through a proxy if we can avoid it (which I _think_ excludes Let's Encrypt via Træfik).  Is there a way to get HTTPS up so our authentication isn't compromised?

3. To install an LDAP authenticator, can I just use the conda installation of   https://github.com/jupyterhub/ldapauthenticator with TLJH or is it different enough from JupyterHub to require a different approach.

4. A similar question about nbgitpuller, can I just follow the installation instructions for it on JupyterHub?  Is it typically to set it up so they follow the link, it creates the account (after LDAP authentication), and then does the automatic git pull?

**Comment by yuvipanda** [comment]
Heya! Thank you for the questions :)

1. Yes, would recommend starting afresh :) We're hoping to push out a v0.1 release sometime next week, so everything is in flux until then.

2. I'm not sure what this means. Can you expand on "We don't want to run HTTPS through a proxy if we can avoid it" mean? HTTPS is high on the list of things to do, see #29 

3. ldapauthenticator is now included in TLJH! Docs coming soon, hopefully once #38 lands

4. Yes, it is typically set up like that. You can follow the instructions already. https://github.com/data-8/nbgitpuller/pull/46 needs to be merged probably. I'll probably ship nbgitpuller by default with TLJH.

What is your timeline like?

**Comment by JuanCab** [comment]
To clarify #2... When I reviewed the HTTPS access offered by Let's Encrypt, it seemed to work by using a proxy for the encrypted front end.  If that was the case, my IT folks said that was not allowed by out system, we have the handle the certificates on the server, so that we are encrypted server to client.  They are used to apache servers, so this is what our IT expects for setting up encryption.

**Comment by JuanCab** [comment]
Didn't mean to close this yet. Sorry. :(

**Comment by yuvipanda** [comment]
@JuanCab the certificates will be on the server, this isn't a cloudflare style external proxy where the certificates live elsewhere. We try design this to require 0 work from institutional IT anywhere, so they wouldn't have to set up apache or anything for handling certificates. We'll try to get that merged in the next few days, and maybe with added documentation it would be clearer!

**Comment by JuanCab** [comment]
Thanks, Let's Encrypt! worked for us (after getting the DNS sorted out).  Thanks!
