### ISSUE TITLE
Environment Variable from get_auth_state() not passed into user environment on Spawning

### ISSUE THREAD

**Issue by eosantigen** [jupyterhub/the-littlest-jupyterhub#470]
I have followed the step from the official documentation [here](https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#authentication-state) in order to inject the value of the 'access_token' into an environment variable that will be available inside each user's notebook/shell.

I have added the snippet:

```
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
            print("AUTH_STATE NOT ENABLED?")
            return
        spawner.environment['TEST'] = auth_state['access_token']
```
inside the _oauthenticator/generic.py_  class right under the _authenticate_ method.

The _authenticate_ method returns :

```
        return {
            'name': resp_json['content'][0]['userName'],
            'auth_state': {
                'access_token': access_token,
                'refresh_token': refresh_token,
                'oauth_user': resp_json,
                'scope': scope,
            }
        }
```

And of course, have the relevant setting: 
```c.LocalGenericOAuthenticator.enable_auth_state = True```

Still, the environment variable does not even show in a user's terminal either as empty or as expected with the certain value .

Also, I have tested likewise:

```
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
            print("AUTH_STATE NOT ENABLED?")
            return
        spawner.environment['TEST'] = 'lol'
        spawner.Spawner.environment= {'TEST': 'lol'}
```
Which also does not work!

What am I missing?

Kind Regards

**Comment by manics** [comment]
Note this was originally opened as https://github.com/jupyterhub/oauthenticator/issues/314

**Comment by GeorgianaElena** [comment]
This has been solved in https://github.com/jupyterhub/oauthenticator/issues/314
