### ISSUE TITLE
Upgrade oauthenticator to 0.10.0 to incorporate AWS cognito

### ISSUE THREAD

**Issue by budgester** [jupyterhub/the-littlest-jupyterhub#471]
The version of oauthenticator that is currently installed is 0.8.2

https://pypi.org/project/oauthenticator/

The new version of oauthenticator is 0.10.0 and has support for aws cognito.

My guess is that it's a change on this line.
https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/installer.py#L212

Unless there is another method of setting the install packages.

**Comment by cgodkin** [comment]
I was totally caught out by this because the installation page 

[http://tljh.jupyter.org/en/latest/howto/auth/awscognito.html](url)

includes the comment 

`# Need to ensure oauthenticator is bumped to 0.10.0`

but perhaps that's a future thing?  TLJH installation following those directions still gives me oauthenticator 0.8.2 which doesn't have AWS Cognito support.

**Comment by budgester** [comment]
and if not do a pip install oauthenticator>=0.10.0, but at the current time 0.8.2 is the default

**Comment by cgodkin** [comment]
I see that I could upgrade the oauthenticator package myself, but I was just hoping someone might edit the AWS Cognito page to fix the comment (or include the "pip install..." command even).  Thanks.

**Comment by cgodkin** [comment]
Actually, I don't know how to install a newer oauthenticator into the "hub" environment so that this authenticator works.  Can someone explain?  I'm trying to follow the steps at 

http://tljh.jupyter.org/en/latest/howto/auth/awscognito.html

Thank you very much!

**Comment by cgodkin** [comment]
For anyone struggling with the same question, we figured it out.  We added these lines into the EC2 "user data" after the curl command:

```
# Upgrade oauthenticator to 0.10.0 in the "hub" environment
cat > /tmp/update_oauthenticator.sh << EOF
source /opt/tljh/hub/bin/activate
pip install -U oauthenticator
EOF
/bin/bash /tmp/update_oauthenticator.sh
```
