### ISSUE TITLE
Ballpark estimates for VM resources in the docs

### ISSUE THREAD

**Issue by geoffbacon** [jupyterhub/the-littlest-jupyterhub#48]
It'd be great to have suggestions in the docs on the number, size and type of resources for typical use cases. For example, "if you expect 50 users crunching big numbers, you might need at least X CPUs with Y RAM, but if you're only having 5 users learning to code for the first time, you probably only need 1 CPU with this much RAM". I can imagine a lot of users (including myself) don't have enough background to get this right.

**Comment by yuvipanda** [comment]
Closed by #68
