### ISSUE TITLE
https certificate expired

### ISSUE THREAD

**Issue by jerpson** [jupyterhub/the-littlest-jupyterhub#480]
After 90 days, the TLJH haven't automatic renew it. the https can't use, how can I resolve it? Thanks very much. @yuvipanda

**Comment by GeorgianaElena** [comment]
Is there anything that may share some light on why this is happening in the [traefik logs](http://tljh.jupyter.org/en/latest/troubleshooting/logs.html#traefik-proxy-logs)?

(I think this issue is related: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/305)

**Comment by jerpson** [comment]
![traefik logs](https://user-images.githubusercontent.com/13460174/72398992-c6913200-377f-11ea-9a28-c42ca6bd4538.png)
@yuvipanda @GeorgianaElena

**Comment by jerpson** [comment]
Thanks. I have solve it. The problem is firewall port.
