### ISSUE TITLE
How could I change default directories .ipynb file generated

### ISSUE THREAD

**Issue by jyh2378** [jupyterhub/the-littlest-jupyterhub#483]
Hi, I've installed TLJH on my own server.
and, I saw the jupyter notebook file(*.ipynb) is generated in ./home/admin-user folder.
How could I change this directory to other?

**Comment by GeorgianaElena** [comment]
Hi @jyh2378! You can use [Spawner.notebook_dir](https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.notebook_dir) to change the notebook directory for the single-user server.

Steps to take:
1. Create a `.py` file in `/opt/tljh/config/jupyterhub_config.d` directory (checkout [custom `jupyterhub_config.py` snippet](http://tljh.jupyter.org/en/latest/topic/escape-hatch.html) for more info about it).
2. In the custom config file previously created, change the spawner's notebook directory:
```
c.Spawner.notebook_dir="path/to/notebook/directory"
```
3. Reload the config:
```
sudo tljh-config reload
```
4. If the the user's server is running, restart it:
Control Panel -> Stop My Server -> Start My Server

**Comment by jyh2378** [comment]
@GeorgianaElena Thank you! I solved it :)

**Comment by sbaehr** [comment]
hi @GeorgianaElena - I found this while trying to do the same thing as @jyh2378 , but the change does not seem to be working for me. I have a file `addl_custom.py` in the `/opt/tljh/config/jupyterhub_config.d` dir, and I've reloaded config and relaunched servers. But still it defaults to the `jupyter-username` home directory.

Any ideas as to why? Happy to supply any useful info, thanks!
