### ISSUE TITLE
Add support to install libraries during TLJH installation

### ISSUE THREAD

**Issue by geoffbacon** [jupyterhub/the-littlest-jupyterhub#49]
Currently, to configure the user environment with libraries, we log in as admin and install them one by one. Given that this is likely to be a common procedure, an alternative is to allow for a requirements.txt/environment.yml file to be included in the TLJH installation process.

**Comment by yuvipanda** [comment]
Thank you for reporting this, @geoffbacon!

Partially fixed by #53, which adds requirements.txt support. Would be nice to add environment.yaml support too!

**Comment by yuvipanda** [comment]
We can add environment.yaml support later when someone asks for it!
