### ISSUE TITLE
Edit description to link to the docs

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/the-littlest-jupyterhub#5]
http://the-littlest-jupyterhub.readthedocs.io/

I can't do that via PRs, you need to edit the repo description via github UI

Also adit your blog post to add a linnk to that :-)

**Comment by yuvipanda** [comment]
I edited the description!

I'm going to wait for a week before publicizing this more widely (including linking from the description). Lots of moving parts! I've been reaching out to individuals and asking them to test instead...

**Comment by Carreau** [comment]
Great ! Awesome, thanks !

**Comment by yuvipanda** [comment]
We do this now!
