### ISSUE TITLE
Integration tests don't match the production installation workflow

### ISSUE THREAD

**Issue by manics** [jupyterhub/the-littlest-jupyterhub#503]
For example https://github.com/jupyterhub/the-littlest-jupyterhub/pull/457 passed all CI tests, but causes an error in production: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/502

**Comment by yuvipanda** [comment]
I think @GeorgianaElena is right in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/504#issuecomment-582280193.

However, our install code *also* git clones the repo, so I'm not sure why this was different.

**Comment by GeorgianaElena** [comment]
> However, our install code also git clones the repo, so I'm not sure why this was different.

@yuvipanda, are you referring to the *git clone* that happens through [this](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/bootstrap/bootstrap.py#L156) *pip install*?

I've read a bit through [these VCS support docs](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support), and it looks like when `--editable` is not used, the repo gets cloned somewhere in */tmp*. In the installer, *--editable* pip flag is added when `TLJH_BOOTSTRAP_DEV == 'yes'`.

For the integration test, we set *TLJH_BOOTSTRAP_DEV* to *yes* in the [Dockerfile](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/integration-tests/Dockerfile#L24) and tljh gets cloned somewhere in the hub venv (I think). But when someone installs tljh, I don't think it's setting TLJH_BOOTSTRAP_DEV (I didn't), so tljh gets cloned in a tmp directory (and won't have access to the source code, only to the tljh package).

I believe this is what caused the *difference* between our tests and an actual deployment.

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, that makes sense! Should we turn that off in our CI? It's useful when developing locally...

**Comment by GeorgianaElena** [comment]
I tried to turned it off, but nothing changed... :(
It appears that we're copying the source code (that comes from the git clone happening in the [checkout step](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/.circleci/config.yml#L62)) into the container [here](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/.circleci/integration-test.py#L88).

It think making the integration tests to work in a production-like manner, comes down to deploying TLJH in a Docker container. What do you think @yuvipanda?
