### ISSUE TITLE
Weird pop-up on documentation pages

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/the-littlest-jupyterhub#520]
Hi folks 👋 

I've just deployed TLJH so I've been digging around the [documentation](https://tljh.jupyter.org/) a lot and I've noticed a pop-up that appears on every page.

<img width="461" alt="Screenshot 2020-02-25 at 18 26 36" src="https://user-images.githubusercontent.com/44771837/75340601-b2fede00-588a-11ea-96bf-87540ef071e4.png">

It's cool that you have such a friendly webpack but gets a bit tiresome if you're clicking the the docs a lot 😄

**Comment by manics** [comment]
Same as BinderHub https://github.com/jupyterhub/binderhub/issues/1069
Do you know how to trigger a docs build? It's an error in the docs theme which I think is now fixed.

**Comment by GeorgianaElena** [comment]
Hey! It looks like the same thing is happening with the binderhub docs https://github.com/jupyterhub/binderhub/issues/1069 and might just need a rebuild to fix it ☺️

**Comment by sgibson91** [comment]
I don't know how to rebuild the docs unfortunately! 😕

**Comment by sgibson91** [comment]
@choldgraf?

**Comment by choldgraf** [comment]
It's a bug in the theme that has already been fixed. We just need to rebuild the docs. I'll try triggering a rebuild on all of our pages in a bit!

**Comment by choldgraf** [comment]
I think this is now fixed, yeah? I just tried a few pages and couldn't find the bug

**Comment by sgibson91** [comment]
Yes I think so, thanks!
