### ISSUE TITLE
How can i compeletly remove/uninstall TLJH ?

### ISSUE THREAD

**Issue by yaakovazat** [jupyterhub/the-littlest-jupyterhub#530]
Current work environment : 
Ubuntu 18.04 Server LTS

**Comment by jtpio** [comment]
There should be some answers in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/128.

The easiest (if your using TLJH on a VM) is to start over from scratch.

**Comment by yaakovazat** [comment]
> There should be some answers in #128.
> 
> The easiest (if you're using TLJH on a VM) is to start over from scratch.

TLJH is running on a real server and that's the problem. I wanna reinstall the TLJH and do not want to effect other Python servers, so willing to find an official way of uninstalling.

**Comment by NPX-nate** [comment]
> > There should be some answers in #128.
> > The easiest (if you're using TLJH on a VM) is to start over from scratch.
> 
> TLJH is running on a real server and that's the problem. I wanna reinstall the TLJH and do not want to effect other Python servers, so willing to find an official way of uninstalling.

What did you find for a solution to uninstalling? I have tried removing the /opt/tljh/ file with no luck. Reinstall is failing.

**Comment by nguyenvulong** [comment]
I need this, really. Current I failed to make it work (#611 help!) and wanted to start from scratch but no way to make sure I completely removed the old one +_+.

**Comment by webDrag0n** [comment]
The closest solution I found is provided by #545, on the [installer-actions page](https://tljh.jupyter.org/en/latest/topic/installer-actions.html) the installation steps are explained with a revert instruction attached to each one of them. 

I removed tljh based on these reverting instructions and it seems to work well.
