### ISSUE TITLE
Should the idle culler also cull named servers?

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/the-littlest-jupyterhub#547]
Testing a TLJH deployment with:

- named servers enabled (2 allowed per user)
- the idle culler service enabled

It looks like the default server is correctly culled after it has been idle for more than the number specified in [`timeout`](http://tljh.jupyter.org/en/latest/topic/idle-culler.html#idle-timeout), 

However the named servers are still shown as running in the list of servers and can be accessed normally, and they don't appear to be culled.

Should the idle culler script also take into account the named servers?

**Comment by jtpio** [comment]
Although it looks like they should be taken into account by the idle culler: https://github.com/jupyterhub/the-littlest-jupyterhub/blob/d0118e9d7b424cdde06ba90931e1ff2943de0bb6/tljh/cull_idle_servers.py#L197

**Comment by betatim** [comment]
Maybe this change to the cull idle script used by Z2JH is helpful https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1558

**Comment by jtpio** [comment]
Thanks @betatim for the pointer!

**Comment by jtpio** [comment]
It looks like the `cull_idle.py` file could be copied over to TLJH.

Then adding a new `remove_named_server` option set to `False` by default that can be enabled with `tljh-config`.

**Comment by jtpio** [comment]
Looking into https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1558, it seems like this change is about *deleting* the named server rather than *stopping*?

**Comment by jtpio** [comment]
Fixed by #559.
