### ISSUE TITLE
Test support bot

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/the-littlest-jupyterhub#557]
Please add support label :robot:

**Comment by manics** [comment]
GitHub had a big outage yesterday
https://www.githubstatus.com/
Everything is meant to be normal now but maybe there's a backlog of tasks?

**Comment by GeorgianaElena** [comment]
Maybe... :confused:  I have not idea how to debug this.
This `request-info` bot that I was testing, seems to work: https://github.com/GeorgianaElena/.github/issues/6 (not really sure if this means anything).

**Comment by manics** [comment]
It's back 😀
