### ISSUE TITLE
update documentation on guidance for choosing a VM size

### ISSUE THREAD

**Issue by norcalbiostat** [jupyterhub/the-littlest-jupyterhub#56]
Add more specific info and guidelines to step 10 on https://the-littlest-jupyterhub.readthedocs.io/en/latest/tutorials/google.html 
The link to the google cloud docs is not helpful. 
Suggestions on what would be best for 30 students, 50, 75 etc. 
Do we need more than 1 CPU to handle multiple students login? 
How many hours are typical? Instances are running 24 hours a day right? 
This type of info is helpful for the new user.

**Comment by yuvipanda** [comment]
Closed by #68. Let us know if that's not good enough, @norcalbiostat
