### ISSUE TITLE
Spawn failed - RuntimeWarning: Escape character '_' cannot be a safe character. 

### ISSUE THREAD

**Issue by ilfsn** [jupyterhub/the-littlest-jupyterhub#573]
This is the logs when I install and run jupyterhub on Ubuntu 20.04. How can I fix this error, thank you.

 5월 16 02:56:14 imtl-AI2 systemd[1]: jupyterhub.service: Succeeded.
 5월 16 02:56:14 imtl-AI2 systemd[1]: Stopped jupyterhub.service.
 5월 16 02:56:14 imtl-AI2 systemd[1]: Started jupyterhub.service.
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.249 JupyterHub app:2240] Running JupyterHub version 1.1.0
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.250 JupyterHub app:2270] Using Authenticator: firstuseauthenticator.firstuseauthenticator.FirstUseAuthenticator
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.250 JupyterHub app:2270] Using Spawner: builtins.UserCreatingSpawner
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.250 JupyterHub app:2270] Using Proxy: jupyterhub_traefik_proxy.toml.TraefikTomlProxy-0+unknown
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.260 JupyterHub app:1349] Loading cookie_secret from /opt/tljh/state/jupyterhub_cookie_secret
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.319 JupyterHub app:1654] Not using whitelist. Any authenticated user will be allowed.
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.377 JupyterHub app:2308] Initialized 0 spawners in 0.006 seconds
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.379 JupyterHub app:2520] Not starting proxy
 5월 16 02:56:15 imtl-AI2 python3[3829]: /opt/tljh/hub/lib/python3.8/site-packages/jupyterhub_traefik_proxy/toml.py:104: RuntimeWarning: Escape character '_' cannot be a safe character. Set allow_collis>
 5월 16 02:56:15 imtl-AI2 python3[3829]:   escaped_routespec = escapism.escape(traefik_routespec, safe=safe)
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.380 JupyterHub app:2556] Hub API listening on http://127.0.0.1:15001/hub/
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.381 JupyterHub app:2571] Starting managed service cull-idle
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.381 JupyterHub service:335] Starting service 'cull-idle': ['/opt/tljh/hub/bin/python3', '-m', 'jupyterhub_idle_culler', '--timeout=600', '>
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.383 JupyterHub service:121] Spawning /opt/tljh/hub/bin/python3 -m jupyterhub_idle_culler --timeout=600 --cull-every=60 --concurrency=5 --m>
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.388 JupyterHub proxy:320] Checking routes
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.388 JupyterHub app:2631] JupyterHub is now running at http://:8000
 5월 16 02:56:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:56:15.577 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 44.69ms
 5월 16 02:57:15 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:15.562 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 30.90ms
 5월 16 02:57:38 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:38.846 JupyterHub log:174] 302 GET / -> /hub/ (@127.0.0.1) 1.71ms
 5월 16 02:57:38 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:38.876 JupyterHub log:174] 302 GET /hub/ -> /hub/spawn (imtl@127.0.0.1) 26.82ms
 5월 16 02:57:39 imtl-AI2 python3[3880]: Running as unit: jupyter-imtl.service
 5월 16 02:57:39 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:39.887 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/imtl (imtl@127.0.0.1) 1006.20ms
 5월 16 02:57:39 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:39.898 JupyterHub pages:347] imtl is pending spawn
 5월 16 02:57:39 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:39.933 JupyterHub log:174] 200 GET /hub/spawn-pending/imtl (imtl@127.0.0.1) 42.07ms
 5월 16 02:57:40 imtl-AI2 python3[3829]: [W 2020-05-16 02:57:40.675 JupyterHub _version:53] jupyterhub version 1.1.0 != jupyterhub-singleuser version 1.0.0. This could cause failure to authenticate and >
 5월 16 02:57:40 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:40.675 JupyterHub base:854] User imtl took 1.791 seconds to start
 5월 16 02:57:40 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:40.676 JupyterHub proxy:258] Adding user imtl to proxy /user/imtl/ => http://127.0.0.1:36103
 5월 16 02:57:40 imtl-AI2 python3[3829]: /opt/tljh/hub/lib/python3.8/site-packages/jupyterhub_traefik_proxy/traefik_utils.py:42: RuntimeWarning: Escape character '_' cannot be a safe character. Set allo>
 5월 16 02:57:40 imtl-AI2 python3[3829]:   return server_type + "_" + escapism.escape(routespec, safe=safe)
 5월 16 02:57:40 imtl-AI2 python3[3829]: [E 2020-05-16 02:57:40.678 JupyterHub base:876] Failed to add imtl to proxy!
 5월 16 02:57:40 imtl-AI2 python3[3829]:     Traceback (most recent call last):
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 869, in finish_user_spawn
 5월 16 02:57:40 imtl-AI2 python3[3829]:         await self.proxy.add_user(user, server_name)
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub/proxy.py", line 271, in add_user
 5월 16 02:57:40 imtl-AI2 python3[3829]:         await self.add_route(
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub_traefik_proxy/toml.py", line 190, in add_route
 5월 16 02:57:40 imtl-AI2 python3[3829]:         traefik_utils.persist_routes(
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/jupyterhub_traefik_proxy/traefik_utils.py", line 153, in persist_routes
 5월 16 02:57:40 imtl-AI2 python3[3829]:         toml.dump(routes_dict, config_fd)
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/toml/encoder.py", line 29, in dump
 5월 16 02:57:40 imtl-AI2 python3[3829]:         d = dumps(o, encoder=encoder)
 5월 16 02:57:40 imtl-AI2 python3[3829]:       File "/opt/tljh/hub/lib/python3.8/site-packages/toml/encoder.py", line 67, in dumps
 5월 16 02:57:40 imtl-AI2 python3[3829]:         raise ValueError("Circular reference detected")
 5월 16 02:57:40 imtl-AI2 python3[3829]:     ValueError: Circular reference detected
 5월 16 02:57:40 imtl-AI2 python3[3829]:     
 5월 16 02:57:40 imtl-AI2 python3[3829]: [E 2020-05-16 02:57:40.680 JupyterHub base:877] Stopping imtl to avoid inconsistent state
 5월 16 02:57:40 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:40.689 JupyterHub log:174] 200 GET /hub/api (@127.0.0.1) 1.88ms
 5월 16 02:57:40 imtl-AI2 python3[3829]: [W 2020-05-16 02:57:40.863 JupyterHub users:617] Server imtl didn't start for unknown reason
 5월 16 02:57:40 imtl-AI2 python3[3829]: [I 2020-05-16 02:57:40.865 JupyterHub log:174] 200 GET /hub/api/users/imtl/server/progress (imtl@127.0.0.1) 763.34ms

**Comment by manics** [comment]
Hi. Unfortunately it looks like this is caused by a recent change. Please follow this issue for updates:
https://github.com/jupyterhub/the-littlest-jupyterhub/issues/572
