### ISSUE TITLE
Working with your local file system / network drive under tljh

### ISSUE THREAD

**Issue by tomnewg** [jupyterhub/the-littlest-jupyterhub#581]
### Bug description

Working with tljh on google cloud. Everything works very well apart from working with the directory module os. For some reason, I am not able to access my local drive or network drives to open certain files. I need this functionaility as users of my juypterhub also all have access to the same network drives. The script opens certain excel files. I have tried with Windows and Mac OS and got same error. Below is the mac os code. Following short code to test:
from os import listdir
listdir(r"/Users/")

#### Expected behaviour

It should give me a list of folders/files in the user folder.

#### Actual behaviour

FileNotFoundError: [Errno 2] No such file or directory: '/Users/'

### How to reproduce

from os import listdir
listdir(r"/Users/")

### Your personal set up

 - OS: Mac OS (I also tried with windows and got the same error)
 
 - Version: Catalina 10.15.5
 
 - Configuration: jupyterhub, google cloud, https enabled 
 

Many thanks for your help guys

**Comment by cmosguy** [comment]
@tomnewg  did you ever figure out a solution this issue?
