### ISSUE TITLE
Add more information on the idle culler

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/the-littlest-jupyterhub#584]
### Proposed change
At http://tljh.jupyter.org/en/latest/topic/idle-culler.html#configuring-the-idle-culler The idle culler is presented. It can only be configured through the `tljh-config` command. There, in the code the command `jupyterhub_idle_culler` is used for which I did not find further information on where it stems from and why out of the sudden it is available on the system. Why is it available at this stage? When was it shipped to my computer? Where can I learn more about it? An explanatory sentence (or even just half a sentence) for further researching available options could be great!

### Alternative options
Instead of including it into the documentation, a quick answer here could also suffice if that is what the maintainers prefer. The documentation could otherwise turn cluddy.

### Who would use this feature?
People who want to learn more about culler configuration and people who want to gather features from different JupyterHub configurations to make their own.

**Comment by dschofield** [comment]
My TLJH install on AWS EC2 from January of this year did not appear to include the jupyterhub_idle_culler package, resulting in lots of error messages in the logs and system degradation after a reasonable amount of unused/zombie notebook server processes had accumulated.

```
Aug 19 07:01:32 ip-x-y-z python3[1753]: [E 2020-08-19 07:01:32.655 JupyterHub service:357] Service cull-idle exited with status 1
Aug 19 07:01:32 ip-x-y-z python3[1753]: [I 2020-08-19 07:01:32.656 JupyterHub service:316] Starting service 'cull-idle': ['/opt/tljh/hub/bin/python3', '-
Aug 19 07:01:32 ip-x-y-z python3[1753]: [I 2020-08-19 07:01:32.658 JupyterHub service:121] Spawning /opt/tljh/hub/bin/python3 -m jupyterhub_idle_culler -
Aug 19 07:01:32 ip-x-y-z python3[1753]: /opt/tljh/hub/bin/python3: No module named jupyterhub_idle_culler
```

It's an easy Pip install (of jupyterhub_idle_culler; to the hub, not user) environment, after which all is well.

**Comment by 1kastner** [comment]
Thank you for sharing your experience here! So I guess the Culler should be installed by default (according to the manual) but somebody changed their mind in the code? Maybe a git blame could give more insight on the matter...

**Comment by 1kastner** [comment]
See https://github.com/jupyterhub/the-littlest-jupyterhub/pull/607 now the additional information is included.
