### ISSUE TITLE
Upgrading the TLJH's "USER" environment Python / Conda ...

### ISSUE THREAD

**Issue by nmvega** [jupyterhub/the-littlest-jupyterhub#615]
Dear Community Friends:

Is it possible to -- after installing `TLJH` -- upgrade it's `USER` `Python / Conda` environment to a latest version of Python? (Without breaking the rest of the platform, of course).

If yes, is there a documented procedure for doing this?

Thank you in advance! `=:)`

**Comment by nmvega** [comment]
Bump. `=:)`

Also, is there a way to `remove` or `grey-out` the `Save`, `Save As` and `Export As` (basically all of the **Save**) options from the menu?

Thank you again!

**Comment by GeorgianaElena** [comment]
Hey @nmvega :wave:

When switching TLJH to Python 3.7 (ref: https://github.com/jupyterhub/the-littlest-jupyterhub/pull/433), there were also added some steps on how to manually update the Python version for an existing install. You can find them [here in the docs](https://tljh.jupyter.org/en/latest/howto/env/user-environment.html#upgrade-to-a-newer-python-version). 

I will open a new issue to try to find a timeline for changing the TLJH default Python version to 3.8.

**Comment by nmvega** [comment]
> Hey @nmvega 
> 
> When switching TLJH to Python 3.7 (ref: #433), there were also added some steps on how to manually update the Python version for an existing install. You can find them [here in the docs](https://tljh.jupyter.org/en/latest/howto/env/user-environment.html#upgrade-to-a-newer-python-version).
> 
> I will open a new issue to try to find a timeline for changing the TLJH default Python version to 3.8.

Hi @GeorgianaElena Thank you! I appreciate that.
