### ISSUE TITLE
tljh-config reload should use base url

### ISSUE THREAD

**Issue by ikhoury** [jupyterhub/the-littlest-jupyterhub#616]
Hey guys,

https://github.com/jupyterhub/the-littlest-jupyterhub/blob/f0b8745194160d003072f579140dff75358da22d/tljh/config.py#L241

This method makes a request to `http://127.0.0.1:%d/hub/api` and therefore does not work when the `base_url` is changed using `c.JupyterHub.base_url`. I guess this is why `tljh-config reload` hangs after changing the base url.

**Comment by GeorgianaElena** [comment]
I believe you are right @ikhoury! Thanks for discovering and reporting this bug :sunflower:

In my opinion, the simplest way to solve this, would be to add `base_url` to the list of things configurable with `tljh-config` and use it in `check_hub_ready` similarly with how we're doing with http port.
I think it's a common enough use-cause to change the base url and it makes sense to make it configurable through `tljh-config`.
@yuvipanda, what do you think about this?

Would you like to open a PR and try to fix this @ikhoury? :heart:

**Comment by ikhoury** [comment]
Sure! Sorry for the late reply, I will work on it with a friend. I like the idea of directly using `tljh-config` to set the base url.
