### ISSUE TITLE
Upgrading to Python 3.8

### ISSUE THREAD

**Issue by tomnewg** [jupyterhub/the-littlest-jupyterhub#617]
How can I install a new tljh with Python 3.8 or upgrading an existing 3.7 to 3.8 whichever is less hassle?

Many thanks

Tom

**Comment by GeorgianaElena** [comment]
Hi @tomnewg :wave: 

There is a section in the docs about this here: https://tljh.jupyter.org/en/latest/howto/env/user-environment.html#upgrade-to-a-newer-python-version. It was added as part of this PR https://github.com/jupyterhub/the-littlest-jupyterhub/pull/433 when Python 3.7 was made the default.
