### ISSUE TITLE
Default to Python 3.8

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/the-littlest-jupyterhub#618]
### Proposed change

Upgrade the Python version for the TLJH user environment to Python 3.8.

### Alternative options

We could also upgrade from Ubuntu Bionic to Ubuntu Focal Fossa which [comes with Python 3.8 by default](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default). This means that the hub `venv` will also use Python3.8.

### Who would use this feature?

There are some related issues asking about upgrading to Python 3.8 that I found:
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/615
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/617

Also, upgrading the OS of the server that TLJH runs on, from Ubuntu Bionic to Ubuntu Focal Fossa can lead to trouble as reported here https://github.com/jupyterhub/the-littlest-jupyterhub/issues/613.

**Comment by GeorgianaElena** [comment]
@yuvipanda, what are your thoughts about this? :cat2:

**Comment by yuvipanda** [comment]
I think we can make a branch for ubuntu 18.04, and stop working on that. And require new installs to be on 20.04, which gives us 3.8 on the venv. This break can also help us do things like switch to conda for the hub environment too, and any other cleanup we might need to make. We won't support upgrades from 18.04 to these, so we can make these breaking changes.

What do you think?

**Comment by GeorgianaElena** [comment]
This sounds like a very good plan @yuvipanda :heart: 
So, the current state of `master` will become `18.04` branch so that at the end we'll have:
- `master` for Ubuntu 20.04
- `18.04` for ubuntu Bionic?

We just need to make sure we're documenting this very good so that people don't break their installs trying to upgrade from master. Maybe put this info at the begging of the readme.

**Comment by yuvipanda** [comment]
@GeorgianaElena yeah, that sounds good! We can also refuse to upgrade if it's a 18.04 instance?

**Comment by gozes** [comment]
So is there a way to use 20.04 for new install or is this still a work in progress?

**Comment by GeorgianaElena** [comment]
Solved by the recent [upgrade to Ubuntu 20.04](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/710) and [conda upgrade](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/697/files) :tada:
