### ISSUE TITLE
Move implementation of class UserCreatingSpawner in a separate module

### ISSUE THREAD

**Issue by ewidl** [jupyterhub/the-littlest-jupyterhub#619]
### Proposed change

I want a TLJH setup in which every user is added automatically to a specific secondary group. This is currently not covered through the `users.extra_user_groups` configuration (which requires to specify the user names), nor through any Linux configuration I am aware of (e.g., in `/etc/login.defs`) or any other way that I was able to figure out. 

However, it is very easy to implement by extending the functionality of class `UserCreatingSpawner`. What I would like to do (in a JupyterHub config file) is the following:
```
from tljh.jupyterhub_config import UserCreatingSpawner
from tljh import user
from tljh.normalize import generate_system_username

class CustomUserCreatingSpawner(UserCreatingSpawner):
    def start(self):
        super_start = super().start()
        system_username = generate_system_username('jupyter-' + self.user.name)
        user.ensure_user_group(system_username, 'testgroup')
        return super_start

c.JupyterHub.spawner_class = CustomUserCreatingSpawner
```
Unfortunately, when I run `tljh-config reload` the import statement in the first line causes the reload to hang. By moving the implementation of class `UserCreatingSpawner` into a separate module, e.g., `tljh/user_creating_spawner.py`, this issues can be solved.

### Alternative options

Alternatively, there could be a configuration option to add all users to a secondary user group (unlike `users.extra_user_groups` which requires to specify the user names). But this requires a bigger effort to implement than my proposed solution.

### Who would use this feature?

I can imagine that there are also other reasons to modify class `UserCreatingSpawner`. My proposed change would benefit also these cases.

Apart from that, it would be a *cleaner* solution in general, separating class implementations and configuration scripts.

### (Optional): Suggest a solution

Class UserCreatingSpawner is currently defined in `tljh/jupyterhub_config.py`. I propose to put it into a separate module, e.g., `tljh/user_creating_spawner.py`.

I would be happy to forge the repo, implement this minor change and make an official merge request.

**Comment by ewidl** [comment]
I just commited a PR to implement the proposed changes (see #633).

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/move-implementation-of-class-usercreatingspawner-in-a-separate-module/6827/1

**Comment by obilodeau** [comment]
Can instructions be provided on how to achieve this using the new `config/jupyterhub_config.d/` python configuration structure?

The above code fails with:

```
Aug 08 20:35:40 tljh-host python3[9693]:     NameError: name 'get_config' is not defined
Aug 08 20:35:40 tljh-host python3[9693]:         c = get_config()  # noqa
Aug 08 20:35:40 tljh-host python3[9693]:       File "/opt/tljh/hub/lib/python3.10/site-packages/tljh/jupyterhub_config.py", line 13, in <module>
Aug 08 20:35:40 tljh-host python3[9693]:         from tljh.jupyterhub_config import UserCreatingSpawner
Aug 08 20:35:40 tljh-host python3[9693]:       File "/opt/tljh/config/jupyterhub_config.d/assign-users.py", line 1, in <module>
```

**Comment by obilodeau** [comment]
I achieved what I wanted to do (custom group) with:

```python
from tljh.user_creating_spawner import UserCreatingSpawner
from tljh import user
from tljh.normalize import generate_system_username

class CustomUserCreatingSpawner(UserCreatingSpawner):
    def start(self):
        super_start = super().start()
        system_username = generate_system_username('jupyter-' + self.user.name)
        user.ensure_user_group(system_username, 'users')
        return super_start

c.JupyterHub.spawner_class = CustomUserCreatingSpawner
```
