### ISSUE TITLE
Provide a way to configure or remove PrivateTmp=yes in the jupyterhub systemd unit

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/the-littlest-jupyterhub#661]
### Proposed change

This is something that came up while trying to mount a shared volume with samba, using the following command from a python `subprocess` when the user logs in:

```bash
mount -t cifs -o user=username,password=abcde1234 //example.com/Data /mnt/username/data
```

However it looks like `systemd` namespaces the mounts, which means that the mounted volume was then not visible to the end user.

Removing `PrivateTmp=yes` from the systemd unit file fixed the issue:

https://github.com/jupyterhub/the-littlest-jupyterhub/blob/18efee665aebd6c59334685eb9929f823ad649b0/tljh/systemd-units/jupyterhub.service#L13

In this setup, the share would first be mounted under `/mnt/username/data` on the host, and then mounted into `/home/jovyan/data` in the user container (using `DockerSpawner`)

### Alternative options

For now it's possible to patch the `jupyterhub.service` systemd unit by either editing it inplace with `sed`, or resinstalling the modified unit without `PrivateTmp=yes`. 

### Who would use this feature?

TLJH admins that would like to mount volumes with samba.

It might also apply to other network based file systems such as NFS? (although not tested).

### (Optional): Suggest a solution

Not sure what the best way would be for now, but maybe this could be made optional or configurable.
Or remove `PrivateTmp=yes`.

**Comment by manics** [comment]
In the meantime if you want an easier way to set it you should be able to override individual settings by creating a file like `/etc/systemd/system/jupyterhub.service.d/override.conf`

E.g. https://unix.stackexchange.com/questions/398540/how-to-override-systemd-unit-file-settings
Note that suggests using `systemctl edit` but I've always just created override files directly using a config management tool, I presume `systemctl edit` would take care of reloading the config though?

**Comment by jtpio** [comment]
Thanks @manics for the pointers!

The issue was mostly opened for visibility and to keep track of the use case. But maybe mentioning these overrides in the TLJH documentation might be enough (and would not require changing the existing unit file).

**Comment by jtpio** [comment]
Providing the `override.conf` file seems to be doing the trick: 

![image](https://user-images.githubusercontent.com/591645/107937167-daf7bd80-6f83-11eb-835b-3314461e74d8.png)

However it looks like it was actually more than `PrivateTmp=no` that was necessary to be able to make the mounts available to users, with the additional settings also disabled:

```conf
[Service]
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
```

**Comment by jtpio** [comment]
> with the additional settings also disabled

It's possible that only one of them is actually needed, and that `PrivateTmp` was not the one to disable.

So maybe the best for now would be to document how to override the service with `override.conf` as mentioned above.

Maybe somewhere in the topics guide: https://tljh.jupyter.org/en/latest/topic/index.html

Or under "Security Considerations` which already has something about the user private `/tmp`: https://tljh.jupyter.org/en/latest/topic/security.html#per-user-tmp

**Comment by jtpio** [comment]
Just opened https://github.com/jupyterhub/the-littlest-jupyterhub/pull/663 to document this.
