### ISSUE TITLE
`jupyterhub-nativeauthenticator v0.0.7` breaks the sign up page.

### ISSUE THREAD

**Issue by ikhoury** [jupyterhub/the-littlest-jupyterhub#685]
### Bug description
Sign up page returns `500 internal server error`. Users are unable to sign up to the service.

#### Expected behaviour
Sign up page should load correctly.

#### Actual behaviour
Sign up page returns `500 internal server error`.

### How to reproduce

1. Go to your JupyterHub login page.
2. Click on 'Sign Up'.

### Your personal set up
Single server `the-littlest-jupyterhub` installation.

 - OS: Ubuntu 18.04
 - Version(s): JupyterHub `1.2.2`, Python `3.6.9`

- <details><summary>Full environment</summary>

```
aiohttp==3.7.4.post0
alembic==1.6.0
async-generator==1.10
async-timeout==3.0.1
attrs==20.3.0
backoff==1.10.0
bcrypt==3.2.0
certifi==2020.12.5
certipy==0.1.3
cffi==1.14.5
chardet==3.0.4
cryptography==3.4.7
decorator==5.0.7
deepmerge==0.3.0
entrypoints==0.3
escapism==1.0.1
etcd3==0.12.0
greenlet==1.0.0
grpcio==1.37.1
idna==2.10
idna-ssl==1.1.0
importlib-metadata==4.0.1
ipython-genutils==0.2.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter-telemetry==0.1.0
jupyterhub==1.2.2
jupyterhub-configurator==1.0
jupyterhub-dummyauthenticator==0.3.1
jupyterhub-firstuseauthenticator==0.14.1
jupyterhub-idle-culler==1.0
jupyterhub-ldapauthenticator==1.3.0
jupyterhub-nativeauthenticator==0.0.7
jupyterhub-systemdspawner==0.15.0
jupyterhub-tmpauthenticator==0.6
jupyterhub-traefik-proxy==0.2.0
ldap3==2.9
Mako==1.1.4
MarkupSafe==1.1.1
multidict==5.1.0
oauthenticator==0.10.0
oauthlib==3.1.0
onetimepass==1.0.1
pamela==1.0.0
passlib==1.7.4
pkg-resources==0.0.0
pluggy==1.0.0.dev0
prometheus-client==0.10.1
protobuf==3.15.8
pyasn1==0.4.8
pycparser==2.20
pycurl==7.43.0.6
pyOpenSSL==20.0.1
pyrsistent==0.17.3
python-consul2==0.1.5
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
requests==2.25.1
ruamel.yaml==0.15.100
six==1.15.0
SQLAlchemy==1.4.13
tenacity==7.0.0
the-littlest-jupyterhub==0.1
toml==0.10.2
tornado==6.1
traitlets==4.3.3
typing-extensions==3.10.0.0
urllib3==1.26.4
yarl==1.6.3
zipp==3.4.1
```
</details>

- <details><summary>Configuration</summary>
- configure native authentication: `tljh-config set auth.type nativeauthenticator.NativeAuthenticator`
- set jupyterlab as default: `tljh-config set user_environment.default_app jupyterlab`
- disable idle culling: `tljh-config set services.cull.enabled False`
- set base url: `tljh-config set base_url /jupyter/{{ project_name }}/`
- update conda: `source /opt/tljh/user/bin/activate && conda update --yes --quiet conda`
 - name: install git plugin: `source /opt/tljh/user/bin/activate && conda install --yes --quiet --channel conda-forge jupyterlab-git`
- install r kernel: `source /opt/tljh/user/bin/activate && conda install --yes --quiet --channel r r-essentials`
- install nbgrader plugin: `source /opt/tljh/user/bin/activate && conda install --yes --quiet --channel conda-forge nbgrader`

- <details><summary>Logs</summary>

Server logs:
```
[E 2021-05-04 13:35:42.712 JupyterHub web:1793] Uncaught exception GET /jupyter/jupyter-issa/hub/signup
     HTTPServerRequest(protocol='https', host='datascience.hu.nl', method='GET', uri='/jupyter/jupyter-issa/hub/signup', version='HTTP/1.1',
    Traceback (most recent call last):
       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
         result = await result
      File "/opt/tljh/hub/lib/python3.6/site-packages/nativeauthenticator/handlers.py", line 39, in get
         two_factor_auth=self.authenticator.allow_2fa,
     TypeError: object str can't be used in 'await' expression
```
</details>

**Note**: Downgrading to `v0.0.6` and reloading the hub fixes the issue.

**Comment by jihobak** [comment]
same issue here too. 
I think this issue was started from belows

https://github.com/jupyterhub/nativeauthenticator/issues/130
https://github.com/jupyterhub/nativeauthenticator/pull/129

**Comment by GeorgianaElena** [comment]
Thanks for reporting this @ikhoury and @jihobak 

The `nativeauthenticator` version has been bumped recently from 0.0.5 to 0.0.7 to fix another bug (https://github.com/jupyterhub/the-littlest-jupyterhub/pull/683). Did you experience any of the issues reported in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/631 when using `0.0.6`?

(cc @lambdaTotoro who knows more about `nativeauthenticator` :sunflower: I'm wondering if this is instead an issue on tljh's side rather than nativeauthenticator's)

**Comment by lambdaTotoro** [comment]
On a cursory glance: I think this is exactly the problem that @jihobak linked above. `nativeauthenticator v.0.0.7` needs `jupyterhub v.1.3.0` or later, but OP seems to run `1.2.2`. That would be the problem.

**Comment by GeorgianaElena** [comment]
Thanks a lot @lambdaTotoro! Just opened https://github.com/jupyterhub/the-littlest-jupyterhub/pull/688 to bump the hub version.
