### ISSUE TITLE
Environment PATH different in notebook than terminal 

### ISSUE THREAD

**Issue by jeanf57** [jupyterhub/the-littlest-jupyterhub#698]
### Bug description

PATH environment variable differ between notebook and terminal

#### Expected behaviour

Should have access to same libraries in notebook as the terminal

#### Actual behaviour

Notebook generates error - while it works fine in the terminal 
### How to reproduce

**In notebook I type:**
!nvcc --version 
**it return :** 
"/bin/bash: nvcc: command not found"
**in terminal i Type:**
nvcc --version 
**it return:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
... 

**In notebook I type:**
!echo $PATH 
**it return :** 
"/opt/tljh/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
**in terminal i Type:**
echo $PATH 
**it return:**
/usr/local/cuda/bin:/opt/tljh/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
^^^^^^^^^^^^^^ not in the notebook
### Your personal set up

 - OS:
 
 - Version(s): DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
 
jupyterhub --version
1.4.0

python --version 
Python 3.7.3
- <details><summary>Full environment</summary>

conda list 
# packages in environment at /opt/tljh/user:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_tflow_select             2.1.0                       gpu  
absl-py                   0.13.0           py37h06a4308_0  
aiohttp                   3.7.4            py37h27cfd23_1  
alembic                   1.6.2                    pypi_0    pypi
anyio                     3.0.1                    pypi_0    pypi
argon2-cffi               20.1.0           py37h27cfd23_1  
arrow-cpp                 1.0.1           py37h0d899e7_30_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
astor                     0.8.1            py37h06a4308_0  
astunparse                1.6.3                      py_0  
async-timeout             3.0.1            py37h06a4308_0  
async_generator           1.10             py37h28b3542_0  
attrs                     21.2.0             pyhd3eb1b0_0  
aws-c-cal                 0.4.5                hb3cee0b_7    conda-forge
aws-c-common              0.5.1                h27cfd23_0  
aws-c-event-stream        0.2.7                hf6e4101_0    conda-forge
aws-c-io                  0.9.0                hd4bc808_1    conda-forge
aws-checksums             0.1.11               hbd38b91_2    conda-forge
aws-sdk-cpp               1.8.138              hfa2f2a4_3    conda-forge
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    3.2.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.3.1              pyhd3eb1b0_0  
blinker                   1.4              py37h06a4308_0  
bokeh                     2.3.3            py37h06a4308_0  
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.7.5             h06a4308_1  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.5.30        py37h06a4308_0  
certipy                   0.1.3                    pypi_0    pypi
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4           py37h06a4308_1003  
click                     8.0.1              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
conda                     4.10.3           py37h06a4308_0  
conda-package-handling    1.7.3            py37h27cfd23_1  
coverage                  5.5              py37h27cfd23_2  
cryptography              3.4.7            py37hd23ed53_0  
cudatoolkit               10.1.243             h036e899_8    nvidia
cudf                      0.19.2          cuda_10.1_py37_gab3b3f653a_0    rapidsai
cudnn                     7.6.5                cuda10.1_0  
cugraph                   0.19.0          py37_gd72b90b0_0    rapidsai
cuml                      0.19.0          cuda10.1_py37_g4cb78ff1a_0    rapidsai
cupti                     10.1.168                      0  
cupy                      8.1.0            py37h66f4e5a_0    conda-forge
cycler                    0.10.0                   py37_0  
cython                    0.29.24          py37h295c915_0  
cytoolz                   0.11.0           py37h7b6447c_0  
dask                      2021.4.0           pyhd3eb1b0_0  
dask-core                 2021.4.0           pyhd3eb1b0_0  
dask-cuda                 0.19.0                   py37_0    rapidsai
dask-cudf                 0.19.2          py37_gab3b3f653a_0    rapidsai
decorator                 5.0.7                    pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0  
distributed               2021.4.0         py37h06a4308_0  
dlpack                    0.3                  he6710b0_1  
entrypoints               0.3                      py37_0  
faiss-proc                1.0.0                      cuda    rapidsai
fastavro                  1.4.2            py37h7f8727e_0  
fastrlock                 0.6              py37h2531618_0  
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.10.4               h5ab3b9f_0  
fsspec                    2021.7.0           pyhd3eb1b0_0  
future                    0.18.2                   py37_1  
gast                      0.4.0                      py_0  
gflags                    2.2.2                he6710b0_0  
glog                      0.4.0                he6710b0_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               1.33.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0                      py_0  
greenlet                  1.1.0                    pypi_0    pypi
grpc-cpp                  1.35.0               h2157cd5_4  
grpcio                    1.36.1           py37h2157cd5_1  
gym                       0.18.0           py37h085eea5_1    conda-forge
h5py                      2.10.0           py37hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
icu                       68.1                 h2531618_0  
idna                      2.10               pyhd3eb1b0_0  
importlib-metadata        4.0.1                    pypi_0    pypi
importlib_metadata        3.10.0               hd3eb1b0_0  
intel-openmp              2021.3.0          h06a4308_3350  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.22.0           py37hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3                    pypi_0    pypi
jedi                      0.17.0                   py37_0  
jinja2                    3.0.1              pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                    pypi_0    pypi
jsonschema                3.2.0                      py_2  
jupyter-client            6.2.0                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-resource-usage    0.5.1                    pypi_0    pypi
jupyter-server            1.7.0                    pypi_0    pypi
jupyter-telemetry         0.1.0                    pypi_0    pypi
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.7.1            py37h06a4308_0  
jupyter_highlight_selected_word 0.2.0           py37h89c1867_1002    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py37h89c1867_2    conda-forge
jupyterhub                1.4.0                    pypi_0    pypi
jupyterhub-nativeauthenticator 0.0.7                    pypi_0    pypi
jupyterlab                3.0.15                   pypi_0    pypi
jupyterlab-server         2.5.1                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
keras-base                2.4.3                      py_0  
keras-gpu                 2.4.3                         0  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.3.1            py37h2531618_0  
krb5                      1.19.2               hac12032_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
libblas                   3.9.0                     9_mkl    conda-forge
libcudf                   0.19.2          cuda10.1_gab3b3f653a_0    rapidsai
libcugraph                0.19.0          cuda10.1_gd72b90b0_0    rapidsai
libcuml                   0.19.0          cuda10.1_g4cb78ff1a_0    rapidsai
libcumlprims              0.19.0          cuda10.1_ga2abf9f_0    nvidia
libcurl                   7.71.1               h303737a_2  
libedit                   3.1.20210216         h27cfd23_1  
libevent                  2.1.8                h1ba5d50_1  
libfaiss                  1.7.0           cuda101h3168606_5_cuda    rapidsai
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0                     9_mkl    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.14.0               h8c45485_0  
librmm                    0.19.0          cuda10.1_g7065af3_0    rapidsai
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libthrift                 0.13.0               hfb8234f_6  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libutf8proc               2.6.1                h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.2.0                h27cfd23_0  
libxgboost                1.4.0dev.rapidsai0.19      cuda10.1_0    rapidsai
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
llvmlite                  0.36.0           py37h612dafd_4  
locket                    0.2.1            py37h06a4308_1  
lxml                      4.5.1            py37hefd8a0e_0  
lz4-c                     1.9.3                h2531618_0  
magma-cuda113             2.5.2                         1    pytorch
mako                      1.1.4                    pypi_0    pypi
markdown                  3.3.4            py37h06a4308_0  
markupsafe                2.0.1            py37h27cfd23_0  
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py37h817c723_0  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.0            py37h42c9631_2  
mkl_random                1.2.2            py37h51133e4_0  
msgpack-python            1.0.2            py37hff7bd54_1  
multidict                 5.1.0            py37h27cfd23_2  
nbclassic                 0.2.8                    pypi_0    pypi
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.1.0            py37h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
nbgitpuller               0.9.0                    pypi_0    pypi
nccl                      2.9.8.1              h8b44402_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nettle                    3.7.3                hbbd107a_1  
ninja                     1.10.2               hff7bd54_1  
notebook                  6.3.0                    pypi_0    pypi
nteract-on-jupyter        2.1.3                    pypi_0    pypi
numba                     0.53.1           py37ha9443f7_0  
numpy                     1.20.3           py37hf144106_0  
numpy-base                1.20.3           py37h74d4b33_0  
nvtx                      0.2.3            py37h5e8e339_0    conda-forge
oauthlib                  3.1.1              pyhd3eb1b0_0  
olefile                   0.46                     py37_0  
onetimepass               1.0.1                    pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openjpeg                  2.3.0                h05c96fa_1  
openssl                   1.1.1k               h27cfd23_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
orc                       1.6.7                h7950760_0    conda-forge
packaging                 21.0               pyhd3eb1b0_0  
pamela                    1.0.0                    pypi_0    pypi
pandas                    1.2.4            py37h2531618_0  
pandocfilters             1.4.3            py37h06a4308_1  
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.2              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.3.1            py37h2c7a002_0  
pip                       21.1.3           py37h06a4308_0  
prometheus_client         0.11.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
protobuf                  3.14.0           py37h2531618_1  
psutil                    5.8.0            py37h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py-xgboost                1.4.0dev.rapidsai0.19  cuda10.1py37_0    rapidsai
pyarrow                   1.0.1           py37h3dc597d_30_cuda    conda-forge
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pyglet                    1.5.16           py37h89c1867_0    conda-forge
pygments                  2.9.0              pyhd3eb1b0_0  
pyjwt                     2.1.0            py37h06a4308_0  
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyrsistent                0.17.3           py37h7b6447c_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-editor             1.0.4                    pypi_0    pypi
python-flatbuffers        1.12               pyhd3eb1b0_0  
python-json-logger        2.0.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.8.1           py3.7_cuda10.1_cudnn7.6.3_0    pytorch
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.4.1            py37h27cfd23_1  
pyzmq                     20.0.0           py37h2531618_1  
re2                       2020.11.01           h2531618_1  
readline                  7.0                  h7b6447c_5  
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rmm                       0.19.0          cuda_10.1_py37_g7065af3_0    rapidsai
rsa                       4.7.2              pyhd3eb1b0_1  
ruamel-yaml               0.17.4                   pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
ruamel_yaml               0.15.100         py37h27cfd23_0  
s2n                       1.0.0                h9b69904_0    conda-forge
scikit-learn              0.23.2           py37h0573a6f_0    anaconda
scipy                     1.6.2            py37had2a1c9_1  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
snappy                    1.1.8                he6710b0_0  
sniffio                   1.2.0                    pypi_0    pypi
sortedcontainers          2.4.0              pyhd3eb1b0_0  
spdlog                    1.7.0                hc9558a2_2    conda-forge
sqlalchemy                1.4.15                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tblib                     1.7.0                      py_0  
tensorboard               2.4.0              pyhc547734_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.4.1           gpu_py37ha2e99fa_0  
tensorflow-base           2.4.1           gpu_py37h29c2da4_0  
tensorflow-estimator      2.5.0              pyh7b7c402_0  
tensorflow-gpu            2.4.1                h30adc30_0  
termcolor                 1.1.0            py37h06a4308_1  
terminado                 0.9.4            py37h06a4308_0  
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.2.0              pyhb85f177_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1             pyhd3eb1b0_0  
torchaudio                0.8.1                      py37    pytorch
torchvision               0.9.1                py37_cu101    pytorch
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.61.2             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
treelite                  1.1.0            py37hc731546_0    conda-forge
treelite-runtime          1.1.0                    pypi_0    pypi
typing-extensions         3.10.0.0             hd3eb1b0_0  
typing_extensions         3.10.0.0           pyh06a4308_0  
ucx                       1.9.0+gcd9efd3       cuda10.1_0    rapidsai
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.19.0          py37_gcd9efd3_0    rapidsai
urllib3                   1.26.6             pyhd3eb1b0_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    pypi_0    pypi
websocket-client          0.59.0                   pypi_0    pypi
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.12.1           py37h7b6447c_1  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3            py37h27cfd23_0  
zeromq                    4.3.4                h2531618_0  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.5.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  

</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
**none**
```

sudo -E /opt/tljh/hub/bin/tljh-config show
users:
  admin:
  - hubadmin
  - eceadmin
https:
  enabled: true
  tls:
    key: /etc/mycerts/j##############
    cert: /etc/mycerts/#############
auth:
  hubadmin:
    password: #########
  type: firstuseauthenticator.FirstUseAuthenticator
user_environment:
  default_app: jupyterlab
services:
  cull:
    timeout: 600
    every: 60
    max_age: 0
    users: false
  configurator:
    enabled: false
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
Hi! Your notebook and your terminal are different environments- for example, you can switch between kernels in your notebook. If you need more help please post on the [Jupyter community Forum](https://discourse.jupyter.org/) where more people hang out and the community will be able to help.
