### ISSUE TITLE
Each user creating its own images that only they can see?

### ISSUE THREAD

**Issue by nikl11** [jupyterhub/the-littlest-jupyterhub#699]
Hello, I wanted to use this tljh with tljh-repo2docker plugin (as a replacement for binderhub which I have trouble setting up) for our independent users. I would like it to work like this: our users login to different servers via kerberos authentication, so I would like them to be able to login, create their own environment images, and run them, without any other user being able to access an image of another user. I thought this is how this plugin works by default, but I see only admins can access Environments, and the every created image is visible to all users. Is there any way to do it the my way, each user has its own images that only they can build or run? Thanks.

**Comment by manics** [comment]
The tljh-repo2docker plugin is developed separately, this is the repo: https://github.com/plasmabio/tljh-repo2docker

You can also try posting on the [Jupyter Community Forum](https://discourse.jupyter.org/) where more people hang out, and you might get more support from others who are interested.
