### ISSUE TITLE
document how to use the authenticators

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/the-littlest-jupyterhub#71]
It appears that both the dummy and the firstuse authenticator are supported, but neither are documented.

**Comment by yuvipanda** [comment]
Authenticator documentation is waiting on #38, since that'll completely change how config is set.

**Comment by choldgraf** [comment]
cool - just leaving this here to make sure we don't forget!

**Comment by yuvipanda** [comment]
I added docs for DummyAuthenticator in #77. I've #54 as a Tutorial for Google Authenticator. #78 is documentation for arbitrary authenticators. I think those are more specific, so am going to close this one.
