### ISSUE TITLE
JSONSchema validation of our config

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#725]
The `helm` can validate a schema of the passed YAML values.

We should also support such schema validation for the configuration set via `tljh-config`. This validation can be done whenever the tljh-config command is used to configure something among other times.

The config file is located at `/opt/tljh/config/config.yaml`.

### Related
- #310 - likely avoided with schema validation
- #705 - likely avoided with schema validation

**Comment by jrdnbradford** [comment]
@consideRatio completed by #962 and can probably be closed.

**Comment by consideRatio** [comment]
:heart: :tada: thank you for the help to keep things tidy @jrdnbradford and for the great work in #962!!!

Btw in case you didn't know, this could be made to autoclose on merge of #962 if its description included a note like "fixes #725" or "closes #725" for example.
