### ISSUE TITLE
Topic guide: clearly describe the three key environments

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#735]
We have a root environment where the bootstrap script installs some apt-get packages, like python3 and git. Then we have the hub environment setup by the bootstrap script, and then we have the user environment setup by the tljh.installer.

I think it would be very helpful to have a very thorough description of this.

**Comment by mskblackbelt** [comment]
Seconded. I struggle when trying to figure out where to install certain extensions, especially ones that are meant to modify the JupyterLab instance served up to users (in my head, it seems most of them should be loaded by JH, but often they're loaded by JL once the instance is spawned). The existence of a single root conda environment for users also seems counter to the conda environment mentality. Shouldn't the base environment remain pristine, untouched, while individual ends are used for computation? Maybe I'm just not grokking certain choices properly.
