### ISSUE TITLE
Autoformatting with black?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#752]
Would a black autoformatting PR be acceptable? I've done it in a few repos at this point, some parts typically gets a bit uglier, a few gets better, but the key feature is a very consistent formatting. There are not many, but a few tricks to influence formatting to look better when black sometimes makes it look worse.

- __Influence formatting__
  - For example, you can force a function call with arguments to format the arguments over multiple lines by adding a trailing comma, or make it shrink to a single line by removing the trailing comma if it can fit in a single line.
- __Adjust to formatting__
  If you before had a list of args to call some CLI in an array, and some elements of the list were associated like `["--version", "1.2.3"]`, then you can avoid having them break into two lines in a larger list by adjusting to a single string flag like this: `["--version=1.2.3"]`.

---

To conclude, I'd appreciate going for black autoformatting in this repo, as all repo's I work really. I appreciate the forced consistency no matter who makes a PR, and the reduced amounts of changes in PRs after its been applied systematically. 

Would it be okay if I applied black autoformatting to this repo, and then also did my best to make it look good?

**Comment by raybellwaves** [comment]
Closed via https://github.com/jupyterhub/the-littlest-jupyterhub/pull/755 ?
