### ISSUE TITLE
TLJH python environments don’t appear on the user interface

### ISSUE THREAD

**Issue by florianbeyer** [jupyterhub/the-littlest-jupyterhub#763]
Hi,

Unfortunately, I get no help in teh forum. 

I’m running a TLJH on a remote server.
Everything works quite fine except that the environments I created don’t show up in the browser.
I used the following command to create the environment:

sudo -E conda create -n flo -c conda-forge python=3.6 ipykernel
When I check the environments sudo -E conda env list, the new environment is in the list.
However, there is no option to start a notebook with the new kernel.
(I restarted the hub, and I also restarted the machine… nothing worked)

What can I do to find the solution?

Infos:
Ubuntu 18.04.5 LTS 
JupyterHub version 1.5.0
Python 3.9.7

**Comment by manics** [comment]
I presume you're referring to this forum post? https://discourse.jupyter.org/t/tljh-python-environments-dont-appear-on-the-user-interface/11677
It's been less than a day since you posted so please be a bit more patient. Thanks!
