### ISSUE TITLE
Add "Edit this page button" on docs

### ISSUE THREAD

**Issue by raybellwaves** [jupyterhub/the-littlest-jupyterhub#767]
### Proposed change
On the docs add an "Edit this page button" similar to that for ztjh (bottom right of screen shot below)

e.g. ztjh:
https://zero-to-jupyterhub.readthedocs.io/en/latest/kubernetes/amazon/step-zero-aws.html
<img width="1518" alt="Screen Shot 2021-12-16 at 12 56 00 AM" src="https://user-images.githubusercontent.com/17162724/146316350-dbc0f4e4-1290-4a37-9cee-9a0bacd838bd.png">

e.g. tljh:
https://tljh.jupyter.org/en/latest/install/amazon.html
<img width="1555" alt="Screen Shot 2021-12-16 at 12 57 16 AM" src="https://user-images.githubusercontent.com/17162724/146316513-50c8b2ca-9a05-428c-9a65-c8c4408b6e97.png">

**Comment by MridulS** [comment]
This was fixed in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/840 and the "Edit" button works fine on tljh too.
