### ISSUE TITLE
Successfully created a TLJH development environment in an LXC instance

### ISSUE THREAD

**Issue by GuanglinDu** [jupyterhub/the-littlest-jupyterhub#769]
Since the LXC is a system container, it's easy to create the dev environment as if we're on a real Ubuntu OS. Personally, I prefer LXC over Docker, as the former is more powerful and it has the full ability to access the host OS's hardware, which meets HPC requirements the best than Docker does. Hopefully, LXD/LXC might be a game-changer in containerization technology. Many thanks to the TLJH creators and contributors.

**Comment by MridulS** [comment]
Thanks for raising this @GuanglinDu. As there is no action item here I'll go ahead and close this issue. You can use https://discourse.jupyter.org/c/jupyterhub/tljh/13 for more general discussions about TLJH.
