### ISSUE TITLE
Support for JupyterHub 2.0

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/the-littlest-jupyterhub#818]
### Proposed change

Currently TLJH pins to `jupyterhub==1.*` here: 

https://github.com/jupyterhub/the-littlest-jupyterhub/blob/121b4c7d8d7ec068e07e55f24ea75ce6fa0ca462/tljh/installer.py#L124

This indicates that TLJH might not be compatible with JupyterHub 2.0.

Since JupyterHub 2.0 has been out for a while, it would be interesting to see TLJH adopting it too.

### Alternative options

Not sure if TLJH can support multiple versions of JupyterHub at the same time?

### Who would use this feature?

Folks wanting to migrate to the latest stable JupyterHub version, and benefit from its new features and bug fixes.

### (Optional): Suggest a solution

Maybe just updating to `jupyterhub==2.*` could be a good starting point.

**Comment by jtpio** [comment]
> Maybe just updating to `jupyterhub==2.*` could be a good starting point.

Actually there seems to be an open PR doing just that: https://github.com/jupyterhub/the-littlest-jupyterhub/pull/777

**Comment by astrojuanlu** [comment]
Better skip to 3.0 directly? 🙂

**Comment by westurner** [comment]
- [ ] TST: Create a directory structure for migration tests between TLJH & JupyterHub major versions?

**Comment by manics** [comment]
Once we've got a [proper release out](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/838) we can install the last major release for testing upgrades.

**Comment by consideRatio** [comment]
We now have jupyterhub 3 in the main branch. Follow #873 for the work towards getting the release out.
