### ISSUE TITLE
Write stdout / stderr from all subprocess commands to log

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/the-littlest-jupyterhub#84]
In bootstrap / installer, we call a lot of external commands. However, we do *not* log their output to the logs - this means we lose very important information there. We should be logging *all* that too - but not outputting it to stdout.

**Comment by fm75** [comment]
FWIW. Unless I am missing something, tljh/installer does not configure its logger to go to any stream, so it is lost as well.

I agree that the logger output could be quite helpful. bootstrap.py logs to stderr. I think the the installer should do that as well.
