### ISSUE TITLE
install error:  Downloading & setting up user environment, Exception sha256sum hash mismatch!

### ISSUE THREAD

**Issue by yang1173350896** [jupyterhub/the-littlest-jupyterhub#864]
Hi，I have a problem when installing TLJH. Could you tell me how to install TLJH ? 
install TLJH with : 
    curl -L https://tljh.jupyter.org/bootstrap.py | sudo -E python3 - --admin  admin

log:
Existing TLJH installation not detected, installing...
Setting up hub environment...
Installing Python, venv, pip, and git via apt-get...
Setting up virtual environment at /opt/tljh/hub
Upgrading pip...
Installing TLJH installer...
Running TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Downloading & setting up user environment...

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/tljh/hub/lib/python3.10/site-packages/tljh/installer.py", line 478, in <module>
    main()
  File "/opt/tljh/hub/lib/python3.10/site-packages/tljh/installer.py", line 452, in main
    ensure_user_environment(args.user_requirements_txt_url)
  File "/opt/tljh/hub/lib/python3.10/site-packages/tljh/installer.py", line 197, in ensure_user_environment
    with conda.download_miniconda_installer(
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/tljh/hub/lib/python3.10/site-packages/tljh/conda.py", line 64, in download_miniconda_installer
    raise Exception("sha256sum hash mismatch! Downloaded file corrupted")
Exception: sha256sum hash mismatch! Downloaded file corrupted

**Comment by fomightez** [comment]
I'm not seeing that be an issue in my test just now.   
There were people reporting GitHub being down for a bit recently. Maybe it was just a networking issue at the time?  
The code below in [test_conda.py](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/a5e72046ab1d806ee3f021fe38445a0af10d6165/tests/test_conda.py) says the installer does come from GitHub:

```python
installer_url = "https://github.com/conda-forge/miniforge/releases/download/{v}/Mambaforge-{v}-Linux-{arch}.sh".format(
    v=mambaforge_version, arch=os.uname().machine
)
```

**Comment by minrk** [comment]
Yup, I suspect this was due to github being down, and the fact that we don't check the response code when downloading installers. #858 [happens to fix exactly this](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/858/files#diff-04a8d995a97bc76d9a91bfe6fb42589704793a1face3c3ed3101ba9124c397daR62), so if the github download fails, you'll see that error instead of a checksum error.
