### ISSUE TITLE
Jupyterlab is not launched for main user account

### ISSUE THREAD

**Issue by deboomce** [jupyterhub/the-littlest-jupyterhub#866]
### Bug description

Even though the default launcher is set up as jupyterlab, for the main (existing?) admin user TLJH still launches as a regular notebok environment.

#### Expected behaviour

After setting the default launcher to jupyterlab, it should be the /lab launcher for **all** users from then on.

#### Actual behaviour

For main admin / existing users, the default launcher is still /tree.

### How to reproduce

1. Set up TLJH with main user account.
2. Change default launcher to jupyterlab in config.

Nothing changes for main user account, but /lab is only used for new user accounts.

### Your personal set up

 - OS: Ubuntu 22.04 TLS

**Comment by deboomce** [comment]
It is no bug: restarting server fixes this. This should be documented though.

**Comment by minrk** [comment]
Feel free to reopen with an edited description or open a new issue about documenting the fact that configuration of the user environment or Spawner only take effect for future server launches. We have this for JupyterHub changes already, but it's not mentioned explicitly for servers.
