### ISSUE TITLE
Planning for release 1.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#873]
This is a placeholder PR to track work towards the 1.0.0 release, maintainers please feel free to edit this!

### Blocking issues/PRs

- #858
- #868
- #880 
- #901
- #915 
- #899 
- #918 
- #920 
- https://github.com/jupyterhub/oauthenticator/issues/585
- #924
- #888 
- [ ] There be notes to link to from the changelog on how to make an upgrade and what to think about when doing one
  - #81 

### Relevant but maybe not blocking issues/PRs

- #872
- #874
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/909

### Helpful notes for creating the changelog

> > Can we upgrade straight from jupyterhub 1 to jupyterhub 4?
> 
> It's tested in the jupyterhub suite and should be supported. It's a disruptive upgrade (the 1->2 transition means all user servers must be restarted and any API-issued tokens will be revoked), but for most tljh use cases, the restart-everything should be the only issue folks need to deal with.

**Comment by consideRatio** [comment]
I moved #872 to blocking as I don't want `pip install --upgrade` of requirements-base.txt to cause issues in the user environment that is unrelated to making the jupyterhub itself function.

**Comment by nsurleraux-railnova** [comment]
Hi @consideRatio,

First, I would like to say thank you for the amazing work on TLJH. Without wanting to be pushy, is there an ETA on 1.0.0 release? We would need to have JupyterHub>=4.0 for JupyterLab extensions to be picked up correctly (see https://github.com/jupyter-server/jupyter-scheduler/issues/370). If there are any known workaround in the meantime, I would highly appreciate it.

Thanks !

**Comment by consideRatio** [comment]
@nsurleraux-railnova a pull request to add the changelog for 1.0.0 is opened and ready for review, you are most welcome to provide feedback on the text if you want!

**Comment by consideRatio** [comment]
A beta release is out, check the changelog for details. At this point what remains is feedback about using the beta and documentation on how to upgrade in general.

The changelog is available at https://tljh.jupyter.org/en/latest/reference/changelog.html

**Comment by godber** [comment]
Will this 1.0 release include JupyterLab 4 and Jupyter Notebook 7, both of which recently released.

BTW, I was able to upgrade from the current latest to the `1.0.0.b1` on a small install with no problem, I had to restart the upstream reverse proxy for some reason, but it was fine after that.

**Comment by jtpio** [comment]
FYI https://github.com/jupyterhub/the-littlest-jupyterhub/pull/928 updates to Notebook 7 and JupyterLab 4.
