### ISSUE TITLE
Upgrade to jupyterhub 4?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#874]
In the main branch, we have jupyterhub 4, but we have jupyterhub 1 in the latest release (0.2.0). Can we upgrade straight from jupyterhub 1 to jupyterhub 4? If so, I suggest we go for it.

**Comment by minrk** [comment]
> Can we upgrade straight from jupyterhub 1 to jupyterhub 4? If so, I suggest we go for it.

It's tested and should be supported. It's a disruptive upgrade (the 1->2 transition means all user servers must be restarted and any API-issued tokens will be revoked), but for most tljh use cases, the restart-everything should be the only issue folks need to deal with.

**Comment by consideRatio** [comment]
Thank you @minrk, I conclude we should upgrade straight to JH 4 then, and let users know about this.
