### ISSUE TITLE
network timeouts on GCE

### ISSUE THREAD

**Issue by willirath** [jupyterhub/the-littlest-jupyterhub#90]
When playing with TLJH on a GCE VM, I ran into network timeouts **a lot**.  These caused the `bootstrap.py` installation method to fail.

Timeouts that caused the `curl | sudo python3` one-liner to fail were:

- the initial `curl .../bootstrap.py` stalling 
- pip install TLJH from Github stalling
- traefik download stalling

Depending on the region the VM was in, bootstrapping either never completed or only after several retries.  The startup-script method never made it.

**Comment by yuvipanda** [comment]
Thank you for testing this, @willirath!

Can you tell me which regions and instance types you were running into these problems with?

**Comment by willirath** [comment]
I had problems with US East 1 and some EU region (Netherlands, I think) instances with four CPUs and 8 GB RAM yesterday.  These seem to have gone away over night: I've just successfully deployed TLJH to a handful of small isntances in US east, US west and EU.

> - the initial `curl .../bootstrap.py` stalling 
> - pip install TLJH from Github stalling
> - traefik download stalling

As all the failing steps are downloading stuff from Github, the failures I saw could be due to Github rate limiting some IP ranges? I'll re-run the test when the US people start working later today :)

**Comment by willirath** [comment]
I just re-ran the setup on a bunch of VMs and got the following error on small (1vCPU, 1.7GB RAM) Ubuntu 18.04 instances in us-west-1b and eu-west-3b:

```bash
curl \
    https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/boo
tstrap.py \
    | sudo python3 - --admin XXXXXXXX
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2682  100  2682    0     0   8707      0 --:--:-- --:--:-- --:--:--  8679
Checking if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Traceback (most recent call last):
  File "<stdin>", line 83, in <module>
  File "<stdin>", line 68, in main
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyt
erhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.
```

After deleting /opt/tljh and re-runnig the installation command, I was unable to reproduce the error.

**Comment by yuvipanda** [comment]
Hmm, implementing #84 should help debug things like this. Looks like more network stuff to me. We should maybe add retry logic here.

**Comment by willirath** [comment]
This definitely looks like retrying would increase success rates here.

**Comment by willirath** [comment]
(Thanks by the way for TLJH!  It's _enormously_ useful already in this alpha state!)

**Comment by yuvipanda** [comment]
Awesome, @willirath! Can you tell us what you are using it for?

**Comment by willirath** [comment]
Sure: My first real application will be a two-day training for about 20 people to learn Parcels ( https://github.com/OceanParcels/parcels/ ) that our institute is hosting next week.

TLJH meets exactly what we need for this: Quick and easy setup on an ephemeral VM with a bunch of non-personslised user accounts that all share the same env.

I was planning to use the https://github.com/jupyterhub/jupyterhub-deploy-teaching playbook initially. But that's already much more than we'd really need. TLJH came just in time. Setup took the time I needed to get a GCE account plus a few minutes following the TLJH setup guide.

**Comment by yuvipanda** [comment]
Awesome, @willirath! Let us know how it goes :)

**Comment by yuvipanda** [comment]
@willirath there's a default memory limit per-user of 1G in the current master code. I'll probably remove it today or tomorrow. Just an FYI!

**Comment by willirath** [comment]
> @willirath there's a default memory limit per-user of 1G in the current master code. I'll probably remove it today or tomorrow. Just an FYI!

Thanks for the reminder!  I've just set it to my requirements.

**Comment by willirath** [comment]
> Awesome, @willirath! Let us know how it goes :)

First day's done: Everything worked perfectly.

**Comment by yuvipanda** [comment]
> > Awesome, @willirath! Let us know how it goes :)
> 
> First day's done: Everything worked perfectly.

Awesome! I'm gonna close this now. Thanks for reporting!
