### ISSUE TITLE
Cleanup of two git tags from 2018?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#925]
We have two git tags from 2018 that I figure we can cleanup, right?

See https://github.com/jupyterhub/the-littlest-jupyterhub/tags:
- untagged-ef83b116158213334f8e
- untagged-70fa67a678db562643c1

**Comment by consideRatio** [comment]
@yuvipanda the tags were created by you - okay to delete or do you know if they are used somehow?

**Comment by yuvipanda** [comment]
Kill 'em!

**Comment by consideRatio** [comment]
Done
