### ISSUE TITLE
Need to access old version

### ISSUE THREAD

**Issue by sanalmgr** [jupyterhub/the-littlest-jupyterhub#937]
I have built a training platform based on the old version of Littlest Jupyterhub (not the latest one). When it was time to move it to the production environment, I noticed that the version is changed, and it collapsed my entire platform because many core add-ons stopped working. Now, the platform is at stake, and I do not have any other option that could alternatively deliver the platform in a short amount of time. 

### Proposed change

Please add a feature through which users can retrieve the old version of Littlest Jupyterhub. 

### Alternative options

No other option I think of except for accessing the old version.

### Who would use this feature?

The clients (more than 2000) of my company will benefit from the platform if successfully deployed. 

### (Optional): Suggest a solution

Please allow passing the parameters to specify the retrieval of the old version of Littlest Jupyterhub.

**Comment by MridulS** [comment]
You can install the previous version by passing a git reference while setting up the VM, something like:
```
#!/bin/bash
curl -L https://tljh.jupyter.org/bootstrap.py \
  | sudo python3 - \
    --admin <admin> --version 0.2.0
```

**Comment by sanalmgr** [comment]
> You can install the previous version by passing a git reference while setting up the VM, something like:
> 
> ```
> #!/bin/bash
> curl -L https://tljh.jupyter.org/bootstrap.py \
>   | sudo python3 - \
>     --admin <admin> --version 0.2.0
> ```

It worked - running the command by specifying the version worked like a charm. You made my day!!!! Thank you so much!!!!
