### ISSUE TITLE
Setting Up Azure AD authenticator results in Bad Gateway for TLJH

### ISSUE THREAD

**Issue by arun-soliton** [jupyterhub/the-littlest-jupyterhub#950]
### Bug description
1. I have hosted  JupyterHub (TLJH) in Azure VM
2. By default the authentication is PAM
3. My primary goal is to set Azure AD authentication for login overriding the existing PAM authentication
4. I set up the authentication using the command `tljh-config` and my configurations are below (The configurations are listed using the command `sudo tljh-config show `)
![image](https://github.com/jupyterhub/the-littlest-jupyterhub/assets/136311111/5d7f412a-9efe-4225-a1e6-95596ac822e8)
5. The client id and client secret are taken from the app service created in Azure
6. After setting the configurations, I reloaded the hub using `sudo tljh-config reload` and when I accessed the IP, it shows `Bad Gateway`.

Am I missing something in the configurations?

**Comment by mhatremahesh** [comment]
I have the same problem. Is there any solution for this? I think I won't be able to change configs as I can't log in to the jupyter hub

**Comment by consideRatio** [comment]
Resolved by #959 i think.

**Comment by arun-soliton** [comment]
Thanks for the fix. Did you try authenticating with Microsoft SSO after the fix?

**Comment by arun-soliton** [comment]
@consideRatio Thanks. Will try setting it up and post the findings.
