### ISSUE TITLE
Hi I'm confronted with the same issue, I've been pulling my hair for 3 days now on how to do this.

### ISSUE THREAD

**Issue by avinashdv** [jupyterhub/the-littlest-jupyterhub#952]
Facing the same issue in Kubernetes cluster with minikube.
Generating & editing the jupyter_notebook_config.py & jupyterhub_config.py in the pods make no difference.
Testing the iframe within a react-app gives the same error
`Refused to frame 'http://127.0.0.1/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

Please correct me, If I'm wrong. 
I followed the general steps in setting up the jupyter-hub locally with minikube.
It is running fine on http://127.0.0.1/ but when I try to use this link in a react app as an iframe, I got the above stated error.
I have generated the jupyter_notebook_config.py & jupyterhub_config.py files in the pod  and edited the tornado_settings in both of them as suggested by others to allow all with *
This doesn't solve the problem.

**Comment by consideRatio** [comment]
This is a github repository for a non-k8s single-machine installation of JupyterHub. Maybe you meant to write a response to a discussion elsewhere?

I'll go for a close =/
