### ISSUE TITLE
Clarifying Licensing Issue for Anaconda

### ISSUE THREAD

**Issue by AlexisMignon** [jupyterhub/the-littlest-jupyterhub#977]
### Proposed change

TLJH uses conda as a package manager. Professional use of Anaconda requires a specific license, and it is not clear whether using TLJH requires subscribing to such a license or whether it remains in the use cases compatible with the free license.

The documentation should clarify this point and potentially provide guidelines to remain in the free licensing framework if possible.

### Who would use this feature?
This will be useful for any person wanting to use TLJH professionally.

**Comment by minrk** [comment]
While TLJH uses conda, it does not use Anaconda. Anaconda is _one distribution_ of conda packages, but not all conda packages. We get our conda packages from [conda-forge](https://conda-forge.org), which are not covered by Anaconda license terms, nor is the use of conda itself.

Now _you_ as a deployment can install packages from Anaconda (`conda install --channel anaconda`) if you want, but TLJH won't do this by default.

**Comment by yuvipanda** [comment]
Closing as answered by @minrk.
