### ISSUE TITLE
Does not pick up jupyter-ai config

### ISSUE THREAD

**Issue by ad-si** [jupyterhub/the-littlest-jupyterhub#980]
### Bug description

I'm trying to set up a default config for jupyter-ai as described here:
https://jupyter-ai.readthedocs.io/en/latest/users/index.html#configuring-as-a-config-file

I put the config file at `/home/jupyter-adrian/.jupyter/jupyter_jupyter_ai_config.json`, but the settings don't seem got get picked up. I'm still getting the error:
`OSError: Authentication environment variable OPENAI_API_KEY is not set.`

### Your personal set up

Clean install of TLJH version 4.1.6

Didn't see anything relevant in the `journalctl` logs.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a question on https://discourse.jupyter.org/ instead?

When you post there please can you show your full configuration, e.g. where are you setting `OPENAI_API_KEY`? Thanks!
